import type { StepDef } from '../types';

// Designation-led: for SA accountants the professional body (CA(SA) via SAICA,
// CIMA, ACCA, SAIPA) is the single biggest determinant of mobility — CA(SA)
// carries Mutual Recognition Agreements into the UK, Australia, NZ, Canada and
// Ireland with no further exams. See content/pathways/accounting.md.
export const ACCOUNTING_STEPS: StepDef[] = [
  {
    slug: 'personal',
    title: 'Personal Details',
    fields: [
      { id: 'personal.full_name', version: 1, label: 'Full name', type: 'text' },
      { id: 'personal.age', version: 1, label: 'Age', type: 'number', placeholder: '32' },
      { id: 'personal.city_province', version: 1, label: 'City / Province', type: 'text', placeholder: 'Cape Town, Western Cape' },
      {
        id: 'personal.whatsapp_number',
        version: 1,
        label: 'WhatsApp number',
        type: 'text',
        hint: "We'll send your feedback to this number",
        placeholder: '079 123 4567',
      },
    ],
  },
  {
    slug: 'situation',
    title: 'Your situation',
    fields: [
      {
        id: 'situation.family_status',
        version: 1,
        label: 'Family status',
        type: 'select',
        options: [
          'Single, no dependants',
          'Married / partnered, no children',
          'Married / partnered with children',
          'Single parent with children',
          'Supporting elderly parents in SA',
        ],
      },
      {
        id: 'situation.current_employment',
        version: 1,
        label: 'Current employment status',
        type: 'select',
        options: [
          'Employed full-time in my field',
          'Employed in a different field',
          'Self-employed / contracting',
          'Studying / recently qualified',
          'Unemployed',
        ],
      },
    ],
  },
  {
    slug: 'qualifications',
    title: 'Qualifications & Designation',
    supportHint: 'Not sure which designation route applies to you?',
    fields: [
      {
        id: 'qualifications.designation',
        version: 1,
        label: 'Professional designation',
        type: 'select',
        options: [
          'CA(SA) — SAICA',
          'AGA(SA) / Accounting Technician — SAICA',
          'Professional Accountant (SA) — SAIPA',
          'CIMA (CGMA)',
          'ACCA',
          'Degree only, no professional designation',
          'Studying / in articles',
          'Other',
        ],
      },
      {
        id: 'qualifications.academic',
        version: 1,
        label: 'Highest academic qualification',
        type: 'select',
        options: ['Diploma', "Bachelor's (B.Com or equivalent)", 'Honours / CTA', 'Masters', 'Other'],
      },
      { id: 'qualifications.institution', version: 1, label: 'Institution', type: 'text' },
      {
        id: 'qualifications.articles_status',
        version: 1,
        label: 'SAICA training contract / articles',
        type: 'select',
        options: ['Completed (signed off)', 'In progress', 'Not applicable / different route'],
      },
    ],
  },
  {
    slug: 'registration',
    title: 'Membership & Recognition',
    supportHint: 'Not sure about your membership standing?',
    fields: [
      {
        id: 'registration.membership_status',
        version: 1,
        label: 'Professional body membership status',
        type: 'select',
        options: [
          'Active member in good standing',
          'Member, fees in arrears',
          'Lapsed',
          'Not a member / not yet admitted',
        ],
      },
      {
        id: 'registration.overseas_body_started',
        version: 1,
        label: 'Recognition with a destination body (ICAEW, CA ANZ, CPA Canada, CPA Ireland)?',
        type: 'select',
        options: [
          'None started',
          'Researching / Letter of Good Standing requested',
          'Application submitted',
          'Completed / admitted',
        ],
      },
      {
        id: 'registration.public_practice',
        version: 1,
        label: 'Do you need audit signing / public practice rights abroad?',
        type: 'select',
        hint: 'MRA membership covers finance roles, not statutory audit signing — those need separate qualifications',
        options: [
          'No — commerce / industry roles (no audit rights needed)',
          'I hold RA / audit signing rights in SA',
          'Yes — I need public practice or audit rights abroad',
          'Not sure',
        ],
      },
    ],
  },
  {
    slug: 'experience',
    title: 'Experience',
    fields: [
      { id: 'experience.years_experience', version: 1, label: 'Years of post-qualification experience', type: 'number', placeholder: '5' },
      {
        id: 'experience.seniority',
        version: 1,
        label: 'Current / most recent level',
        type: 'select',
        options: [
          'Trainee / in articles',
          'Newly qualified (0–2 years post)',
          'Manager / Senior',
          'Senior Manager / Associate Director',
          'Director / Partner / CFO',
        ],
      },
      {
        id: 'experience.specialisms',
        version: 1,
        label: 'Function / specialism (select all that apply)',
        type: 'multiselect',
        options: [
          'External Audit',
          'Internal Audit',
          'Tax',
          'Financial Accounting / Reporting',
          'Management Accounting / FP&A',
          'Advisory / Corporate Finance',
          'Forensic',
          'Insolvency / Restructuring',
          'Public Sector',
          'Other',
        ],
      },
      {
        id: 'experience.worked_abroad',
        version: 1,
        label: 'Have you worked abroad before?',
        type: 'boolean',
      },
      {
        id: 'experience.worked_abroad_where',
        version: 1,
        label: 'Where did you work?',
        type: 'text',
        optional: true,
        showIf: { field: 'experience.worked_abroad', value: true },
      },
      {
        id: 'experience.notice_period',
        version: 1,
        label: 'Notice period at current job',
        type: 'select',
        options: ['Immediate', '1 calendar month', '2 months', '3 months', 'Other / not employed'],
      },
    ],
  },
  {
    slug: 'documents',
    title: 'Documents & Finances',
    fields: [
      {
        id: 'documents.passport_status',
        version: 1,
        label: 'Passport status',
        type: 'select',
        options: ['Valid, 2+ years remaining', 'Valid, under 2 years remaining', 'Expired', 'No passport'],
      },
      {
        id: 'documents.police_clearance',
        version: 1,
        label: 'Police clearance certificate',
        type: 'select',
        options: ['Current (within 6 months)', 'Older than 6 months', 'None'],
      },
      {
        id: 'documents.dependants_count',
        version: 1,
        label: 'Number of dependants (spouse + children)',
        type: 'number',
        placeholder: '0',
        hint: 'Enter 0 if none',
      },
      {
        id: 'documents.available_capital',
        version: 1,
        label: 'Savings / available capital for relocation',
        type: 'select',
        options: ['Under R30k', 'R30k – R70k', 'R70k – R150k', 'R150k+', 'Prefer not to say'],
        hint: 'This helps us identify realistic destinations for you',
      },
    ],
  },
  {
    slug: 'readiness',
    title: 'Language & Readiness',
    fields: [
      {
        id: 'readiness.english_rating',
        version: 1,
        label: 'How would you rate your English?',
        type: 'select',
        options: ['Basic', 'Conversational', 'Fluent', 'Native / first language'],
      },
      {
        id: 'readiness.english_test',
        version: 1,
        label: 'English test for your visa (IELTS / PTE)?',
        type: 'select',
        hint: 'Some skilled-worker visas require proof even for first-language English speakers',
        options: ['Not needed for my route', 'Not yet', 'IELTS / PTE done', 'Exempt'],
      },
      {
        id: 'readiness.target_destinations',
        version: 1,
        label: 'Target destinations (select all that apply)',
        type: 'multiselect',
        options: ['UK', 'Australia', 'New Zealand', 'Canada', 'Ireland', 'Netherlands', 'UAE', 'Other'],
      },
      {
        id: 'readiness.target_timeline',
        version: 1,
        label: 'Target timeline',
        type: 'select',
        options: ['As soon as possible', 'Within 6 months', 'Within 1 year', 'Just exploring'],
      },
    ],
  },
];
