import type { StepDef } from '../types';

export const AU_PAIR_STEPS: StepDef[] = [
  {
    slug: 'personal',
    title: 'Personal Details',
    supportHint: 'Why we ask about age and nationality',
    fields: [
      { id: 'personal.full_name', version: 1, label: 'Full name', type: 'text' },
      {
        id: 'personal.age',
        version: 1,
        label: 'Age',
        type: 'number',
        placeholder: '21',
        hint: 'Every au-pair programme has an age cap. USA J-1: 18–26. Netherlands: 18–25. Germany: 18–26 (sometimes 27). France: 18–30',
      },
      { id: 'personal.city_province', version: 1, label: 'City / Province', type: 'text', placeholder: 'Cape Town, Western Cape' },
      {
        id: 'personal.nationality',
        version: 1,
        label: 'Nationality on your passport',
        type: 'select',
        options: ['South African', 'Dual (SA + other)', 'Other'],
      },
      {
        id: 'personal.gender',
        version: 1,
        label: 'Gender',
        type: 'select',
        options: ['Female', 'Male', 'Prefer not to say'],
        hint: 'Most au-pair host families request a female au pair; declaring opens fewer or different placements rather than blocking you',
      },
      {
        id: 'personal.whatsapp_number',
        version: 1,
        label: 'WhatsApp number',
        type: 'text',
        hint: "We'll send your feedback to this number",
        placeholder: '079 123 4567',
      },
    ],
  },
  {
    slug: 'experience',
    title: 'Childcare Experience',
    supportHint: 'What counts as childcare experience?',
    fields: [
      {
        id: 'experience.childcare_hours',
        version: 1,
        label: 'Documented hours of childcare experience',
        type: 'select',
        options: ['Under 50 hours', '50–200 hours', '200–500 hours', '500+ hours', 'Not sure'],
        hint: 'USA J-1 requires 200+ documented hours. Babysitting, nannying, crèche, after-school care all count if a reference can confirm them',
      },
      {
        id: 'experience.contexts',
        version: 1,
        label: 'Where you have cared for children (select all that apply)',
        type: 'multiselect',
        options: ['Family (siblings, cousins)', 'Babysitting (paid)', 'Nanny / au pair (paid)', 'Crèche / preschool', 'After-school care', 'Holiday programmes', 'Sunday school / youth group', 'Sports coaching', 'None'],
      },
      {
        id: 'experience.youngest_age',
        version: 1,
        label: 'Youngest age you have cared for',
        type: 'select',
        options: ['Under 12 months (infant)', '1–2 years (toddler)', '3–5 years (preschool)', '6–12 years (school age)', '13+ years (teen)', 'Not sure'],
        hint: 'Host families with infants strongly prefer au pairs with infant experience; under-2 placements often require it',
      },
      {
        id: 'experience.references',
        version: 1,
        label: 'Childcare references you can provide',
        type: 'select',
        options: ['3+ contactable references', '1–2 references', 'None yet'],
        hint: 'USA J-1 sponsors typically require 3 non-family written references with contactable phone + email',
      },
      {
        id: 'experience.first_aid',
        version: 1,
        label: 'First aid / CPR certification',
        type: 'select',
        options: ['Current (within 2 years)', 'Expired', 'None'],
      },
    ],
  },
  {
    slug: 'practical',
    title: 'Driving & Practical Skills',
    fields: [
      {
        id: 'practical.drivers_licence',
        version: 1,
        label: "Driver's licence",
        type: 'select',
        options: ['Code B (full)', 'Learners only', 'In progress', 'None'],
        hint: "USA J-1 effectively requires a full driver's licence. Most European host families also expect one",
      },
      {
        id: 'practical.driving_experience',
        version: 1,
        label: 'Driving experience',
        type: 'select',
        options: ['Daily driver (1+ year)', 'Occasional driver', 'Just got licence', 'Have not driven independently', 'N/A'],
      },
      {
        id: 'practical.idp',
        version: 1,
        label: 'International Driving Permit (IDP) status',
        type: 'select',
        options: ['Already have it', 'Will apply via AA SA', 'Not needed (destination accepts SA licence)', 'Not sure'],
      },
      {
        id: 'practical.swimming',
        version: 1,
        label: 'Can you swim?',
        type: 'select',
        options: ['Yes — confident swimmer', 'Yes — basic', 'No'],
        hint: 'Many host families request swim-confident au pairs (pool/beach supervision)',
      },
    ],
  },
  {
    slug: 'qualifications',
    title: 'Education & Languages',
    fields: [
      {
        id: 'qualifications.highest_qualification',
        version: 1,
        label: 'Highest completed qualification',
        type: 'select',
        options: ['Matric (NSC)', 'Diploma / Certificate', 'Bachelor degree', 'Honours / Postgrad', 'Currently studying', 'Other'],
      },
      {
        id: 'qualifications.english_rating',
        version: 1,
        label: 'How would you rate your English?',
        type: 'select',
        options: ['Basic', 'Conversational', 'Fluent', 'Native / first language'],
      },
      {
        id: 'qualifications.german',
        version: 1,
        label: 'German language ability',
        type: 'select',
        options: ['None', 'A1 (basic) — no certificate', 'A1 certificate (Goethe / telc)', 'A2 or higher', 'Goethe-Institut student'],
        hint: 'Germany requires a Goethe or telc A1 certificate at visa application — without it the German route is closed',
      },
      {
        id: 'qualifications.french',
        version: 1,
        label: 'French language ability',
        type: 'select',
        options: ['None', 'Basic', 'A1 / DELF A1', 'A2 or higher'],
        hint: 'French host families prefer A1+; not a strict visa requirement but enrolment in a French language school is part of the VLS-TS process',
      },
      {
        id: 'qualifications.other_languages',
        version: 1,
        label: 'Other languages spoken',
        type: 'text',
        optional: true,
        placeholder: 'e.g. Afrikaans, isiZulu',
      },
    ],
  },
  {
    slug: 'documents',
    title: 'Documents & Finances',
    fields: [
      {
        id: 'documents.passport_status',
        version: 1,
        label: 'Passport status',
        type: 'select',
        options: ['Valid — 2+ years remaining', 'Valid — under 2 years remaining', 'Expired', 'No passport'],
      },
      {
        id: 'documents.police_clearance',
        version: 1,
        label: 'SAPS Police Clearance Certificate',
        type: 'select',
        options: ['Current (within 6 months)', 'Older than 6 months', 'Applied / in progress', 'None'],
      },
      {
        id: 'documents.dirco_legalisation',
        version: 1,
        label: 'DIRCO Legalisation (apostille) of PCC + birth certificate',
        type: 'select',
        options: ['Done', 'In progress', 'Not started', "I don't know what this is"],
        hint: 'DIRCO Legalisation Services issues the Hague-Convention apostille — a stamp on your document. The service is free; private agents like Apostil.co.za only courier documents to/from DIRCO for a fee',
      },
      {
        id: 'documents.medical',
        version: 1,
        label: 'Medical examination / fitness certificate',
        type: 'select',
        options: ['Done — within 6 months', 'Done — older', 'Not done'],
      },
      {
        id: 'documents.dependants_count',
        version: 1,
        label: 'Number of dependants (children of your own)',
        type: 'number',
        placeholder: '0',
        hint: 'Most au-pair programmes require no children of your own — declare honestly',
      },
      {
        id: 'documents.available_capital',
        version: 1,
        label: 'Savings / available capital for pre-departure costs',
        type: 'select',
        options: ['Under R15k', 'R15k – R30k', 'R30k – R60k', 'R60k+', 'Prefer not to say'],
        hint: 'Au-pair pre-departure costs are typically R15k–R30k (PCC, apostille, visa fee, medical, programme fee, flight if not covered)',
      },
    ],
  },
  {
    slug: 'readiness',
    title: 'Destinations & Timeline',
    fields: [
      {
        id: 'readiness.target_destinations',
        version: 1,
        label: 'Target destinations (select all that apply)',
        type: 'multiselect',
        options: ['USA (J-1 Au Pair)', 'Netherlands', 'Germany', 'France', 'Belgium', 'Denmark', 'Open to recommendations'],
      },
      {
        id: 'readiness.priority',
        version: 1,
        label: 'What matters most to you?',
        type: 'select',
        options: ['USA J-1 specifically', 'Highest stipend / savings', 'Cultural experience', 'EU / Schengen access', 'Family-friendly destination', 'Shortest commitment'],
      },
      {
        id: 'readiness.contract_length',
        version: 1,
        label: 'How long are you willing to commit?',
        type: 'select',
        options: ['6 months', '12 months', '12 months + extension', '24 months (USA max)', 'Not sure'],
        hint: 'USA J-1 is a 12-month minimum with optional 6/9/12-month extension. Most European programmes are 12 months',
      },
      {
        id: 'readiness.target_timeline',
        version: 1,
        label: 'Target timeline',
        type: 'select',
        options: ['As soon as possible', 'Within 6 months', 'Within 1 year', 'Just exploring'],
      },
    ],
  },
];
