import type { StepDef } from '../types';

export const ENGINEERING_STEPS: StepDef[] = [
  {
    slug: 'personal',
    title: 'Personal Details',
    supportHint: 'Why we ask about age',
    fields: [
      { id: 'personal.full_name', version: 1, label: 'Full name', type: 'text' },
      {
        id: 'personal.age',
        version: 1,
        label: 'Age',
        type: 'number',
        placeholder: '32',
        hint: 'New Zealand residence applicants must be 55 or younger at time of application',
      },
      { id: 'personal.city_province', version: 1, label: 'City / Province', type: 'text', placeholder: 'Cape Town, Western Cape' },
      {
        id: 'personal.nationality',
        version: 1,
        label: 'Nationality on your passport',
        type: 'select',
        options: ['South African', 'Dual (SA + EU/UK/other)', 'Other'],
        hint: 'SA nationals now need both an Irish CSEP permit AND a Long Stay D visa (changed July 2024)',
      },
      {
        id: 'personal.whatsapp_number',
        version: 1,
        label: 'WhatsApp number',
        type: 'text',
        hint: "We'll send your feedback to this number",
        placeholder: '079 123 4567',
      },
    ],
  },
  {
    slug: 'qualifications',
    title: 'Engineering Qualification',
    supportHint: 'Why the Accord question matters',
    fields: [
      {
        id: 'qualifications.degree_level',
        version: 1,
        label: 'Highest engineering qualification',
        type: 'select',
        options: [
          'BEng / BSc(Eng) (4-year professional degree)',
          'BTech / BEngTech (3-year technologist)',
          'National Diploma (3-year technician)',
          'Honours / Postgrad in engineering',
          'Master / PhD in engineering',
          'Currently studying',
          'Non-engineering degree',
        ],
        hint: 'Washington Accord covers BEng (4-year). Sydney Accord covers BTech. Dublin Accord covers NDip technicians',
      },
      {
        id: 'qualifications.discipline',
        version: 1,
        label: 'Engineering discipline',
        type: 'select',
        options: [
          'Civil',
          'Structural',
          'Mechanical',
          'Electrical',
          'Electronics / Telecommunications',
          'Chemical',
          'Industrial',
          'Mining',
          'Mechatronics',
          'Aerospace / Aeronautical',
          'Geotechnical',
          'Environmental',
          'Materials / Metallurgical',
          'Other',
        ],
      },
      {
        id: 'qualifications.institution',
        version: 1,
        label: 'Institution',
        type: 'text',
        placeholder: 'e.g. University of Pretoria',
      },
      {
        id: 'qualifications.graduation_year',
        version: 1,
        label: 'Graduation year',
        type: 'number',
        placeholder: '2018',
        hint: 'Accord eligibility depends on year falling within your programme\'s accredited intake period',
      },
      {
        id: 'qualifications.iea_checked',
        version: 1,
        label: 'Have you checked your programme on the IEA Qualification Checker?',
        type: 'select',
        options: [
          'Yes — listed as fully accredited',
          'Yes — only provisionally accredited',
          'Yes — not listed',
          'No — not yet',
          "I don't know what this is",
        ],
        hint: 'ieagreements.org/for-engineers/qualification-checker — 5-minute check that decides AUD $539 (Accord) vs AUD $1,001 (CDR) for Engineers Australia',
      },
    ],
  },
  {
    slug: 'registration',
    title: 'ECSA Registration & Experience',
    supportHint: 'Not sure about ECSA categories?',
    fields: [
      {
        id: 'registration.ecsa_status',
        version: 1,
        label: 'ECSA registration status',
        type: 'select',
        options: [
          'Pr Eng (Professional Engineer)',
          'Pr Tech Eng (Professional Engineering Technologist)',
          'Pr Techni Eng (Professional Engineering Technician)',
          'Candidate (Candidate Eng / Tech / Techni)',
          'Graduate (not yet registered)',
          'Lapsed',
          'Not registered',
        ],
        hint: 'Pr Eng with 1+ year standing unlocks the SAICE–ICE Mutual Exemption Agreement (UK Chartered Engineer pathway)',
      },
      {
        id: 'registration.ecsa_number',
        version: 1,
        label: 'ECSA registration number',
        type: 'text',
        optional: true,
        placeholder: 'e.g. 20180123',
      },
      {
        id: 'registration.years_experience',
        version: 1,
        label: 'Years of engineering work experience (post-graduation)',
        type: 'number',
        placeholder: '5',
      },
      {
        id: 'registration.employer_type',
        version: 1,
        label: 'Current / most recent employer type',
        type: 'select',
        options: ['Consulting engineering firm', 'Contractor / construction', 'Industrial / manufacturing', 'Mining', 'Government / state-owned', 'Tech / software', 'Other'],
      },
      {
        id: 'registration.saice_member',
        version: 1,
        label: 'Are you a SAICE member? (civil engineers only)',
        type: 'select',
        options: ['Yes — current', 'Lapsed', 'No', 'Not applicable (non-civil)'],
        hint: 'SAICE membership + Pr Eng (1 yr standing) unlocks UK ICE Chartered Engineer route',
      },
    ],
  },
  {
    slug: 'assessment',
    title: 'Skills Assessment & Credential Recognition',
    supportHint: 'Each destination has a different assessor',
    fields: [
      {
        id: 'assessment.ea_status',
        version: 1,
        label: 'Engineers Australia Migration Skills Assessment',
        type: 'select',
        options: ['Outcome letter received', 'Submitted — in progress', 'Not started', 'Not applying to Australia'],
        hint: 'EA assessment takes 6–9 months; outcome letter valid 3 years',
      },
      {
        id: 'assessment.enz_status',
        version: 1,
        label: 'Engineering New Zealand Credential Check',
        type: 'select',
        options: ['Completed', 'Submitted — in progress', 'Not started', 'Not applying to NZ'],
        hint: 'NZ$550 fee, 7–10 working days',
      },
      {
        id: 'assessment.ecctis_status',
        version: 1,
        label: 'Ecctis UK ENIC Equivalency (for UK Skilled Worker)',
        type: 'select',
        options: ['Reference letter received', 'Applied — in progress', 'Not started', 'Not applying to UK'],
        hint: 'Online application; SA degree must be assessed via Ecctis (no SAQA/DIRCO apostille needed for UK visa)',
      },
      {
        id: 'assessment.wes_status',
        version: 1,
        label: 'WES Educational Credential Assessment (for Canada)',
        type: 'select',
        options: ['ECA letter received', 'Submitted — in progress', 'Not started', 'Not applying to Canada'],
        hint: 'CAD $272 + courier; SA university must send transcripts directly to WES',
      },
      {
        id: 'assessment.saqa_letter',
        version: 1,
        label: 'SAQA Verification of National Qualifications',
        type: 'select',
        options: ['Already obtained', 'Applied / in progress', 'Not started', "I don't know what this is"],
        hint: 'Required before DIRCO can apostille your degree (NZ, Ireland). Not needed for UK Ecctis or AU Engineers Australia',
      },
    ],
  },
  {
    slug: 'documents',
    title: 'Documents & Finances',
    fields: [
      {
        id: 'documents.passport_status',
        version: 1,
        label: 'Passport status',
        type: 'select',
        options: ['Valid — 2+ years remaining', 'Valid — under 2 years remaining', 'Expired', 'No passport'],
      },
      {
        id: 'documents.police_clearance',
        version: 1,
        label: 'SAPS Police Clearance Certificate',
        type: 'select',
        options: ['Current (within 6 months)', 'Older than 6 months', 'Applied / in progress', 'None'],
        hint: 'Valid 6 months from issue. Time it to arrive near visa lodgement, not before',
      },
      {
        id: 'documents.dirco_apostille',
        version: 1,
        label: 'DIRCO Apostille on PCC + SAQA letter',
        type: 'select',
        options: ['Done', 'In progress', 'Not started', 'Not applicable (UK / Ecctis route)'],
        hint: 'DIRCO service is free. Cannot apostille a raw degree — only the SAQA verification letter',
      },
      {
        id: 'documents.transcripts',
        version: 1,
        label: 'Academic transcripts from your university',
        type: 'select',
        options: ['Sealed copies on hand', 'Requested from registrar', 'Not started'],
        hint: 'Most assessors (EA, WES) require transcripts sent directly from the registrar — you cannot hand-deliver',
      },
      {
        id: 'documents.dependants_count',
        version: 1,
        label: 'Number of dependants (spouse + children)',
        type: 'number',
        placeholder: '0',
        hint: 'Enter 0 if none',
      },
      {
        id: 'documents.available_capital',
        version: 1,
        label: 'Savings / available capital for relocation',
        type: 'select',
        options: ['Under R50k', 'R50k – R100k', 'R100k – R200k', 'R200k – R400k', 'R400k+', 'Prefer not to say'],
        hint: 'Engineering relocation typically needs R80k–R200k upfront (assessment + visa + flights + settling). Canada requires proof of settlement funds in addition',
      },
    ],
  },
  {
    slug: 'readiness',
    title: 'English, Destinations & Timeline',
    supportHint: 'Each country accepts a different English test',
    fields: [
      {
        id: 'readiness.english_rating',
        version: 1,
        label: 'How would you rate your English?',
        type: 'select',
        options: ['Conversational', 'Fluent', 'Native / first language'],
      },
      {
        id: 'readiness.english_test',
        version: 1,
        label: 'English test taken (if any)',
        type: 'select',
        options: [
          'IELTS Academic (general purpose)',
          'IELTS for UKVI (UK Skilled Worker)',
          'IELTS General Training (Canada Express Entry)',
          'PTE Academic',
          'None yet',
        ],
        hint: 'Standard IELTS Academic is NOT accepted for UK Skilled Worker. PTE Academic is NOT accepted for Canada Express Entry',
      },
      {
        id: 'readiness.english_score',
        version: 1,
        label: 'Test score (overall + lowest band)',
        type: 'text',
        optional: true,
        placeholder: 'e.g. IELTS 7.5 overall, 6.5 lowest',
      },
      {
        id: 'readiness.german_ability',
        version: 1,
        label: 'German language ability',
        type: 'select',
        options: ['None', 'A1 (basic) — no certificate', 'A2 / B1 certificate', 'B2 or higher', 'Native / near-native'],
        hint: 'Germany is open to engineers but generally requires B1–B2 German for non-international roles',
      },
      {
        id: 'readiness.target_destinations',
        version: 1,
        label: 'Target destinations (select all)',
        type: 'multiselect',
        options: ['Australia', 'New Zealand', 'United Kingdom', 'Ireland', 'Canada', 'Germany', 'Open to recommendations'],
      },
      {
        id: 'readiness.priority',
        version: 1,
        label: 'What matters most to you?',
        type: 'select',
        options: [
          'Fastest path to permanent residence',
          'Highest salary',
          'Largest SA diaspora / easiest landing',
          'Tax efficiency',
          'Family-friendly destination',
          'Specific role / industry sector',
        ],
      },
      {
        id: 'readiness.notice_period',
        version: 1,
        label: 'Notice period at current job',
        type: 'select',
        options: ['Immediate', '1 month', '2 months', '3 months', 'Other / not employed'],
      },
      {
        id: 'readiness.target_timeline',
        version: 1,
        label: 'Target timeline',
        type: 'select',
        options: ['As soon as possible', 'Within 6 months', 'Within 1 year', 'Within 2 years', 'Just exploring'],
      },
    ],
  },
];
