import type { StepDef } from '../types';

export const FARMING_STEPS: StepDef[] = [
  {
    slug: 'personal',
    title: 'Personal Details',
    fields: [
      { id: 'personal.full_name', version: 1, label: 'Full name', type: 'text' },
      {
        id: 'personal.age',
        version: 1,
        label: 'Age',
        type: 'number',
        placeholder: '32',
        hint: 'Most farming routes are open to 18+, no upper cap. Australia working holiday excludes SA.',
      },
      { id: 'personal.city_province', version: 1, label: 'City / Province', type: 'text', placeholder: 'Cape Town, Western Cape' },
      {
        id: 'personal.whatsapp_number',
        version: 1,
        label: 'WhatsApp number',
        type: 'text',
        hint: "We'll send your feedback to this number",
        placeholder: '079 123 4567',
      },
    ],
  },
  {
    slug: 'experience',
    title: 'Farm Experience',
    supportHint: 'Not sure how to describe your farm experience?',
    fields: [
      {
        id: 'experience.years_farm_experience',
        version: 1,
        label: 'Years of farm or agricultural experience',
        type: 'number',
        placeholder: '0',
        hint: '0 is fine for UK SWV. 3+ unlocks NZ Global Workforce Seasonal Visa.',
      },
      {
        id: 'experience.experience_types',
        version: 1,
        label: 'Type of farm work you\'ve done (select all)',
        type: 'multiselect',
        options: [
          'Horticulture / orchard',
          'Livestock / dairy',
          'Poultry',
          'Crops / grain',
          'Machinery / equipment operator',
          'Irrigation',
          'Packing / grading',
          'Other',
          'None yet',
        ],
      },
      {
        id: 'experience.prior_farm_abroad',
        version: 1,
        label: 'Have you worked on a farm abroad before? (select all)',
        type: 'multiselect',
        options: [
          'None',
          'UK (Seasonal Worker Visa)',
          'USA (H-2A Visa)',
          'Canada',
          'New Zealand',
          'Other country',
        ],
      },
      {
        id: 'experience.uk_swv_dates',
        version: 1,
        label: 'When did you last work in the UK on the Seasonal Worker Visa?',
        type: 'text',
        placeholder: 'e.g. Apr–Oct 2025',
        hint: 'List start + end month for each season. Needed to check the new 4-month cooling-off rule (Nov 2025).',
        showIf: { field: 'experience.prior_farm_abroad', includes: 'UK (Seasonal Worker Visa)' },
      },
      {
        id: 'experience.prior_farm_abroad_where',
        version: 1,
        label: 'Other country — where did you work?',
        type: 'text',
        optional: true,
        placeholder: 'e.g. Australia 2023, Israel 2022',
        showIf: { field: 'experience.prior_farm_abroad', includes: 'Other country' },
      },
    ],
  },
  {
    slug: 'skills',
    title: 'Skills & Fitness',
    fields: [
      {
        id: 'skills.drivers_licence',
        version: 1,
        label: "Driver's licence",
        type: 'select',
        options: [
          'Full SA Code 8/EB',
          'Code 10/14 (LDV/HDV)',
          'Heavy machinery / Code EC',
          'Tractor experience only (no licence)',
          'None',
        ],
        hint: 'Code 10+ and machinery experience widen H-2A and Canada LMIA options',
      },
      {
        id: 'skills.physical_fitness',
        version: 1,
        label: 'Physical fitness for outdoor manual work',
        type: 'select',
        options: [
          'Excellent — daily heavy labour now',
          'Good — fit and active',
          'Fair — would need to build up',
          'Poor — health concerns',
        ],
      },
      {
        id: 'skills.english_rating',
        version: 1,
        label: 'How would you rate your English?',
        type: 'select',
        options: ['Basic', 'Conversational', 'Fluent', 'Native / first language'],
      },
    ],
  },
  {
    slug: 'documents',
    title: 'Documents & Finances',
    fields: [
      {
        id: 'documents.passport_status',
        version: 1,
        label: 'Passport status',
        type: 'select',
        options: ['Valid — 18+ months remaining', 'Valid — under 18 months remaining', 'Expired', 'No passport'],
      },
      {
        id: 'documents.police_clearance',
        version: 1,
        label: 'SA Police Clearance Certificate (SAPS)',
        type: 'select',
        options: ['Current (within 6 months)', 'Older than 6 months', 'Applied — waiting', 'None'],
      },
      {
        id: 'documents.available_capital',
        version: 1,
        label: 'Savings available for visa fees + flights + first weeks abroad',
        type: 'select',
        options: ['Under R10k', 'R10k – R30k', 'R30k – R60k', 'R60k+', 'Prefer not to say'],
        hint: 'UK ≈ R20–30k upfront (visa fee + flight). USA H-2A employer reimburses most costs.',
      },
      {
        id: 'documents.funding_source',
        version: 1,
        label: 'Primary funding source',
        type: 'select',
        options: ['Own savings', 'Family contribution', 'Loan', 'Combination', 'Need to find funding'],
      },
      {
        id: 'documents.visa_refusal_history',
        version: 1,
        label: 'Have you been refused a visa before?',
        type: 'select',
        options: ['None', 'Yes — UK', 'Yes — USA', 'Yes — other country', 'Multiple'],
        hint: 'Be honest — refused applications affect future visas',
      },
    ],
  },
  {
    slug: 'recruiter',
    title: 'Recruiter & Programme',
    supportHint: 'Not sure if your recruiter is legitimate?',
    fields: [
      {
        id: 'recruiter.has_recruiter_contact',
        version: 1,
        label: 'Are you already in contact with a recruiter, agent, or scheme operator?',
        type: 'boolean',
      },
      {
        id: 'recruiter.recruiter_name',
        version: 1,
        label: 'Recruiter / operator name',
        type: 'text',
        optional: true,
        placeholder: 'e.g. Concordia, HOPS, Farm 4 USA',
        hint: "We cross-check against licensed UK operators (Concordia, HOPS, Pro-Force, Fruitful, Agri HR) and verified H-2A agents (Farm 4 USA, Country Labour, Farm Recruit USA, Greenfields).",
        showIf: { field: 'recruiter.has_recruiter_contact', value: true },
      },
      {
        id: 'recruiter.paid_recruiter_already',
        version: 1,
        label: 'Have you already paid this recruiter any fees?',
        type: 'boolean',
        optional: true,
        hint: 'Licensed UK operators and H-2A agents cannot legally charge worker fees. If you\'ve paid, tell us — we can help you assess.',
        showIf: { field: 'recruiter.has_recruiter_contact', value: true },
      },
    ],
  },
  {
    slug: 'readiness',
    title: 'Destination & Timing',
    fields: [
      {
        id: 'readiness.target_destinations',
        version: 1,
        label: 'Target destinations (select all)',
        type: 'multiselect',
        options: ['UK', 'USA', 'Canada', 'New Zealand', 'Australia', 'Open'],
        hint: 'Australia: skilled / management routes only for SA — no seasonal scheme.',
      },
      {
        id: 'readiness.has_dependants',
        version: 1,
        label: 'Do you have a spouse or dependent children you\'d hope to bring?',
        type: 'boolean',
        optional: true,
        hint: 'Mainly relevant for longer-term Canada routes that can lead to residency.',
        showIf: { field: 'readiness.target_destinations', includes: 'Canada' },
      },
      {
        id: 'readiness.target_window',
        version: 1,
        label: 'Target programme window (select all that work for you)',
        type: 'multiselect',
        options: [
          'UK horticulture (Apr–Oct)',
          'UK poultry (Oct–Dec)',
          'USA H-2A spring/summer',
          'USA H-2A year-round',
          'Canada (Mar–Nov)',
          'NZ (Oct–May)',
          'Open',
        ],
      },
      {
        id: 'readiness.target_year',
        version: 1,
        label: 'Target departure year',
        type: 'select',
        options: ['2026', '2027', '2028', 'Just exploring'],
      },
      {
        id: 'readiness.commitment_length',
        version: 1,
        label: 'How long can you commit?',
        type: 'select',
        options: [
          'Single season (3–6 months)',
          'Multiple seasons (repeat)',
          'Open-ended where possible',
        ],
      },
    ],
  },
];
