import type { StepDef } from '../types';

export const HOSPITALITY_STEPS: StepDef[] = [
  {
    slug: 'personal',
    title: 'Personal Details',
    fields: [
      { id: 'personal.full_name', version: 1, label: 'Full name', type: 'text' },
      {
        id: 'personal.age',
        version: 1,
        label: 'Age',
        type: 'number',
        placeholder: '32',
        hint: 'Most hospitality routes are open 18–55. UAE often prefers under 45 for line roles.',
      },
      { id: 'personal.city_province', version: 1, label: 'City / Province', type: 'text', placeholder: 'Cape Town, Western Cape' },
      {
        id: 'personal.whatsapp_number',
        version: 1,
        label: 'WhatsApp number',
        type: 'text',
        hint: "We'll send your feedback to this number",
        placeholder: '079 123 4567',
      },
    ],
  },
  {
    slug: 'experience',
    title: 'Hospitality Experience',
    supportHint: 'Not sure how to describe your hospitality experience?',
    fields: [
      {
        id: 'experience.years_hospitality_experience',
        version: 1,
        label: 'Years of professional hospitality experience',
        type: 'number',
        placeholder: '0',
        hint: '5+ years senior chef opens AU 482 (via VETASSESS). 2+ years opens UAE 5-star hotel routes.',
      },
      {
        id: 'experience.primary_role',
        version: 1,
        label: 'Primary role',
        type: 'select',
        options: [
          'Head Chef / Executive Chef',
          'Sous Chef / Senior Chef de Partie',
          'Chef de Partie / Line Chef',
          'Commis Chef / Junior Cook',
          'Pastry / Bakery',
          'Restaurant / F&B Manager',
          'Waiter / Front of House',
          'Bartender / Mixologist',
          'Hotel Reception / Concierge',
          'Housekeeping',
          'Kitchen Porter / Steward',
          'Other',
        ],
        hint: 'Australia 482 only opens for Chef (ANZSCO 351311) — head, sous, senior chef. Cooks (351411) face TRADE assessment with no PR pathway.',
      },
      {
        id: 'experience.cuisine_specialisation',
        version: 1,
        label: 'Cuisine speciality (select all)',
        type: 'multiselect',
        options: [
          'Continental / European',
          'Mediterranean',
          'Asian (Chinese / Thai / Japanese)',
          'Indian',
          'Middle Eastern',
          'African',
          'Pastry / Bakery',
          'Pizza / Italian',
          'No speciality / general',
        ],
        hint: 'UAE 5-star hotels recruit heavily for European, Mediterranean, and Asian specialists.',
      },
      {
        id: 'experience.venue_type',
        version: 1,
        label: 'Type of venue you\'ve worked in (select all)',
        type: 'multiselect',
        options: [
          '5-star hotel / resort',
          '4-star hotel',
          'Fine-dining restaurant',
          'Casual / mid-tier restaurant',
          'Quick-service / fast food',
          'Cruise ship',
          'Catering / events',
          'Game lodge / safari',
          'Other',
        ],
      },
      {
        id: 'experience.prior_hospitality_abroad',
        version: 1,
        label: 'Have you worked in hospitality abroad before? (select all)',
        type: 'multiselect',
        options: [
          'None',
          'UAE / Dubai',
          'UK',
          'Saudi Arabia / Qatar / Bahrain',
          'Australia',
          'Canada',
          'Cruise ship',
          'Other country',
        ],
      },
      {
        id: 'experience.prior_hospitality_abroad_where',
        version: 1,
        label: 'Other country — where did you work?',
        type: 'text',
        optional: true,
        placeholder: 'e.g. Maldives 2023, Mauritius 2022',
        showIf: { field: 'experience.prior_hospitality_abroad', includes: 'Other country' },
      },
    ],
  },
  {
    slug: 'qualifications',
    title: 'Qualifications & Skills',
    fields: [
      {
        id: 'qualifications.formal_qualification',
        version: 1,
        label: 'Highest hospitality / cookery qualification',
        type: 'select',
        options: [
          'Occupational Certificate: Chef (QCTO, NQF 5)',
          'National Certificate: Professional Cookery (CATHSSETA, NQF 2–4)',
          'Diploma in Culinary Arts / Hotel Management',
          'Degree in Hospitality / Culinary Arts',
          'In-house training only — no formal qualification',
          'None',
        ],
        hint: 'Australia VETASSESS requires a SAQA-aligned qualification PLUS a trade test. NQF 5 Chef cert is the safer baseline.',
      },
      {
        id: 'qualifications.trade_test',
        version: 1,
        label: 'Do you hold a Trade Test Certificate (Red Seal / Olifantsfontein)?',
        type: 'select',
        options: ['Yes — current', 'In progress', 'No', 'Not sure'],
        hint: 'Trade test is a hard requirement for VETASSESS Pathway 1 (Australia) and helps UAE 5-star applications.',
      },
      {
        id: 'qualifications.english_rating',
        version: 1,
        label: 'How would you rate your English?',
        type: 'select',
        options: ['Basic', 'Conversational', 'Fluent', 'Native / first language'],
      },
      {
        id: 'qualifications.english_test',
        version: 1,
        label: 'English test status (IELTS / OET / PTE)',
        type: 'select',
        options: [
          'Have valid IELTS/OET/PTE (within 2 years)',
          'Booked / studying for one',
          'Not yet — need to take one',
          'Not applicable to my target',
        ],
        hint: 'UK Skilled Worker requires B1+ unless qualification was taught in English. AU 482 typically requires IELTS 5.0.',
      },
    ],
  },
  {
    slug: 'documents',
    title: 'Documents & Finances',
    fields: [
      {
        id: 'documents.passport_status',
        version: 1,
        label: 'Passport status',
        type: 'select',
        options: ['Valid — 18+ months remaining', 'Valid — under 18 months remaining', 'Expired', 'No passport'],
      },
      {
        id: 'documents.police_clearance',
        version: 1,
        label: 'SA Police Clearance Certificate (SAPS)',
        type: 'select',
        options: ['Current (within 6 months)', 'Older than 6 months', 'Applied — waiting', 'None'],
      },
      {
        id: 'documents.available_capital',
        version: 1,
        label: 'Savings available for visa fees + flights + first weeks abroad',
        type: 'select',
        options: ['Under R10k', 'R10k – R30k', 'R30k – R60k', 'R60k+', 'Prefer not to say'],
        hint: 'UAE: low (employer normally pays). Australia: ~R70–90k upfront for VETASSESS + visa. UK: R20–40k.',
      },
      {
        id: 'documents.funding_source',
        version: 1,
        label: 'Primary funding source',
        type: 'select',
        options: ['Own savings', 'Family contribution', 'Loan', 'Combination', 'Need to find funding'],
      },
      {
        id: 'documents.visa_refusal_history',
        version: 1,
        label: 'Have you been refused a visa before?',
        type: 'select',
        options: ['None', 'Yes — UK', 'Yes — UAE', 'Yes — Australia', 'Yes — other country', 'Multiple'],
        hint: 'Be honest — refused applications affect future visas',
      },
    ],
  },
  {
    slug: 'recruiter',
    title: 'Recruiter & Programme',
    supportHint: 'Not sure if your recruiter is legitimate?',
    fields: [
      {
        id: 'recruiter.has_recruiter_contact',
        version: 1,
        label: 'Are you already in contact with a recruiter, agent, or hotel group?',
        type: 'boolean',
      },
      {
        id: 'recruiter.recruiter_name',
        version: 1,
        label: 'Recruiter / hotel group name',
        type: 'text',
        optional: true,
        placeholder: 'e.g. Marriott, Accor, Jumeirah, ITP, Berkeley Scott',
        hint: 'We cross-check against MOHRE-licensed recruiters (UAE), CATHSSETA-aligned SA agencies, and known fraud patterns.',
        showIf: { field: 'recruiter.has_recruiter_contact', value: true },
      },
      {
        id: 'recruiter.paid_recruiter_already',
        version: 1,
        label: 'Have you already paid this recruiter any fees?',
        type: 'boolean',
        optional: true,
        hint: 'UAE law (MOHRE Resolution 47/2022) requires the employer — not the worker — to pay all recruitment costs. SA recruiters charging placement fees violate the SA Employment Services Act 2014. If you\'ve paid, tell us — we can help you assess.',
        showIf: { field: 'recruiter.has_recruiter_contact', value: true },
      },
      {
        id: 'recruiter.uk_pre_july_2025_visa',
        version: 1,
        label: 'Have you held a UK Skilled Worker visa with continuous permission since before 22 July 2025?',
        type: 'boolean',
        optional: true,
        hint: 'From 22 July 2025 the UK Skilled Worker route closed to new SA hospitality applicants. Only existing visa holders extending or switching employers remain eligible under transitional rules.',
      },
    ],
  },
  {
    slug: 'readiness',
    title: 'Destination & Timing',
    fields: [
      {
        id: 'readiness.target_destinations',
        version: 1,
        label: 'Target destinations (select all)',
        type: 'multiselect',
        options: ['UAE / Dubai', 'UK', 'Australia', 'Canada', 'Cruise ship', 'Open'],
        hint: 'UK is effectively closed to new SA hospitality applicants since 22 Jul 2025. UAE is the most accessible high-volume route.',
      },
      {
        id: 'readiness.target_role_level',
        version: 1,
        label: 'Role level you\'re targeting abroad',
        type: 'select',
        options: [
          'Same level as current role',
          'Step down (junior role to break in)',
          'Step up (senior role)',
          'Open',
        ],
      },
      {
        id: 'readiness.has_dependants',
        version: 1,
        label: 'Do you have a spouse or dependent children you\'d hope to bring?',
        type: 'boolean',
        optional: true,
        hint: 'Mainly relevant for AU 482 and Canadian routes that allow dependants. UAE work visas typically don\'t cover dependants below a salary threshold.',
      },
      {
        id: 'readiness.target_year',
        version: 1,
        label: 'Target departure year',
        type: 'select',
        options: ['2026', '2027', '2028', 'Just exploring'],
      },
      {
        id: 'readiness.commitment_length',
        version: 1,
        label: 'How long can you commit?',
        type: 'select',
        options: [
          '6–12 months (short contract)',
          '1–2 years',
          '2+ years',
          'Open-ended where possible',
        ],
      },
    ],
  },
];
