import type { StepDef } from '../types';

export const IT_TECH_STEPS: StepDef[] = [
  {
    slug: 'personal',
    title: 'Personal Details',
    fields: [
      { id: 'personal.full_name', version: 1, label: 'Full name', type: 'text' },
      { id: 'personal.age', version: 1, label: 'Age', type: 'number', placeholder: '30' },
      { id: 'personal.city_province', version: 1, label: 'City / Province', type: 'text', placeholder: 'Cape Town, Western Cape' },
      {
        id: 'personal.nationality',
        version: 1,
        label: 'Nationality on your passport',
        type: 'select',
        options: ['South African', 'Dual (SA + EU/UK/other)', 'Other'],
      },
      {
        id: 'personal.whatsapp_number',
        version: 1,
        label: 'WhatsApp number',
        type: 'text',
        hint: "We'll send your feedback to this number",
        placeholder: '079 123 4567',
      },
    ],
  },
  {
    slug: 'role',
    title: 'Your IT Role',
    supportHint: 'IT support vs degree-level — why it matters',
    fields: [
      {
        id: 'role.discipline',
        version: 1,
        label: 'Primary IT discipline',
        type: 'select',
        options: [
          'Software developer / engineer',
          'Data engineer / data scientist',
          'Cloud architect / DevOps / SRE',
          'Cybersecurity specialist',
          'ML / AI engineer',
          'IT business analyst / systems designer',
          'Mobile developer',
          'Web / multimedia developer',
          'Database administrator',
          'Network engineer / sysadmin',
          'IT support / help desk (technician)',
          'QA / test engineer',
          'Product / project manager (technical)',
          'Other',
        ],
        hint: 'Most ICT roles are non-regulated in destination countries — your employer\'s sponsorship is usually the only gate. IT support roles (RQF 3–5) are an exception',
      },
      {
        id: 'role.seniority',
        version: 1,
        label: 'Seniority level',
        type: 'select',
        options: ['Junior (under 2 yrs)', 'Mid-level (2–5 yrs)', 'Senior (5–10 yrs)', 'Staff / Principal (10+ yrs)', 'Manager / Lead'],
      },
      {
        id: 'role.years_experience',
        version: 1,
        label: 'Years of IT experience (post-qualification or self-taught)',
        type: 'number',
        placeholder: '5',
        hint: 'Germany IT-specialist-without-degree route requires 3+ years of IT experience in the last 7 years',
      },
      {
        id: 'role.tech_stack',
        version: 1,
        label: 'Primary tech stack / specialism',
        type: 'text',
        optional: true,
        placeholder: 'e.g. Python / React / AWS, or .NET, or Salesforce admin',
      },
      {
        id: 'role.uk_soc_aware',
        version: 1,
        label: 'For UK applicants — your role at UK SOC code level',
        type: 'select',
        options: [
          'Degree-level (2134/2135/2136/2137/2139 — software / systems / cyber / web)',
          'IT support / help desk (3132/3133 — TSL only, expires 31 Dec 2026)',
          'Not applying to UK / not sure',
        ],
        hint: 'IT support roles are only UK-eligible via the Temporary Shortage List which expires 31 December 2026 — do not plan around it beyond that date',
      },
    ],
  },
  {
    slug: 'qualifications',
    title: 'Education',
    supportHint: 'What if I don\'t have a degree?',
    fields: [
      {
        id: 'qualifications.highest_qualification',
        version: 1,
        label: 'Highest completed qualification',
        type: 'select',
        options: [
          'BSc / BEng / BCom in CS or IT (3-year)',
          'BTech / BSc Honours / 4-year IT degree',
          'Master / PhD in computing',
          'National Diploma in IT',
          'Industry certifications only (AWS, Azure, CCNA, etc.)',
          'Matric (NSC) + self-taught',
          'Bootcamp graduate',
          'Other non-IT degree',
          'Currently studying',
        ],
        hint: 'A degree is NOT required for Germany IT-specialist or UK Skilled Worker if your role is degree-level. Canada Express Entry generally needs a degree-equivalent ECA',
      },
      {
        id: 'qualifications.institution',
        version: 1,
        label: 'Institution',
        type: 'text',
        optional: true,
        placeholder: 'e.g. University of Cape Town',
      },
      {
        id: 'qualifications.graduation_year',
        version: 1,
        label: 'Graduation year',
        type: 'number',
        optional: true,
        placeholder: '2018',
      },
      {
        id: 'qualifications.medium_of_instruction',
        version: 1,
        label: 'Was your degree taught and assessed in English?',
        type: 'select',
        options: ['Yes — and I can get a letter from the university', 'Yes — but no formal letter yet', 'No', 'Not applicable (no degree)'],
        hint: 'Medium-of-instruction letter can satisfy UK English requirement without IELTS for UKVI from 8 Jan 2026',
      },
      {
        id: 'qualifications.industry_certs',
        version: 1,
        label: 'Industry certifications you hold (select all that apply)',
        type: 'multiselect',
        options: [
          'AWS (any level)',
          'Microsoft Azure',
          'Google Cloud (GCP)',
          'Cisco (CCNA / CCNP / CCIE)',
          'CompTIA (Security+, Network+, etc.)',
          'Kubernetes / CKA / CKAD',
          'PMP / PRINCE2',
          'Scrum / SAFe',
          'CISSP / CISM / CEH',
          'Salesforce',
          'Other / none',
        ],
      },
    ],
  },
  {
    slug: 'assessment',
    title: 'Skills Assessment & Credential Recognition',
    supportHint: 'Most ICT destinations need no assessment — two exceptions',
    fields: [
      {
        id: 'assessment.acs_status',
        version: 1,
        label: 'ACS Migration Skills Assessment (Australia)',
        type: 'select',
        options: ['Suitable outcome received', 'Submitted — in progress', 'Not started', 'Not applying to Australia'],
        hint: 'ACS is MANDATORY for any Australian skilled visa — only Australia requires it. AUD$543 + 8–10 weeks',
      },
      {
        id: 'assessment.wes_status',
        version: 1,
        label: 'WES Educational Credential Assessment (Canada)',
        type: 'select',
        options: ['ECA letter received', 'Submitted — in progress', 'Not started', 'Not applying to Canada'],
        hint: 'CAD$272 + courier; SA university must send transcripts directly to WES. Required for Canada Express Entry',
      },
      {
        id: 'assessment.ecctis_status',
        version: 1,
        label: 'UK ENIC (Ecctis) equivalence — optional for UK',
        type: 'select',
        options: ['Reference letter received', 'Applied — in progress', 'Not needed (degree is clearly RQF 6+)', 'Not started', 'Not applying to UK'],
        hint: 'Optional — can support employer\'s licensed-sponsor assessment and may help avoid IELTS for UKVI',
      },
      {
        id: 'assessment.anabin_check',
        version: 1,
        label: 'Anabin / Bundesagentur recognition (Germany)',
        type: 'select',
        options: ['Confirmed on Anabin database', 'Submitted to Bundesagentur', 'Not checked yet', 'Not needed (IT-specialist-without-degree route)', 'Not applying to Germany'],
        hint: 'UCT, Wits, Stellenbosch, UP degrees are generally listed on Anabin. Individual recognition can take 3–12 months',
      },
    ],
  },
  {
    slug: 'documents',
    title: 'Documents & Finances',
    fields: [
      {
        id: 'documents.passport_status',
        version: 1,
        label: 'Passport status',
        type: 'select',
        options: ['Valid — 2+ years remaining', 'Valid — under 2 years remaining', 'Expired', 'No passport'],
      },
      {
        id: 'documents.police_clearance',
        version: 1,
        label: 'SAPS Police Clearance Certificate',
        type: 'select',
        options: ['Current (within 6 months)', 'Older than 6 months', 'Applied / in progress', 'None'],
        hint: 'Valid 6 months from issue — time to arrive near visa lodgement, not before',
      },
      {
        id: 'documents.dirco_apostille',
        version: 1,
        label: 'DIRCO apostille on PCC + degree-equivalent docs',
        type: 'select',
        options: ['Done', 'In progress', 'Not started', 'Not applicable (UK / Ecctis route only)'],
        hint: 'DIRCO service is free. Required for Hague Convention destinations; UK uses Ecctis instead',
      },
      {
        id: 'documents.cv_in_destination_format',
        version: 1,
        label: 'CV adapted for destination market',
        type: 'select',
        options: ['Yes — ATS-friendly, destination format', 'Yes — but SA format', 'No', 'Working on it'],
        hint: 'UK/Ireland/Germany/Canada CVs differ from SA format — ATS-readable plain text wins, no photo, no SA-style personal details',
      },
      {
        id: 'documents.github_portfolio',
        version: 1,
        label: 'Public GitHub or portfolio',
        type: 'select',
        options: ['Yes — active and current', 'Yes — but stale', 'Private / employer-owned only', 'No public portfolio'],
        hint: 'Most destination tech employers expect a GitHub or portfolio link — material differentiator for SA candidates',
      },
      {
        id: 'documents.dependants_count',
        version: 1,
        label: 'Number of dependants (spouse + children)',
        type: 'number',
        placeholder: '0',
      },
      {
        id: 'documents.available_capital',
        version: 1,
        label: 'Savings / available capital for relocation',
        type: 'select',
        options: ['Under R50k', 'R50k – R100k', 'R100k – R200k', 'R200k – R400k', 'R400k+', 'Prefer not to say'],
        hint: 'IT relocation typically needs R60k–R150k upfront (visa + flights + first month). Germany Opportunity Card additionally requires a blocked account of ~€13,092 (R260k)',
      },
    ],
  },
  {
    slug: 'readiness',
    title: 'English, German & Destinations',
    supportHint: 'Each country has different English requirements',
    fields: [
      {
        id: 'readiness.english_rating',
        version: 1,
        label: 'How would you rate your English?',
        type: 'select',
        options: ['Conversational', 'Fluent', 'Native / first language'],
      },
      {
        id: 'readiness.english_test',
        version: 1,
        label: 'English test taken (if any)',
        type: 'select',
        options: [
          'IELTS Academic',
          'IELTS for UKVI (UK Skilled Worker — required from 8 Jan 2026)',
          'IELTS General Training (Canada Express Entry)',
          'PTE Academic',
          'TOEFL',
          'None yet',
        ],
        hint: 'UK Skilled Worker requires CEFR B2 from 8 Jan 2026. PTE Academic is NOT accepted for Canada Express Entry — IELTS General Training only',
      },
      {
        id: 'readiness.english_score',
        version: 1,
        label: 'Test score (overall + lowest band)',
        type: 'text',
        optional: true,
        placeholder: 'e.g. IELTS 7.5 overall, 7.0 lowest',
      },
      {
        id: 'readiness.german_ability',
        version: 1,
        label: 'German language ability',
        type: 'select',
        options: ['None', 'A1 (basic) — no certificate', 'A1 certificate (Goethe / telc)', 'A2 / B1', 'B2 or higher', 'Native / near-native'],
        hint: 'Germany Opportunity Card accepts A1 German OR B2 English. Settlement permit at 21 months needs B1 German (27 months without)',
      },
      {
        id: 'readiness.target_destinations',
        version: 1,
        label: 'Target destinations (select all that apply)',
        type: 'multiselect',
        options: ['Ireland', 'United Kingdom', 'Germany', 'Netherlands', 'Canada', 'Australia', 'Open to recommendations'],
        hint: 'Ireland and UK are the lowest-friction English-language starts. Germany Opportunity Card lets you arrive without a job offer',
      },
      {
        id: 'readiness.priority',
        version: 1,
        label: 'What matters most to you?',
        type: 'select',
        options: [
          'Fastest start (job offer in hand soon)',
          'Highest salary',
          'Fastest path to permanent residence',
          'Largest SA / tech diaspora',
          'EU access / mobility',
          'Family-friendly destination',
          'Tax efficiency',
        ],
      },
      {
        id: 'readiness.remote_offer',
        version: 1,
        label: 'Do you have a remote offer or active interviews?',
        type: 'select',
        options: ['Active interviews with destination employers', 'Remote-first offer from destination employer', 'Currently remote for SA employer only', 'Not yet — just exploring'],
      },
      {
        id: 'readiness.notice_period',
        version: 1,
        label: 'Notice period at current job',
        type: 'select',
        options: ['Immediate', '1 month', '2 months', '3 months', 'Other / not employed'],
      },
      {
        id: 'readiness.target_timeline',
        version: 1,
        label: 'Target timeline',
        type: 'select',
        options: ['As soon as possible', 'Within 6 months', 'Within 1 year', 'Within 2 years', 'Just exploring'],
      },
    ],
  },
];
