import type { StepDef } from '../types';

export const SEASONAL_STEPS: StepDef[] = [
  {
    slug: 'personal',
    title: 'Personal Details',
    fields: [
      { id: 'personal.full_name', version: 1, label: 'Full name', type: 'text' },
      { id: 'personal.age', version: 1, label: 'Age', type: 'number', placeholder: '23', hint: 'Most seasonal programmes have age caps (J-1 SWT 18–28, Canada IEC 18–35)' },
      { id: 'personal.city_province', version: 1, label: 'City / Province', type: 'text', placeholder: 'Cape Town, Western Cape' },
      {
        id: 'personal.whatsapp_number',
        version: 1,
        label: 'WhatsApp number',
        type: 'text',
        hint: "We'll send your feedback to this number",
        placeholder: '079 123 4567',
      },
    ],
  },
  {
    slug: 'education',
    title: 'Student Status',
    supportHint: 'Not sure if you qualify as a full-time student?',
    fields: [
      {
        id: 'education.student_status',
        version: 1,
        label: 'Current student status',
        type: 'select',
        options: ['Currently enrolled full-time', 'Recently graduated (within 12 months)', 'Graduated more than 12 months ago', 'Not a student'],
        hint: 'J-1 SWT requires full-time enrolment at a post-secondary institution at the time of application',
      },
      {
        id: 'education.institution',
        version: 1,
        label: 'University / college',
        type: 'text',
        optional: true,
        placeholder: 'e.g. University of Cape Town',
        showIf: { field: 'education.student_status', value: 'Currently enrolled full-time' },
      },
      {
        id: 'education.qualification_level',
        version: 1,
        label: 'Qualification level',
        type: 'select',
        options: ['Diploma / Certificate', 'Undergraduate degree', 'Honours', 'Masters / Postgraduate', 'Other'],
        optional: true,
      },
      {
        id: 'education.expected_graduation',
        version: 1,
        label: 'Expected graduation year',
        type: 'select',
        options: ['2026', '2027', '2028', '2029+', 'Already graduated', 'Not applicable'],
      },
    ],
  },
  {
    slug: 'programme',
    title: 'Programme Interest',
    fields: [
      {
        id: 'programme.primary_interest',
        version: 1,
        label: 'Which programme interests you most?',
        type: 'select',
        options: ['J-1 Summer Work Travel (US)', 'Canada IEC Working Holiday', 'H-2B (US, employer-petitioned)', 'UK seasonal work', 'Open / not sure', 'Other'],
      },
      {
        id: 'programme.has_sponsor_contact',
        version: 1,
        label: 'Are you already in contact with a sponsor or recruiter?',
        type: 'boolean',
      },
      {
        id: 'programme.sponsor_name',
        version: 1,
        label: 'Sponsor / recruiter name',
        type: 'text',
        optional: true,
        placeholder: 'e.g. CCUSA, SWAP, CIEE',
        hint: "We'll cross-check against the official designated-sponsor list",
        showIf: { field: 'programme.has_sponsor_contact', value: true },
      },
      {
        id: 'programme.previously_applied',
        version: 1,
        label: 'Have you applied for a J-1, IEC, or similar programme before?',
        type: 'select',
        options: ['No', 'Yes — completed', 'Yes — in progress', 'Yes — was refused'],
      },
    ],
  },
  {
    slug: 'experience',
    title: 'Work Experience',
    fields: [
      {
        id: 'experience.years_relevant',
        version: 1,
        label: 'Years of customer-facing / hospitality / retail experience',
        type: 'number',
        placeholder: '2',
        hint: 'Babysitting, lifeguarding, retail, food service, summer jobs all count',
      },
      {
        id: 'experience.sector',
        version: 1,
        label: 'Sectors worked in (select all)',
        type: 'multiselect',
        options: ['Hospitality / restaurants', 'Retail', 'Theme park / resort', 'Lifeguarding / camp', 'Customer service / call centre', 'Agriculture / farming', 'None yet', 'Other'],
      },
      {
        id: 'experience.drivers_license',
        version: 1,
        label: 'Driver\'s licence',
        type: 'select',
        options: ['Full SA licence (Code 8/EB)', 'Learner\'s licence', 'International driving permit', 'None'],
      },
    ],
  },
  {
    slug: 'documents',
    title: 'Documents & Finances',
    fields: [
      {
        id: 'documents.passport_status',
        version: 1,
        label: 'Passport status',
        type: 'select',
        options: ['Valid — 18+ months remaining', 'Valid — under 18 months remaining', 'Expired', 'No passport'],
      },
      {
        id: 'documents.police_clearance',
        version: 1,
        label: 'SA Police Clearance Certificate (SAPS)',
        type: 'select',
        options: ['Current (within 6 months)', 'Older than 6 months', 'Applied — waiting', 'None'],
      },
      {
        id: 'documents.available_capital',
        version: 1,
        label: 'Savings available for sponsor fees + flights + first weeks abroad',
        type: 'select',
        options: ['Under R20k', 'R20k – R40k', 'R40k – R70k', 'R70k+', 'Prefer not to say'],
        hint: 'J-1 SWT total to first paycheck typically ~R45k–R65k all-in',
      },
      {
        id: 'documents.funding_source',
        version: 1,
        label: 'Primary funding source',
        type: 'select',
        options: ['Own savings', 'Family contribution', 'Loan', 'Combination', 'Need to find funding'],
      },
    ],
  },
  {
    slug: 'readiness',
    title: 'Readiness & Timing',
    fields: [
      {
        id: 'readiness.english_rating',
        version: 1,
        label: 'How would you rate your English?',
        type: 'select',
        options: ['Basic', 'Conversational', 'Fluent', 'Native / first language'],
      },
      {
        id: 'readiness.target_season',
        version: 1,
        label: 'Target programme cycle',
        type: 'select',
        options: ['Northern summer (J-1 SWT, May–Sep)', 'Southern summer / SA window (Dec–Mar)', 'Year-round (Canada IEC)', 'Open'],
      },
      {
        id: 'readiness.target_year',
        version: 1,
        label: 'Target departure year',
        type: 'select',
        options: ['2026', '2027', '2028', 'Just exploring'],
      },
      {
        id: 'readiness.commitment_length',
        version: 1,
        label: 'How long can you commit?',
        type: 'select',
        options: ['Up to 4 months (typical SWT)', '4–12 months', '12–24 months (Canada IEC)', 'Open'],
      },
    ],
  },
];
