import type { StepDef } from '../types';

export const TEACHING_STEPS: StepDef[] = [
  {
    slug: 'personal',
    title: 'Personal Details',
    fields: [
      { id: 'personal.full_name', version: 1, label: 'Full name', type: 'text' },
      { id: 'personal.age', version: 1, label: 'Age', type: 'number', placeholder: '32' },
      { id: 'personal.city_province', version: 1, label: 'City / Province', type: 'text', placeholder: 'Cape Town, Western Cape' },
      {
        id: 'personal.whatsapp_number',
        version: 1,
        label: 'WhatsApp number',
        type: 'text',
        hint: "We'll send your feedback to this number",
        placeholder: '079 123 4567',
      },
    ],
  },
  {
    slug: 'situation',
    title: 'Your situation',
    fields: [
      {
        id: 'situation.family_status',
        version: 1,
        label: 'Family status',
        type: 'select',
        options: [
          'Single, no dependants',
          'Married / partnered, no children',
          'Married / partnered with children',
          'Single parent with children',
          'Supporting elderly parents in SA',
        ],
      },
      {
        id: 'situation.current_employment',
        version: 1,
        label: 'Current employment status',
        type: 'select',
        options: [
          'Employed full-time in my field',
          'Employed in a different field',
          'Self-employed / contracting',
          'Studying / recently qualified',
          'Unemployed',
        ],
      },
    ],
  },
  {
    slug: 'qualifications',
    title: 'Qualifications',
    fields: [
      {
        id: 'qualifications.highest_qualification',
        version: 1,
        label: 'Highest teaching qualification',
        type: 'select',
        options: ['PGCE', 'B.Ed', 'B.Ed Honours', 'M.Ed / Masters', 'PhD', 'Other'],
      },
      { id: 'qualifications.institution', version: 1, label: 'Institution', type: 'text' },
      { id: 'qualifications.graduation_year', version: 1, label: 'Graduation year', type: 'number', placeholder: '2018' },
      {
        id: 'qualifications.phase',
        version: 1,
        label: 'Phase qualified to teach (select all that apply)',
        type: 'multiselect',
        options: ['Foundation (Gr R–3)', 'Intermediate (Gr 4–6)', 'Senior (Gr 7–9)', 'FET (Gr 10–12)', 'Early Childhood', 'Adult / Tertiary'],
      },
      {
        id: 'qualifications.subjects',
        version: 1,
        label: 'Subject specialisms (select all that apply)',
        type: 'multiselect',
        options: ['English', 'Maths', 'Sciences', 'Languages', 'Humanities / Social Sciences', 'Tech / Computing', 'Arts / Music', 'Phys Ed', 'Special Needs', 'Other'],
      },
    ],
  },
  {
    slug: 'registration',
    title: 'SACE Registration',
    supportHint: 'Not sure about your SACE details?',
    fields: [
      { id: 'registration.sace_number', version: 1, label: 'SACE registration number', type: 'text' },
      {
        id: 'registration.sace_status',
        version: 1,
        label: 'Registration status',
        type: 'select',
        options: ['Active (full)', 'Provisional', 'Lapsed', 'Pending renewal', 'Not registered'],
      },
      {
        id: 'registration.sace_expiry',
        version: 1,
        label: 'Registration expiry year',
        type: 'select',
        options: ['2025', '2026', '2027', '2028+', "I don't know"],
        hint: 'Approximate year is fine',
      },
      {
        id: 'registration.qts_started',
        version: 1,
        label: 'Have you started UK QTS / iQTS or any overseas teacher registration?',
        type: 'select',
        options: ['None started', 'In progress', 'Completed'],
      },
    ],
  },
  {
    slug: 'experience',
    title: 'Teaching Experience',
    fields: [
      { id: 'experience.years_teaching', version: 1, label: 'Years of teaching experience', type: 'number', placeholder: '5' },
      {
        id: 'experience.school_type',
        version: 1,
        label: 'Current / most recent school type',
        type: 'select',
        options: ['Public (state)', 'Private / independent', 'Model C', 'International school', 'Tutoring / online', 'Not currently teaching', 'Other'],
      },
      {
        id: 'experience.taught_abroad',
        version: 1,
        label: 'Have you taught abroad before?',
        type: 'boolean',
      },
      {
        id: 'experience.taught_abroad_where',
        version: 1,
        label: 'Where did you teach?',
        type: 'text',
        optional: true,
        showIf: { field: 'experience.taught_abroad', value: true },
      },
      {
        id: 'experience.notice_period',
        version: 1,
        label: 'Notice period at current school',
        type: 'select',
        options: ['Immediate', 'End of current term', '1 calendar month', '3 months / end of semester', 'Other / not employed'],
      },
    ],
  },
  {
    slug: 'documents',
    title: 'Documents & Finances',
    fields: [
      {
        id: 'documents.passport_status',
        version: 1,
        label: 'Passport status',
        type: 'select',
        options: ['Valid, 2+ years remaining', 'Valid, under 2 years remaining', 'Expired', 'No passport'],
      },
      {
        id: 'documents.police_clearance',
        version: 1,
        label: 'Police clearance certificate',
        type: 'select',
        options: ['Current (within 6 months)', 'Older than 6 months', 'None'],
      },
      {
        id: 'documents.dependants_count',
        version: 1,
        label: 'Number of dependants (spouse + children)',
        type: 'number',
        placeholder: '0',
        hint: 'Enter 0 if none',
      },
      {
        id: 'documents.available_capital',
        version: 1,
        label: 'Savings / available capital for relocation',
        type: 'select',
        options: ['Under R30k', 'R30k – R70k', 'R70k – R150k', 'R150k+', 'Prefer not to say'],
        hint: 'This helps us identify realistic destinations for you',
      },
    ],
  },
  {
    slug: 'readiness',
    title: 'Language & Readiness',
    supportHint: 'Not sure which English test applies?',
    fields: [
      {
        id: 'readiness.english_rating',
        version: 1,
        label: 'How would you rate your English?',
        type: 'select',
        options: ['Basic', 'Conversational', 'Fluent', 'Native / first language'],
      },
      {
        id: 'readiness.english_test',
        version: 1,
        label: 'Have you taken an English test?',
        type: 'select',
        options: ['Not yet', 'IELTS', 'TOEFL', 'Other / exempt'],
      },
      {
        id: 'readiness.english_test_score',
        version: 1,
        label: 'Score / grade',
        type: 'text',
        optional: true,
        placeholder: 'e.g. IELTS 7.0',
        showIf: { field: 'readiness.english_test', value: 'IELTS' },
      },
      {
        id: 'readiness.toefl_score',
        version: 1,
        label: 'TOEFL score',
        type: 'text',
        optional: true,
        placeholder: 'e.g. 100 iBT',
        showIf: { field: 'readiness.english_test', value: 'TOEFL' },
      },
      {
        id: 'readiness.target_destinations',
        version: 1,
        label: 'Target destinations (select all that apply)',
        type: 'multiselect',
        options: ['UAE', 'Saudi Arabia', 'China', 'UK', 'Vietnam', 'Thailand', 'Qatar / Oman / Kuwait', 'Australia / NZ', 'Other'],
      },
      {
        id: 'readiness.target_timeline',
        version: 1,
        label: 'Target timeline',
        type: 'select',
        options: ['As soon as possible', 'Within 6 months', 'Within 1 year', 'Just exploring'],
      },
    ],
  },
];
