import type { StepDef } from '../types';

export const TEFL_STEPS: StepDef[] = [
  {
    slug: 'personal',
    title: 'Personal Details',
    fields: [
      { id: 'personal.full_name', version: 1, label: 'Full name', type: 'text' },
      { id: 'personal.age', version: 1, label: 'Age', type: 'number', placeholder: '28' },
      { id: 'personal.city_province', version: 1, label: 'City / Province', type: 'text', placeholder: 'Cape Town, Western Cape' },
      {
        id: 'personal.nationality',
        version: 1,
        label: 'Nationality on your passport',
        type: 'select',
        options: ['South African', 'Dual (SA + other)', 'Other'],
        hint: 'Korea EPIK and most Gulf programmes require a passport from one of seven recognised English-speaking countries — SA qualifies',
      },
      {
        id: 'personal.whatsapp_number',
        version: 1,
        label: 'WhatsApp number',
        type: 'text',
        hint: "We'll send your feedback to this number",
        placeholder: '079 123 4567',
      },
    ],
  },
  {
    slug: 'qualifications',
    title: 'Degree',
    supportHint: 'Why we ask about your degree',
    fields: [
      {
        id: 'qualifications.degree_status',
        version: 1,
        label: 'Highest completed qualification',
        type: 'select',
        options: ['Bachelor (any field)', 'Honours / Postgrad Diploma', 'Master / PhD', 'Diploma (3-year)', 'Matric only', 'Currently studying'],
        hint: 'Most TEFL visa routes (Korea E-2, China Z, Saudi/UAE) require a completed bachelor degree in any field',
      },
      { id: 'qualifications.degree_field', version: 1, label: 'Field of study', type: 'text', optional: true, placeholder: 'e.g. BCom, BA English, BSc' },
      { id: 'qualifications.institution', version: 1, label: 'Institution', type: 'text', optional: true },
      { id: 'qualifications.graduation_year', version: 1, label: 'Graduation year', type: 'number', optional: true, placeholder: '2018' },
      {
        id: 'qualifications.saqa_letter',
        version: 1,
        label: 'SAQA Individual Verification Letter',
        type: 'select',
        options: ['Already obtained', 'Applied / in progress', 'Not started', "I don't know what this is"],
        hint: 'Required by some destinations to verify your SA degree before apostille',
      },
    ],
  },
  {
    slug: 'credential',
    title: 'TEFL Credential',
    supportHint: 'Not sure which certificate you have?',
    fields: [
      {
        id: 'credential.tefl_cert_type',
        version: 1,
        label: 'TEFL / TESOL certificate',
        type: 'select',
        options: ['CELTA (Cambridge)', 'Trinity CertTESOL', 'Ofqual-regulated Level 5 Diploma', 'Online TEFL (120hr+)', 'Online TEFL (under 120hr)', 'None yet — planning to get one', 'None — not planning'],
        hint: 'Korea, Gulf, and reputable Vietnamese employers prefer CELTA / Trinity / Ofqual-regulated credentials',
      },
      { id: 'credential.cert_provider', version: 1, label: 'Certificate provider / awarding body', type: 'text', optional: true, placeholder: 'e.g. International House Johannesburg' },
      { id: 'credential.cert_year', version: 1, label: 'Year obtained', type: 'number', optional: true, placeholder: '2024' },
      {
        id: 'credential.specialism',
        version: 1,
        label: 'Specialism / additional training (select all that apply)',
        type: 'multiselect',
        options: ['Young Learners (YL)', 'Business English', 'IELTS / exam prep', 'Online teaching', 'One-to-one tutoring', 'None'],
      },
    ],
  },
  {
    slug: 'experience',
    title: 'Teaching Experience',
    fields: [
      {
        id: 'experience.years_teaching',
        version: 1,
        label: 'Years of teaching experience',
        type: 'select',
        options: ['None', 'Under 1 year', '1–2 years', '3–5 years', '5+ years'],
      },
      {
        id: 'experience.context',
        version: 1,
        label: 'Where you have taught (select all that apply)',
        type: 'multiselect',
        options: ['Language centre / academy', 'Public school', 'Private / international school', 'University', 'Online (1-on-1)', 'Online (group)', 'Tutoring / freelance', 'None'],
      },
      {
        id: 'experience.taught_abroad',
        version: 1,
        label: 'Have you taught abroad before?',
        type: 'boolean',
      },
      {
        id: 'experience.taught_abroad_where',
        version: 1,
        label: 'Where did you teach?',
        type: 'text',
        optional: true,
        showIf: { field: 'experience.taught_abroad', value: true },
      },
      {
        id: 'experience.notice_period',
        version: 1,
        label: 'Earliest you could relocate',
        type: 'select',
        options: ['Immediately', 'Within 1 month', 'Within 3 months', '6+ months', 'Just researching'],
      },
    ],
  },
  {
    slug: 'documents',
    title: 'Documents & Finances',
    fields: [
      {
        id: 'documents.passport_status',
        version: 1,
        label: 'Passport status',
        type: 'select',
        options: ['Valid — 2+ years remaining', 'Valid — under 2 years remaining', 'Expired', 'No passport'],
      },
      {
        id: 'documents.police_clearance',
        version: 1,
        label: 'SAPS Police Clearance Certificate',
        type: 'select',
        options: ['Current (within 6 months)', 'Older than 6 months', 'None'],
        hint: 'Required for every TEFL visa; valid 6 months from issue',
      },
      {
        id: 'documents.degree_legalisation',
        version: 1,
        label: 'Degree legalisation via DIRCO (apostille or authentication)',
        type: 'select',
        options: ['Done', 'In progress', 'Not started', 'Not applicable'],
        hint: 'DIRCO Legalisation Services issues either an apostille (Hague-Convention destinations: Korea, Saudi, China, UAE) or authentication (Vietnam pre-Sep 2026). The service is free; private agents only courier documents for a fee',
      },
      {
        id: 'documents.dependants_count',
        version: 1,
        label: 'Number of dependants (spouse + children)',
        type: 'number',
        placeholder: '0',
        hint: 'Enter 0 if none',
      },
      {
        id: 'documents.available_capital',
        version: 1,
        label: 'Savings / available capital for relocation',
        type: 'select',
        options: ['Under R30k', 'R30k – R70k', 'R70k – R150k', 'R150k+', 'Prefer not to say'],
        hint: 'TEFL relocation typically needs R40k–R80k upfront before first salary',
      },
    ],
  },
  {
    slug: 'readiness',
    title: 'Destinations & Timeline',
    fields: [
      {
        id: 'readiness.english_rating',
        version: 1,
        label: 'How would you rate your English?',
        type: 'select',
        options: ['Conversational', 'Fluent', 'Native / first language'],
      },
      {
        id: 'readiness.target_destinations',
        version: 1,
        label: 'Target destinations (select all that apply)',
        type: 'multiselect',
        options: ['South Korea (EPIK / hagwon)', 'China', 'Vietnam', 'Japan (JET / Eikaiwa)', 'Saudi Arabia', 'UAE', 'Thailand', 'Hong Kong', 'Other Asia', 'Open to recommendations'],
      },
      {
        id: 'readiness.priority',
        version: 1,
        label: 'What matters most to you?',
        type: 'select',
        options: ['Highest savings', 'Lifestyle / culture', 'Structured government programme (EPIK / JET)', 'Career stepping stone', 'Family-friendly destination'],
      },
      {
        id: 'readiness.target_timeline',
        version: 1,
        label: 'Target timeline',
        type: 'select',
        options: ['As soon as possible', 'Within 6 months', 'Within 1 year', 'Just exploring'],
      },
    ],
  },
];
