import type { StepDef } from '../types';

export const TRADES_STEPS: StepDef[] = [
  {
    slug: 'personal',
    title: 'Personal Details',
    fields: [
      { id: 'personal.full_name', version: 1, label: 'Full name', type: 'text' },
      { id: 'personal.age', version: 1, label: 'Age', type: 'number', placeholder: '32' },
      { id: 'personal.city_province', version: 1, label: 'City / Province', type: 'text', placeholder: 'Cape Town, Western Cape' },
      {
        id: 'personal.whatsapp_number',
        version: 1,
        label: 'WhatsApp number',
        type: 'text',
        hint: "We'll send your feedback to this number",
        placeholder: '079 123 4567',
      },
    ],
  },
  {
    slug: 'trade',
    title: 'Your Trade',
    supportHint: 'What if my trade is not listed?',
    fields: [
      {
        id: 'trade.occupation',
        version: 1,
        label: 'Primary trade',
        type: 'select',
        options: [
          'Electrician',
          'Plumber',
          'Welder',
          'Boilermaker',
          'Fitter & Turner',
          'Diesel Mechanic',
          'Motor Mechanic',
          'Auto Electrician',
          'Millwright',
          'Refrigeration / HVAC',
          'Carpenter / Joiner',
          'Bricklayer',
          'Painter',
          'Rigger',
          'Other',
        ],
      },
      {
        id: 'trade.red_seal_status',
        version: 1,
        label: 'QCTO Trade Test Certificate (Red Seal)',
        type: 'select',
        options: ['Passed — certificate in hand', 'Passed — certificate lost', 'Booked / writing soon', 'Not yet — apprentice', 'No formal trade test'],
        hint: 'Every destination requires the Red Seal. Pre-2013 certificates go through your old SETA, not QCTO',
      },
      {
        id: 'trade.red_seal_year',
        version: 1,
        label: 'Year you passed your trade test',
        type: 'number',
        optional: true,
        placeholder: '2018',
      },
      {
        id: 'trade.section_13_logbook',
        version: 1,
        label: 'Section 13 contract + artisan logbook',
        type: 'select',
        options: ['Both on hand', 'One missing — need to reconstruct', 'Both missing', 'Not applicable (6-yr on-the-job route)'],
        hint: 'TRA Australia accepts either 4 yrs formal training OR 6 yrs documented on-the-job experience',
      },
      {
        id: 'trade.training_route',
        version: 1,
        label: 'How you qualified',
        type: 'select',
        options: ['Section 13 apprenticeship (SETA)', 'TVET / N-course route', 'On-the-job (6+ years)', 'Olifantsfontein trade test', 'Other'],
      },
    ],
  },
  {
    slug: 'experience',
    title: 'Work Experience',
    supportHint: 'Why we ask about IRP5 / formal records',
    fields: [
      {
        id: 'experience.years_post_qualification',
        version: 1,
        label: 'Years of paid work experience after qualifying',
        type: 'number',
        placeholder: '5',
        hint: 'TRA requires 12 months full-time paid in your nominated trade within the last 3 years',
      },
      {
        id: 'experience.recent_12_months',
        version: 1,
        label: 'Worked at least 12 full months in your trade in the last 3 years?',
        type: 'select',
        options: ['Yes — same trade', 'Yes — but different/related trade', 'No — gap of 1+ year', 'No — recently qualified'],
      },
      {
        id: 'experience.employment_type',
        version: 1,
        label: 'Most of your work experience was…',
        type: 'select',
        options: ['PAYE / IRP5 documented', 'Self-employed (with SARS records)', 'Mix of PAYE and cash', 'Mostly cash-in-hand / family business', 'Other'],
        hint: 'Cash-in-hand work without IRP5s/tax records is excluded from TRA and Canadian assessments',
      },
      {
        id: 'experience.employer_references',
        version: 1,
        label: 'Employer reference letters you can produce',
        type: 'select',
        options: ['All employers contactable + letterhead refs available', 'Some employers contactable', 'Old employers closed / unreachable', 'None'],
        hint: 'Required by TRA OSAP and every Canadian provincial TEA — letters must be on company letterhead with named signatory',
      },
      {
        id: 'experience.notice_period',
        version: 1,
        label: 'Notice period at current job',
        type: 'select',
        options: ['Immediate', '1 month', '2 months', '3 months', 'Other / not employed'],
      },
    ],
  },
  {
    slug: 'qualifications',
    title: 'Verification & N-Level Documents',
    supportHint: 'Which body verifies which document?',
    fields: [
      {
        id: 'qualifications.n_level',
        version: 1,
        label: 'N-level certificates you hold',
        type: 'multiselect',
        options: ['N1', 'N2', 'N3 (Matric equivalent)', 'N4', 'N5', 'N6', 'N-Diploma', 'None'],
      },
      {
        id: 'qualifications.umalusi_verified',
        version: 1,
        label: 'Umalusi verification (Matric / N1–N3)',
        type: 'select',
        options: ['Done', 'In progress', 'Not started', 'Not applicable'],
      },
      {
        id: 'qualifications.dhet_verified',
        version: 1,
        label: 'DHET verification (N4–N6 / N-Diploma)',
        type: 'select',
        options: ['Done', 'In progress', 'Not started', 'Not applicable'],
      },
      {
        id: 'qualifications.qcto_verified',
        version: 1,
        label: 'QCTO / SETA verification of trade test certificate',
        type: 'select',
        options: ['Done', 'In progress', 'Not started', 'Pre-2013 — needs old SETA, not QCTO'],
        hint: 'QCTO verifies certificates issued from 1 Nov 2013 onwards. Earlier certificates go to the original Training Board or SETA',
      },
    ],
  },
  {
    slug: 'assessment',
    title: 'Destination Skills Assessment',
    supportHint: 'A SAQA letter does not replace a skills assessment',
    fields: [
      {
        id: 'assessment.tra_osap_status',
        version: 1,
        label: 'TRA Offshore Skills Assessment Program (Australia)',
        type: 'select',
        options: ['Outcome received', 'Submitted — in progress', 'Not started', 'Not applying to Australia'],
        hint: 'TRA OSAP takes ~15 weeks; mandatory before any AU skilled visa lodgement',
      },
      {
        id: 'assessment.canadian_tea_status',
        version: 1,
        label: 'Canadian provincial Trade Equivalency Assessment (Alberta/BC/Ontario/SK)',
        type: 'select',
        options: ['Approved by a province', 'Submitted — in progress', 'Not started', 'Not applying to Canada'],
        hint: 'Each province has its own TEA — 3–12 months. SA Red Seal does NOT auto-transfer; provincial re-certification is required',
      },
      {
        id: 'assessment.nz_iqa_status',
        version: 1,
        label: 'NZ qualification / Engineering NZ check',
        type: 'select',
        options: ['Completed', 'Submitted — in progress', 'Not started', 'Not applying to NZ'],
      },
    ],
  },
  {
    slug: 'documents',
    title: 'Documents & Finances',
    fields: [
      {
        id: 'documents.passport_status',
        version: 1,
        label: 'Passport status',
        type: 'select',
        options: ['Valid — 2+ years remaining', 'Valid — under 2 years remaining', 'Expired', 'No passport'],
      },
      {
        id: 'documents.unabridged_birth_cert',
        version: 1,
        label: 'Unabridged birth certificate',
        type: 'select',
        options: ['On hand', 'Applied / waiting', 'Not started'],
        hint: 'DHA backlog is 12+ months — apply the day you begin planning, before anything else',
      },
      {
        id: 'documents.police_clearance',
        version: 1,
        label: 'SAPS Police Clearance Certificate',
        type: 'select',
        options: ['Current (within 6 months)', 'Older than 6 months', 'Applied / in progress', 'None'],
        hint: 'Valid 6 months from issue — time it to arrive near visa lodgement, not before',
      },
      {
        id: 'documents.dirco_apostille',
        version: 1,
        label: 'DIRCO apostille on trade docs + PCC',
        type: 'select',
        options: ['Done', 'In progress', 'Not started', "I don't know what this is"],
        hint: 'Free service. Cannot apostille unverified docs — QCTO/Umalusi/DHET verification must come first',
      },
      {
        id: 'documents.dependants_count',
        version: 1,
        label: 'Number of dependants (spouse + children)',
        type: 'number',
        placeholder: '0',
      },
      {
        id: 'documents.available_capital',
        version: 1,
        label: 'Savings / available capital for relocation',
        type: 'select',
        options: ['Under R50k', 'R50k – R100k', 'R100k – R200k', 'R200k – R400k', 'R400k+', 'Prefer not to say'],
        hint: 'Trades relocation typically needs R60k–R150k upfront (verification + assessment + visa + flights + first weeks)',
      },
    ],
  },
  {
    slug: 'readiness',
    title: 'English, Destinations & Timeline',
    supportHint: 'Each country accepts a different English test',
    fields: [
      {
        id: 'readiness.english_rating',
        version: 1,
        label: 'How would you rate your English?',
        type: 'select',
        options: ['Basic', 'Conversational', 'Fluent', 'Native / first language'],
      },
      {
        id: 'readiness.english_test',
        version: 1,
        label: 'English test taken (if any)',
        type: 'select',
        options: [
          'IELTS Academic',
          'IELTS for UKVI (UK Skilled Worker)',
          'IELTS General Training (Canada / NZ)',
          'PTE Academic',
          'None yet',
        ],
        hint: 'UK Skilled Worker requires IELTS for UKVI specifically — standard IELTS Academic is not accepted',
      },
      {
        id: 'readiness.english_score',
        version: 1,
        label: 'Test score (overall + lowest band)',
        type: 'text',
        optional: true,
        placeholder: 'e.g. IELTS 6.5 overall, 6.0 lowest',
      },
      {
        id: 'readiness.target_destinations',
        version: 1,
        label: 'Target destinations (select all)',
        type: 'multiselect',
        options: ['Australia', 'New Zealand', 'United Kingdom', 'Canada', 'UAE (cash-flow stepping stone)', 'Open to recommendations'],
      },
      {
        id: 'readiness.uk_before_2026',
        version: 1,
        label: 'Could you relocate to the UK before 31 December 2026?',
        type: 'select',
        options: ['Yes — solo, no dependants', 'Yes — with dependants', 'Maybe', 'No', 'Not interested in UK'],
        hint: 'The UK Temporary Shortage List route for trades closes 31 December 2026 — the only realistic UK window for most artisans',
      },
      {
        id: 'readiness.priority',
        version: 1,
        label: 'What matters most to you?',
        type: 'select',
        options: [
          'Highest salary',
          'Fastest path to permanent residence',
          'Largest SA diaspora / easiest landing',
          'Tax-free savings (UAE)',
          'Family-friendly destination',
        ],
      },
      {
        id: 'readiness.target_timeline',
        version: 1,
        label: 'Target timeline',
        type: 'select',
        options: ['As soon as possible', 'Within 6 months', 'Within 1 year', 'Within 2 years', 'Just exploring'],
      },
    ],
  },
];
