// AUTO-GENERATED from wiki-builds vaults via /tmp/extract_contacts.py — do not edit by hand.
// Re-run the extractor when the wiki vaults change.

export type Recruiter = {
  name: string;
  categories: string[];
  type: string;
  destinations: string[];
  website: string;
  email: string;
  phone: string;
  evidence: 'confirmed' | 'high' | 'alleged' | '';
  notes: string;
};

export type ScamPattern = {
  name: string;
  category: string;
  vault: string;
  destinations: string[];
  channels: string[];
  typicalFeeZar: string;
  reportSa: string;
  reportDestination: string;
  evidence: string;
  summary: string;
};

export const recruiters: Recruiter[] = [
  {
    name: "AHP International Nursing / ALOR Group",
    categories: ["Healthcare"],
    type: "Nursing recruiter",
    destinations: ["Australia"],
    website: "https://alorgroup.com.au/",
    email: "",
    phone: "",
    evidence: "alleged" as Recruiter['evidence'],
    notes: "AHP International Nursing had SA-specific Australia recruitment page — website now redirects to ALOR Group (rebrand uncertain); verify with ALOR directly before recommending",
  },
  {
    name: "Apostil.co.za",
    categories: ["Trades"],
    type: "Document concierge",
    destinations: ["Australia", "United Kingdom", "Canada", "New Zealand", "UAE"],
    website: "https://apostil.co.za/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Apostil.co.za (also operating as apostille.co.za) is a South African document concierge firm specialising in apostilles, notarisations, authentications, and document certifications for use abroad. It is confirmed as a DIRCO-registered agent — agents submit to DIRCO on Wednesdays only, with a 1–2 week turnaround compared to the public's 3–4 week courier wait.",
  },
  {
    name: "Breytenbachs / BIC",
    categories: ["Migration consultants"],
    type: "Immigration consultant",
    destinations: ["United Kingdom", "South Africa", "Ireland"],
    website: "https://www.bic-immigration.com/contact/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Breytenbachs Immigration Consultants Ltd (trading as BIC) is a multi-jurisdiction immigration consultancy with deep roots in the South African market, operating from offices in London, Pretoria, Durban, and Cape Town. The firm specialises in UK immigration law and visa applications as its primary service, with secondary expertise in South African and Irish immigration.",
  },
  {
    name: "CSCS",
    categories: ["Trades"],
    type: "Competence card issuer",
    destinations: ["United Kingdom"],
    website: "https://www.cscs.uk.com/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "The Construction Skills Certification Scheme (CSCS) is the UK's primary competence card scheme for construction site workers, administered via the CITB (Construction Industry Training Board). A CSCS card proves that an individual working on a UK construction site holds appropriate training and qualifications for their role.",
  },
  {
    name: "ECS Card",
    categories: ["Trades"],
    type: "Competence card issuer",
    destinations: ["United Kingdom"],
    website: "https://www.ecscard.org.uk/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "The Electrotechnical Certification Scheme (ECS) is the UK's industry competence card scheme specifically for electricians and electrotechnical workers, administered by the Joint Industry Board (JIB) for England, Wales, and Northern Ireland, and by the Scottish JIB (SJIB) for Scotland.",
  },
  {
    name: "Engage Education",
    categories: ["Teaching"],
    type: "Teaching recruiter",
    destinations: ["United Kingdom"],
    website: "https://engage-education.com/za/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "UK teacher recruiter since 2008 with SA-specific portal; employer-pays model; mixed TrustPilot (326 reviews) — payment delay complaints noted",
  },
  {
    name: "Eteach",
    categories: ["Teaching"],
    type: "Support organisation",
    destinations: ["United Kingdom", "International"],
    website: "https://www.eteach.com/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "UK teacher job board (20+ years); 2 million candidate database; free to search; employer-pays model; covers UK state and international schools",
  },
  {
    name: "Four Corners Emigration / Four Corners Migration",
    categories: ["Migration consultants"],
    type: "Immigration consultant",
    destinations: ["Australia", "New Zealand (Unconfirmed)"],
    website: "https://four-corners.com.au/za-migrate-to-australia/",
    email: "info@four-corners.co.za",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Four Corners Emigration (also operating as Four Corners Migration) is one of South Africa's best-established Australia and New Zealand immigration specialists, founded in 1996 and claiming 61,000+ individuals, small businesses, and multinationals assisted.",
  },
  {
    name: "Gesundheit Personal Netz",
    categories: ["Migration consultants"],
    type: "Healthcare recruiter",
    destinations: ["Germany"],
    website: "https://global.gesundheit-pn.de/southernafrica/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Gesundheit Personal Netz (Health Personnel Network) is a Berlin-based healthcare recruitment organisation that specifically recruits nurses from South Africa and Namibia for placement in German hospitals and care facilities.",
  },
  {
    name: "Global Nurse Force",
    categories: ["Healthcare", "Migration consultants"],
    type: "Nursing recruiter",
    destinations: ["United Kingdom", "United States", "Ireland", "Germany", "UAE", "Saudi Arabia", "Qatar", "Australia"],
    website: "https://www.globalnurseforce.com/contact-us",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "US-based international nursing recruiter (20+ yrs, 20,000+ placements) — zero-cost to nurses; places SA nurses in UK, USA, Ireland, Germany, GCC, Australia; no confirmed SA office",
  },
  {
    name: "Impact Teachers",
    categories: ["Teaching"],
    type: "Teaching recruiter",
    destinations: ["United Kingdom"],
    website: "https://impactteachers.com/apply-register-with-us/southafrica/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "London-based UK teacher recruiter with dedicated SA portal; employer-pays model; small sample of positive Indeed reviews; no TrustPilot listing found",
  },
  {
    name: "Intergate Emigration",
    categories: ["Migration consultants"],
    type: "Immigration consultant",
    destinations: ["Australia", "New Zealand", "South Africa (Inbound)"],
    website: "https://www.intergate-emigration.com/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Intergate Emigration GmbH is a boutique immigration consultancy specialising in Australia, New Zealand, and South Africa immigration and visa services. Established as a formal entity in 2015 and headquartered in Hamburg, Germany, the firm operates from four offices — Hamburg, Zürich (Switzerland), Cork (Ireland), and Cape Town (South Africa) — reflecting its primary client base…",
  },
  {
    name: "Medipath Healthcare Recruitment",
    categories: ["Healthcare"],
    type: "Nursing recruiter",
    destinations: ["South Africa", "Australia", "New Zealand"],
    website: "https://www.medipath.co.za/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "SA-based healthcare recruiter since 2012 — places nurses in Australia and New Zealand; LinkedIn-verified; fee structure not disclosed; CIPC reg not found on site",
  },
  {
    name: "MMA Healthcare Recruitment",
    categories: ["Healthcare", "Migration consultants"],
    type: "Nursing recruiter",
    destinations: ["United Kingdom", "Ireland", "Germany", "United States", "Australia", "Canada", "New Zealand"],
    website: "https://mmarecruitment.com/applicants/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Established UK/Ireland nursing recruiter since 1998 (Melinda Moolman) — SA office confirmed; 2,000+ placements; NHS Employers Code + WHO Code compliant; employer pays; check red-list status for SA",
  },
  {
    name: "Move Up",
    categories: ["Migration consultants"],
    type: "Recruiter",
    destinations: ["United Kingdom"],
    website: "https://ukjobs.moveup.co.za/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Move Up is a South African recruitment firm that specialises in connecting South African professionals — primarily engineers — with UK employers who hold or can obtain Skilled Worker visa sponsorship licences. The company explicitly positions itself for South Africans without UK ancestry or marriage ties, navigating the UK Skilled Worker visa route as the primary pathway.",
  },
  {
    name: "Network Migration Services",
    categories: ["Migration consultants"],
    type: "Immigration consultant",
    destinations: ["Australia", "New Zealand"],
    website: "https://www.networkmigration.com/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Network Migration Services is a Johannesburg-based migration consultancy with 30+ years of operation and 10,000+ families successfully assisted to migrate to Australia and New Zealand. The firm is one of the most experienced SA-domiciled Australia/New Zealand immigration specialists, with its principal director Andrew Kerr holding MARA (Australia) and IAA (New Zealand) registra…",
  },
  {
    name: "NHS England International Recruitment Programme",
    categories: ["Healthcare"],
    type: "Nursing recruiter",
    destinations: ["United Kingdom"],
    website: "https://www.healthcareers.nhs.uk/we-are-the-nhs/nursing-careers/international-recruitment/application-process",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "NHS England programme that funds trust-level international nurse recruitment — not a direct nurse-facing agency; nurses apply via healthcareers.nhs.uk",
  },
  {
    name: "NOCN Job Cards (CPCS / CISRS)",
    categories: ["Trades"],
    type: "Competence card issuer",
    destinations: ["United Kingdom"],
    website: "https://www.nocnjobcards.org/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "NOCN Group is a UK charity and awarding organisation that owns the Construction Plant Competence Scheme (CPCS) and is responsible for providing scheme administration services to the Construction Industry Scaffolders Record Scheme (CISRS).",
  },
  {
    name: "SA-Recruitment",
    categories: ["Teaching"],
    type: "Teaching recruiter",
    destinations: ["Middle East", "Australia"],
    website: "https://www.sa-recruitment.com",
    email: "",
    phone: "",
    evidence: "alleged" as Recruiter['evidence'],
    notes: "SA-based recruiter placing teachers in international schools in Middle East and Australia; 20+ years claimed; CIPC status unverified; no TrustPilot/HelloPeter found",
  },
  {
    name: "Sable International",
    categories: ["Trades"],
    type: "Migration consultancy",
    destinations: ["United Kingdom", "Australia"],
    website: "https://www.sableinternational.com/immigration/contact",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Sable International is a Cape Town–based (and UK/Australia–based) financial and immigration services firm that provides cross-border financial advice, immigration consulting, and related services to South Africans and other global citizens. It is a vetted SA-facing migration consultancy with confirmed OISC registration for UK immigration advice (OISC Number: F2001-00004).",
  },
  {
    name: "Teaching Vacancies",
    categories: ["Teaching"],
    type: "Support organisation",
    destinations: ["United Kingdom"],
    website: "https://teaching-vacancies.service.gov.uk/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Free DfE government job board for UK school teaching jobs; SA teachers can apply directly to schools without using a paid recruitment agency",
  },
  {
    name: "TES (Times Educational Supplement)",
    categories: ["Teaching"],
    type: "Support organisation",
    destinations: ["United Kingdom", "International"],
    website: "https://www.tes.com/jobs/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Major UK and international teacher job board; free for candidates; widely used by SA teachers seeking UK and international school roles",
  },
  {
    name: "Tradewind Recruitment",
    categories: ["Teaching"],
    type: "Teaching recruiter",
    destinations: ["United Kingdom"],
    website: "https://www.twrecruitment.com/teachers-from-south-africa",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "UK teacher agency with 13 offices and dedicated SA support; employer-pays; 82 TrustPilot reviews (positive); noted for KCSIE training and CPD access",
  },
];

export const scamPatterns: ScamPattern[] = [
  {
    name: "Canada SAWP Confusion Scam",
    category: "Farming",
    vault: "Closed scheme pitch, Upfront recruitment fee",
    destinations: [],
    channels: ["facebook", "whatsapp", "email", "indeed"],
    typicalFeeZar: "3000–15000",
    reportSa: "SAPS (saps.gov.za); SA Department of Employment and Labour",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Canada SAWP is for Mexico and Caribbean countries only; SA workers are not eligible — but the legitimate Canadian Agricultural Stream via LMIA is open to all nationalities.",
  },
  {
    name: "Fake Australia PALM Placement Scam",
    category: "Farming",
    vault: "Closed scheme pitch",
    destinations: [],
    channels: ["facebook", "whatsapp", "telegram", "indeed", "email", "instagram"],
    typicalFeeZar: "3000–15000",
    reportSa: "SAPS (saps.gov.za); SA Department of Employment and Labour",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Fraudulent recruiters pitch PALM scheme placements to SA workers; PALM is restricted to 9 Pacific nations + Timor-Leste — SA is ineligible by design.",
  },
  {
    name: "Fake NZ RSE Placement Scam",
    category: "Farming",
    vault: "Closed scheme pitch",
    destinations: [],
    channels: ["facebook", "whatsapp", "telegram", "email", "indeed"],
    typicalFeeZar: "3000–12000",
    reportSa: "SAPS (saps.gov.za); SA Department of Employment and Labour",
    reportDestination: "",
    evidence: "confirmed",
    summary: "NZ RSE scheme is Pacific-only; South Africa is ineligible — any RSE placement pitch to a SA worker is fraudulent by design.",
  },
  {
    name: "Fake UK Seasonal Worker Agency Scam",
    category: "Farming",
    vault: "Fake scheme operator, Upfront recruitment fee",
    destinations: [],
    channels: ["facebook", "whatsapp", "indeed", "email", "linkedin"],
    typicalFeeZar: "5000–25000",
    reportSa: "SAPS (saps.gov.za); SA Department of Employment and Labour",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Fraudulent agencies claim to be UK Seasonal Worker scheme operators; only 5 Defra-endorsed operators can issue Certificates of Sponsorship for this route.",
  },
  {
    name: "Guaranteed PR Via Farm Work Pitch",
    category: "Farming",
    vault: "Guaranteed pr claim",
    destinations: [],
    channels: ["facebook", "whatsapp", "telegram", "tiktok", "instagram", "email"],
    typicalFeeZar: "10000–50000",
    reportSa: "SAPS (saps.gov.za); SA Department of Employment and Labour",
    reportDestination: "",
    evidence: "confirmed",
    summary: "UK Seasonal Worker, H-2A, and Canadian SAWP/Agricultural Stream do not provide permanent residency; any PR guarantee via these routes is a misrepresentation used to extract fees.",
  },
  {
    name: "H-2A Worker Recruitment Fee Scam",
    category: "Farming",
    vault: "Upfront recruitment fee",
    destinations: [],
    channels: ["facebook", "whatsapp", "indeed", "email", "telegram"],
    typicalFeeZar: "3000–20000",
    reportSa: "SAPS (saps.gov.za); US Embassy Pretoria (za.usembassy.gov)",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Charging H-2A workers recruitment/placement fees is illegal under 20 CFR §655.135(j)–(k); any recruiter asking SA workers for H-2A placement money is breaking US federal law.",
  },
  {
    name: "Maritime Offshore Fishing Vessel Scam",
    category: "Farming",
    vault: "Fake employer, Upfront recruitment fee",
    destinations: [],
    channels: ["email", "facebook", "whatsapp", "indeed"],
    typicalFeeZar: "5000–30000",
    reportSa: "SAPS (saps.gov.za)",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Fraudulent emails offer employment on Australian cruise ships or fishing vessels to South Africans; victims pay for fake visas or 'foreign worker certificates' and receive nothing.",
  },
  {
    name: "Bogus Canadian Hotel Agency Demanding LMIA Fee from Worker",
    category: "Hospitality",
    vault: "Hospitality",
    destinations: [],
    channels: [],
    typicalFeeZar: "",
    reportSa: "",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Fake Canadian hotel agencies sell LMIA-approved jobs for $25k–$50k — illegal; employer must pay all LMIA costs",
  },
  {
    name: "Cruise Ship / Yacht Hospitality Scam with Maritime Visa and Uniform Deposit",
    category: "Hospitality",
    vault: "Hospitality",
    destinations: [],
    channels: [],
    typicalFeeZar: "",
    reportSa: "",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Fake cruise recruiter demands upfront 'maritime visa' and uniform deposit — MLC 2006 prohibits all advance seafarer fees",
  },
  {
    name: "Fake UAE Hotel Job with Upfront Registration Fee",
    category: "Hospitality",
    vault: "Hospitality",
    destinations: [],
    channels: [],
    typicalFeeZar: "",
    reportSa: "",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Fake UAE hospitality job ads demand R3k–R10k upfront for visa/registration — illegal under MOHRE Resolution 47/2022",
  },
  {
    name: "Fake UK Certificate of Sponsorship for Sale",
    category: "Hospitality",
    vault: "Hospitality",
    destinations: [],
    channels: [],
    typicalFeeZar: "",
    reportSa: "",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Fraudulent UK CoS sold for £3k–£8k on WhatsApp/Telegram; criminal offence since Feb 2026 to advertise",
  },
  {
    name: "Fake UK Chef Placement After 22 July 2025",
    category: "Hospitality",
    vault: "Hospitality",
    destinations: [],
    channels: [],
    typicalFeeZar: "",
    reportSa: "",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Post-July 2025 UK chef/waiter Skilled Worker visa no longer exists; ads for it are fake or fraudulent",
  },
  {
    name: "Romance and Dating-App Dubai Hotel Job Scam",
    category: "Hospitality",
    vault: "Hospitality",
    destinations: [],
    channels: [],
    typicalFeeZar: "",
    reportSa: "",
    reportDestination: "",
    evidence: "alleged",
    summary: "Romance scam combined with Dubai hotel job offer; 'fiancé in Dubai' pattern combines emotional manipulation + visa fraud",
  },
  {
    name: "Tourist Visa and Find a Job in Dubai Pitch",
    category: "Hospitality",
    vault: "Hospitality",
    destinations: [],
    channels: [],
    typicalFeeZar: "",
    reportSa: "",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Recruiters tell SA hospitality workers to fly Dubai on tourist visa and job-hunt — illegal; deportation + AED 200/day fine",
  },
  {
    name: "Bogus SA Nursing College",
    category: "Healthcare",
    vault: "Fake programme",
    destinations: ["UK", "Australia", "Ireland"],
    channels: ["facebook", "whatsapp", "in_person"],
    typicalFeeZar: "10000–50000 (\\\"tuition\\\" for a non-existent programme)",
    reportSa: "SAPS (10111); Presidential Hotline (17737); Department of Health provincial offices; SANC (sanc.co.za)",
    reportDestination: "Action Fraud UK (0300 123 2040) if abroad-bound; NMC (020 7637 7181)",
    evidence: "confirmed",
    summary: "SA-based fake nursing colleges charge tuition and issue worthless 'diplomas' — victims left without valid SANC credentials and unplaceable abroad.",
  },
  {
    name: "Contract Trap and Bonded Labour",
    category: "Healthcare",
    vault: "Fake agency",
    destinations: ["UK", "Australia"],
    channels: ["whatsapp", "linkedin", "email", "in_person"],
    typicalFeeZar: "0 upfront — trap is enforced after arrival via contract clawback (R100000–R500000)",
    reportSa: "SA Fraud Prevention Service (0800 222 999); Department of Employment and Labour (0800 220 818)",
    reportDestination: "Gangmaster and Labour Abuse Authority UK (gla.gov.uk / 0800 432 0804); Fair Work Ombudsman AUS (fairwork.gov.au)",
    evidence: "confirmed",
    summary: "Agencies insert disproportionate repayment clauses trapping nurses in UK/AUS care homes; leaving triggers R200k+ clawback demands.",
  },
  {
    name: "Fake HSE Employer Ireland",
    category: "Healthcare",
    vault: "Fake employer",
    destinations: ["Ireland"],
    channels: ["whatsapp", "facebook", "linkedin", "zoom_teams", "email"],
    typicalFeeZar: "45000–165000 (€2300–€11000 range documented)",
    reportSa: "SAPS (10111); nearest Irish embassy (Pretoria)",
    reportDestination: "An Garda Síochána (garda.ie); NMBI (nmbi.ie); Migrant Nurses Ireland (MNI)",
    evidence: "confirmed",
    summary: "Operators clone HSE letterheads to sell fake Ireland nursing jobs — nurses pay €4k–€11k, receive genuine permits, arrive jobless.",
  },
  {
    name: "Fake NHS Trust Recruitment",
    category: "Healthcare",
    vault: "Fake employer",
    destinations: ["UK"],
    channels: ["facebook", "whatsapp", "linkedin", "indeed", "email"],
    typicalFeeZar: "5000–50000 (visa/relocation advance fees)",
    reportSa: "SAPS (10111 or saps.gov.za); South African Fraud Prevention Service (0800 222 999)",
    reportDestination: "Action Fraud (actionfraud.police.uk / 0300 123 2040); NHS Counter Fraud Authority (cfa.nhs.uk)",
    evidence: "confirmed",
    summary: "Scammers clone NHS trust branding to recruit SA nurses with fake job offers, extracting visa and relocation fees.",
  },
  {
    name: "Fake NMC Registration Agent",
    category: "Healthcare",
    vault: "Fake registration agent",
    destinations: ["UK"],
    channels: ["whatsapp", "email", "facebook", "phone"],
    typicalFeeZar: "3000–20000 (\\\"processing\\\" or \\\"fast-track\\\" fees)",
    reportSa: "SAPS (10111); South African Fraud Prevention Service (0800 222 999)",
    reportDestination: "NMC directly: 020 7637 7181; Action Fraud: 0300 123 2040",
    evidence: "confirmed",
    summary: "Fraudsters pose as NMC agents charging fees to 'fast-track' registration — NMC never charges via phone or third parties.",
  },
  {
    name: "Nursing Qualification Fraud",
    category: "Healthcare",
    vault: "Qualification fraud",
    destinations: ["UK", "Australia", "Ireland", "USA"],
    channels: ["whatsapp", "facebook", "email", "in_person"],
    typicalFeeZar: "5000–50000 (per fraudulent document set)",
    reportSa: "SAPS (10111); SAQA fraud hotline; SANC (sanc.co.za); SA Fraud Prevention Service (0800 222 999)",
    reportDestination: "Action Fraud UK (0300 123 2040); AHPRA Australia (ahpra.gov.au/Complaints); NMC UK (020 7637 7181)",
    evidence: "confirmed",
    summary: "Fraudsters sell fake SA nursing transcripts, SANC certificates, or university diplomas to nurses and would-be nurses seeking work abroad.",
  },
  {
    name: "Unregistered Nursing Agency",
    category: "Healthcare",
    vault: "Fake agency",
    destinations: ["UK", "Australia", "Ireland"],
    channels: ["facebook", "whatsapp", "linkedin", "indeed", "email"],
    typicalFeeZar: "5000–30000 (registration, placement, or admin fees)",
    reportSa: "SAPS (10111); Department of Employment and Labour (0800 220 818 / labour.gov.za)",
    reportDestination: "Action Fraud UK: 0300 123 2040; AHPRA Australia: ahpra.gov.au/Complaints",
    evidence: "confirmed",
    summary: "SA-based unregistered agencies collect fees from nurses for UK/AUS/IRE placement with no legitimate employer relationships.",
  },
  {
    name: "Upfront OSCE CBT Guarantee Fee Scam",
    category: "Healthcare",
    vault: "Upfront exam fee",
    destinations: ["UK"],
    channels: ["facebook", "whatsapp", "email", "linkedin"],
    typicalFeeZar: "5000–30000 (\\\"guarantee\\\" or \\\"preparation\\\" fees)",
    reportSa: "SAPS (10111); SA Fraud Prevention Service (0800 222 999)",
    reportDestination: "Action Fraud (0300 123 2040 / actionfraud.police.uk); NMC: 020 7637 7181",
    evidence: "confirmed",
    summary: "Fraudsters charge SA nurses upfront fees to 'guarantee' OSCE/CBT pass — no entity can legally guarantee exam outcomes.",
  },
  {
    name: "Canada IEC Fake Recognized Organisation Scam",
    category: "Seasonal",
    vault: "Fake sponsor agency, Upfront fee, Guaranteed placement",
    destinations: [],
    channels: ["facebook", "whatsapp", "linkedin", "email"],
    typicalFeeZar: "R28000–R37000 (equiv. CAD 2000 / USD 1500 — typical reported IEC employment scam loss)",
    reportSa: "SAPS (saps.gov.za); SA Dept of Employment and Labour",
    reportDestination: "",
    evidence: "alleged",
    summary: "Scammers pose as mandatory IEC Recognized Organisations to charge SA-eligible youth upfront fees — ROs are in fact optional intermediaries.",
  },
  {
    name: "Fake J1 Placement Agency Scam",
    category: "Seasonal",
    vault: "Fake sponsor agency, Upfront fee, Guaranteed placement",
    destinations: [],
    channels: ["facebook", "whatsapp", "linkedin", "indeed", "email", "instagram"],
    typicalFeeZar: "R2000–R15000 (varies; sometimes USD 200–500 framed as 'admin' or 'processing' fee)",
    reportSa: "SAPS (saps.gov.za); SA Dept of Employment and Labour",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Fraudulent agencies charge SA students upfront fees to 'secure' J1 Summer Work Travel placements, falsely claiming to issue DS-2019 forms.",
  },
  {
    name: "Fake UK Seasonal Recruiter Scam",
    category: "Seasonal",
    vault: "Fake sponsor agency, Fake visa service, Upfront fee",
    destinations: [],
    channels: ["facebook", "whatsapp", "linkedin", "instagram", "email"],
    typicalFeeZar: "R3000–R12000 (framed as 'YMS application assistance', 'visa fast-track', or 'slot reservation')",
    reportSa: "SAPS (saps.gov.za); SA Dept of Employment and Labour",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Fraudulent services charge SA applicants for 'assisted' UK Youth Mobility Scheme applications — a process that requires no intermediary and cannot be fast-tracked.",
  },
  {
    name: "Guaranteed Disney Resort Job Scam",
    category: "Seasonal",
    vault: "Fake employer, Upfront fee, Guaranteed placement",
    destinations: [],
    channels: ["facebook", "whatsapp", "instagram", "indeed", "email"],
    typicalFeeZar: "R1500–R10000 (framed as 'processing' or 'placement guarantee' fee)",
    reportSa: "SAPS (saps.gov.za); SA Dept of Employment and Labour",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Scammers impersonate Disney hiring to offer 'guaranteed' USA seasonal jobs, collecting fees and personal data from SA students.",
  },
  {
    name: "Advance Fee Fraud",
    category: "General",
    vault: "Advance fee",
    destinations: [],
    channels: ["email", "whatsapp", "facebook", "linkedin", "in_person"],
    typicalFeeZar: "R500–R10000+ (escalating through multiple invented obstacles)",
    reportSa: "SAPS Commercial Crime Branch: hq.commercial@saps.org.za; SAPS Cybercrime Division",
    reportDestination: "Action Fraud UK (actionfraud.police.uk); FTC USA (ReportFraud.ftc.gov); US Secret Service (419.fcd@usss.treas.gov)",
    evidence: "confirmed",
    summary: "Repeated fee extraction through invented obstacles before a promised job, visa, or payment that never materialises.",
  },
  {
    name: "Fake Job Offer Scam",
    category: "General",
    vault: "Job offer",
    destinations: [],
    channels: ["whatsapp", "facebook", "email", "in_person", "indeed", "gumtree"],
    typicalFeeZar: "R150–R2000 (registration, background check, uniform, admin)",
    reportSa: "SAPS Cybercrime Division; Department of Employment and Labour (086 6002 2194); SAFPS",
    reportDestination: "Action Fraud UK; ACCC Australia; US FTC (ReportFraud.ftc.gov)",
    evidence: "confirmed",
    summary: "Fee-based fake job offer exploiting SA's 31.9% unemployment rate via WhatsApp, Facebook, and cloned websites.",
  },
  {
    name: "Fake Recruitment Agency",
    category: "General",
    vault: "Job offer",
    destinations: [],
    channels: ["email", "facebook", "indeed", "in_person", "fax", "whatsapp"],
    typicalFeeZar: "R200–R3000 (placement, criminal clearance, insurance enrollment, fax premium rate)",
    reportSa: "SAPS; Department of Employment and Labour (086 6002 2194); CIPC",
    reportDestination: "Action Fraud UK; ACCC Australia",
    evidence: "confirmed",
    summary: "Illegally operating recruiters collect fees from SA job seekers for placements that don't materialise.",
  },
  {
    name: "Identity Document Fraud",
    category: "General",
    vault: "Identity",
    destinations: [],
    channels: ["email", "whatsapp", "in_person", "zoom_teams", "linkedin"],
    typicalFeeZar: "Not applicable — value extracted is the identity itself, worth thousands in downstream fraud",
    reportSa: "SAPS Cybercrime; SAFPS (011 867 2234 / protection@safps.org.za); credit bureaux (TransUnion, Experian)",
    reportDestination: "Action Fraud UK; FTC USA (IdentityTheft.gov); ACCC Australia (scamwatch.gov.au)",
    evidence: "confirmed",
    summary: "Scammers harvest SA victims' ID, passport, or bank details during fake job or visa processes — enabling downstream financial crime.",
  },
  {
    name: "LinkedIn Recruiter Impersonation",
    category: "General",
    vault: "Impersonation",
    destinations: [],
    channels: ["linkedin", "email", "indeed", "zoom_teams"],
    typicalFeeZar: "R1500–R25000 (equipment invoice or identity theft value)",
    reportSa: "SAPS Cybercrime Division; SAFPS",
    reportDestination: "Action Fraud UK (actionfraud.police.uk); FTC USA (ReportFraud.ftc.gov); LinkedIn Safety (linkedin.com/help)",
    evidence: "confirmed",
    summary: "Scammers clone real LinkedIn recruiter profiles to deliver fake job offers and harvest money or identity data.",
  },
  {
    name: "Phantom Interview Scam",
    category: "General",
    vault: "Phantom interview",
    destinations: [],
    channels: ["zoom_teams", "linkedin", "indeed", "email", "whatsapp"],
    typicalFeeZar: "R1000–R20000 (fake equipment deposit or fake check reimbursement)",
    reportSa: "SAPS Cybercrime Division; SAFPS",
    reportDestination: "Action Fraud UK (actionfraud.police.uk); FTC USA (ReportFraud.ftc.gov); ACCC Australia (scamwatch.gov.au)",
    evidence: "confirmed",
    summary: "Scammer conducts a fake job interview via Zoom or Teams chat (no video), then extracts money or identity data.",
  },
  {
    name: "Scam Compound Operator",
    category: "General",
    vault: "General",
    destinations: [],
    channels: [],
    typicalFeeZar: "",
    reportSa: "",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Transnational criminal syndicates trafficking South Africans into forced online fraud operations in Myanmar, Cambodia, and Laos.",
  },
  {
    name: "Upfront Visa Fee Fraud",
    category: "General",
    vault: "Visa fee",
    destinations: [],
    channels: ["email", "whatsapp", "facebook", "linkedin", "in_person"],
    typicalFeeZar: "R500–R15000 (visa processing, work permit, medical, flight deposit)",
    reportSa: "SAPS Cybercrime Division; DIRCO; Department of Employment and Labour (086 6002 2194)",
    reportDestination: "Australian High Commission Pretoria (+27 12 423 6000); UK Home Office (gov.uk/report-immigration-fraud); Action Fraud UK (actionfraud.police.uk)",
    evidence: "confirmed",
    summary: "Scammers charge SA job seekers upfront for fraudulent visa or work permit processing — fees rarely below R1000.",
  },
  {
    name: "WhatsApp Global Group Placement Scam",
    category: "General",
    vault: "Job offer",
    destinations: [],
    channels: ["whatsapp", "linkedin", "facebook"],
    typicalFeeZar: "R300–R5000 (committal/activation fee to secure placement)",
    reportSa: "SAPS Cybercrime Division; report group to WhatsApp (Settings → Report)",
    reportDestination: "Action Fraud UK (actionfraud.police.uk); FTC USA (ReportFraud.ftc.gov)",
    evidence: "confirmed",
    summary: "Invitation-only WhatsApp group claiming to place members in overseas jobs; admin-only permissions trap victims and prevent warnings.",
  },
  {
    name: "Australian Teacher Registration Scam",
    category: "Teaching",
    vault: "Fake agency, Upfront placement fee, Qualification misrepresentation",
    destinations: ["Australia"],
    channels: ["facebook", "whatsapp", "linkedin", "email"],
    typicalFeeZar: "45000",
    reportSa: "SAPS (saps.gov.za); National Consumer Commission (ncc.gov.za)",
    reportDestination: "Australian Competition and Consumer Commission/Scamwatch (scamwatch.gov.au); Fair Work Ombudsman (fairwork.gov.au)",
    evidence: "alleged",
    summary: "Fraudulent agents charge SA teachers for 'bundled' AITSL + state registration + visa packages; all three are applied to separately and directly — no agent is needed.",
  },
  {
    name: "Fake DBS Check Fee Scam",
    category: "Teaching",
    vault: "Upfront placement fee, Fake employer",
    destinations: ["UK"],
    channels: ["email", "whatsapp", "linkedin", "indeed"],
    typicalFeeZar: "5000",
    reportSa: "SAPS (saps.gov.za)",
    reportDestination: "Action Fraud (actionfraud.police.uk); DBS directly (gov.uk/find-dbs-umbrella-body)",
    evidence: "confirmed",
    summary: "Fraudsters charge teachers upfront for fake 'Enhanced DBS checks' during recruitment; real DBS checks cost £49.50 max and are not demanded before a genuine job offer.",
  },
  {
    name: "Fake Guaranteed UK Placement Agency",
    category: "Teaching",
    vault: "Fake agency, Upfront placement fee",
    destinations: ["UK", "Australia"],
    channels: ["facebook", "whatsapp", "linkedin", "indeed", "email", "zoom_teams"],
    typicalFeeZar: "35000",
    reportSa: "SAPS (saps.gov.za); National Consumer Commission (ncc.gov.za); labour.gov.za",
    reportDestination: "Action Fraud (actionfraud.police.uk); Recruitment and Employment Confederation (rec.uk.com) for UK; Fair Work Ombudsman (fairwork.gov.au) for Australia",
    evidence: "confirmed",
    summary: "Fraudulent agencies charge SA teachers upfront 'placement', 'visa processing', or 'shortlisting' fees; legitimate UK teacher recruiters charge only the hiring school.",
  },
  {
    name: "Fraudulent Certificate of Sponsorship Seller",
    category: "Teaching",
    vault: "Fake cos seller",
    destinations: ["UK"],
    channels: ["facebook", "whatsapp", "linkedin", "email", "zoom_teams"],
    typicalFeeZar: "200000",
    reportSa: "SAPS (saps.gov.za); labour.gov.za",
    reportDestination: "Action Fraud (actionfraud.police.uk); Home Office immigration crime (gov.uk/report-immigration-crime)",
    evidence: "confirmed",
    summary: "Scam selling fake or invalid UK Certificates of Sponsorship to teachers/workers for fees up to £42,000; CoS is always free to candidates.",
  },
  {
    name: "QTS Misrepresentation Scam",
    category: "Teaching",
    vault: "Qualification misrepresentation",
    destinations: ["UK"],
    channels: ["facebook", "whatsapp", "linkedin", "email"],
    typicalFeeZar: "15000",
    reportSa: "SAPS (saps.gov.za); consumer complaints to National Consumer Commission (ncc.gov.za)",
    reportDestination: "Action Fraud (actionfraud.police.uk); DfE Teaching Regulation Agency (gov.uk/guidance/teacher-misconduct-regulating-the-teaching-profession)",
    evidence: "confirmed",
    summary: "Agents falsely claim all SA teachers get free automatic QTS regardless of subject, then charge for 'processing' a qualification that may not be obtainable.",
  },
  {
    name: "SACE Document Harvesting Scam",
    category: "Teaching",
    vault: "Document harvesting",
    destinations: ["UK", "Australia", "UAE", "General"],
    channels: ["whatsapp", "facebook", "email", "in_person"],
    typicalFeeZar: "2800",
    reportSa: "SAPS (saps.gov.za); SACE directly (sace.org.za); WCED/provincial education departments",
    reportDestination: "Action Fraud (actionfraud.police.uk) for UK-directed variants",
    evidence: "confirmed",
    summary: "Scammers impersonate SACE officials or overseas recruiters to harvest original SACE certificates, police clearances, and passports before any legitimate employment exists.",
  },
  {
    name: "School Impersonation Scam",
    category: "Teaching",
    vault: "Fake employer",
    destinations: ["UK", "Australia", "General"],
    channels: ["email", "linkedin", "indeed", "facebook", "whatsapp"],
    typicalFeeZar: "25000",
    reportSa: "SAPS (saps.gov.za)",
    reportDestination: "Action Fraud (actionfraud.police.uk); reporting to the real school whose name was impersonated",
    evidence: "confirmed",
    summary: "Scammers use near-identical names or stolen branding of real UK schools to issue fake job offers and collect fees or documents from SA teachers.",
  },
  {
    name: "Australian FIFO Mining Placement Scam",
    category: "Trades",
    vault: "Guaranteed placement, Upfront fee, Maritime oil rig, Fifo mining, Fake employer",
    destinations: ["australia"],
    channels: ["facebook", "whatsapp", "telegram", "instagram", "indeed", "email", "recruitment_agency"],
    typicalFeeZar: "50000",
    reportSa: "SAPS (saps.gov.za); Australian High Commission Pretoria (southafrica.embassy.gov.au)",
    reportDestination: "Department of Home Affairs — visa fraud reporting (homeaffairs.gov.au); Border Watch Line",
    evidence: "confirmed",
    summary: "Fake recruiters offer SA tradespeople FIFO/mining/oil rig placements in Australia, bypassing TRA assessment and SBS requirements.",
  },
  {
    name: "Fake Canadian Trades Visa Pipeline",
    category: "Trades",
    vault: "Fake pnp nomination, Upfront fee, Guaranteed placement, Fake immigration adviser",
    destinations: ["canada"],
    channels: ["facebook", "whatsapp", "telegram", "tiktok", "youtube", "instagram"],
    typicalFeeZar: "40000",
    reportSa: "SAPS (saps.gov.za); Canadian High Commission Pretoria",
    reportDestination: "Canadian Anti-Fraud Centre (CAFC) — antifraudcentre-centreantifraude.ca; IRCC fraud reporting",
    evidence: "confirmed",
    summary: "Operators on Facebook/TikTok/Telegram sell fake 'guaranteed PNP nominations' to SA tradespeople; PNPs are issued by provinces, not agents.",
  },
  {
    name: "Fake New Zealand Trades Placement",
    category: "Trades",
    vault: "Fake employer, Upfront fee, Guaranteed placement, Identity theft",
    destinations: ["new_zealand"],
    channels: ["facebook", "whatsapp", "email", "indeed", "recruitment_agency"],
    typicalFeeZar: "30000",
    reportSa: "SAPS (saps.gov.za); NZ High Commission Pretoria",
    reportDestination: "Immigration NZ fraud reporting (immigration.govt.nz); New Zealand Police",
    evidence: "confirmed",
    summary: "Fake NZ employer offers targeting SA tradespeople exploit AEWV system; company absent from Accredited Employer list = definitive fraud indicator.",
  },
  {
    name: "Fake UAE Trades Placement",
    category: "Trades",
    vault: "Fake employer, Upfront fee, Guaranteed placement, Identity theft",
    destinations: ["uae"],
    channels: ["facebook", "whatsapp", "telegram", "instagram", "indeed", "email"],
    typicalFeeZar: "25000",
    reportSa: "SAPS (saps.gov.za); UAE Embassy Pretoria",
    reportDestination: "MOHRE — ask@mohre.gov.ae / +971 6802 7666; Dubai GDRFA; ICP eChannels",
    evidence: "confirmed",
    summary: "Fake UAE construction/trades offers target SA workers with upfront fee demands; MOHRE warns all genuine offers must be issued through the ministry system.",
  },
  {
    name: "Fake UK Certificate of Sponsorship Scam",
    category: "Trades",
    vault: "Fake cos, Upfront fee, Guaranteed placement",
    destinations: ["uk"],
    channels: ["facebook", "whatsapp", "telegram", "tiktok", "instagram", "email", "website", "recruitment_agency"],
    typicalFeeZar: "230000",
    reportSa: "SAPS (saps.gov.za); SA Department of Employment and Labour",
    reportDestination: "Action Fraud (actionfraud.police.uk); Home Office immigration enforcement",
    evidence: "confirmed",
    summary: "Agents sell fake or invalid UK CoS documents to SA tradespeople for £10k–£35k; only Licensed Sponsors can issue CoS.",
  },
  {
    name: "Fake UK Competence Card Services",
    category: "Trades",
    vault: "Fake competence card, Upfront fee",
    destinations: ["uk"],
    channels: ["facebook", "instagram", "tiktok", "twitter", "whatsapp", "telegram"],
    typicalFeeZar: "3000",
    reportSa: "SAPS (saps.gov.za)",
    reportDestination: "CSCS — intel@cscs.co.uk; JIB — feedback@ecscard.org.uk; Police",
    evidence: "confirmed",
    summary: "Operators sell fake pre-arrival CSCS/ECS/JIB competence cards on social media; real cards require UK-assessed qualifications.",
  },
];
