// AUTO-GENERATED from wiki-builds vaults via /tmp/extract_contacts.py — do not edit by hand.
// Re-run the extractor when the wiki vaults change.

export type Recruiter = {
  name: string;
  categories: string[];
  type: string;
  destinations: string[];
  website: string;
  email: string;
  phone: string;
  evidence: 'confirmed' | 'high' | 'alleged' | '';
  notes: string;
};

export type ScamPattern = {
  name: string;
  category: string;
  vault: string;
  destinations: string[];
  channels: string[];
  typicalFeeZar: string;
  reportSa: string;
  reportDestination: string;
  evidence: string;
  summary: string;
};

export const recruiters: Recruiter[] = [
  {
    name: "AHP International Nursing / ALOR Group",
    categories: ["Healthcare"],
    type: "Nursing recruiter",
    destinations: ["Australia"],
    website: "https://alorgroup.com.au/",
    email: "",
    phone: "",
    evidence: "alleged" as Recruiter['evidence'],
    notes: "AHP International Nursing had SA-specific Australia recruitment page — website now redirects to ALOR Group (rebrand uncertain); verify with ALOR directly before recommending",
  },
  {
    name: "Apostil.co.za",
    categories: ["Trades"],
    type: "Document concierge",
    destinations: ["Australia", "United Kingdom", "Canada", "New Zealand", "UAE"],
    website: "https://apostil.co.za/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Apostil.co.za (also operating as apostille.co.za) is a South African document concierge firm specialising in apostilles, notarisations, authentications, and document certifications for use abroad. It is confirmed as a DIRCO-registered agent — agents submit to DIRCO on Wednesdays only, with a 1–2 week turnaround compared to the public's 3–4 week courier wait.",
  },
  {
    name: "Breytenbachs / BIC",
    categories: ["Migration consultants"],
    type: "Immigration consultant",
    destinations: ["United Kingdom", "South Africa", "Ireland"],
    website: "https://www.bic-immigration.com/contact/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Breytenbachs Immigration Consultants Ltd (trading as BIC) is a multi-jurisdiction immigration consultancy with deep roots in the South African market, operating from offices in London, Pretoria, Durban, and Cape Town. The firm specialises in UK immigration law and visa applications as its primary service, with secondary expertise in South African and Irish immigration.",
  },
  {
    name: "CSCS",
    categories: ["Trades"],
    type: "Competence card issuer",
    destinations: ["United Kingdom"],
    website: "https://www.cscs.uk.com/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "The Construction Skills Certification Scheme (CSCS) is the UK's primary competence card scheme for construction site workers, administered via the CITB (Construction Industry Training Board). A CSCS card proves that an individual working on a UK construction site holds appropriate training and qualifications for their role.",
  },
  {
    name: "ECS Card",
    categories: ["Trades"],
    type: "Competence card issuer",
    destinations: ["United Kingdom"],
    website: "https://www.ecscard.org.uk/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "The Electrotechnical Certification Scheme (ECS) is the UK's industry competence card scheme specifically for electricians and electrotechnical workers, administered by the Joint Industry Board (JIB) for England, Wales, and Northern Ireland, and by the Scottish JIB (SJIB) for Scotland.",
  },
  {
    name: "Engage Education",
    categories: ["Teaching"],
    type: "Teaching recruiter",
    destinations: ["United Kingdom"],
    website: "https://engage-education.com/za/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "UK teacher recruiter since 2008 with SA-specific portal; employer-pays model; mixed TrustPilot (326 reviews) — payment delay complaints noted",
  },
  {
    name: "Eteach",
    categories: ["Teaching"],
    type: "Support organisation",
    destinations: ["United Kingdom", "International"],
    website: "https://www.eteach.com/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "UK teacher job board (20+ years); 2 million candidate database; free to search; employer-pays model; covers UK state and international schools",
  },
  {
    name: "Four Corners Emigration / Four Corners Migration",
    categories: ["Migration consultants"],
    type: "Immigration consultant",
    destinations: ["Australia", "New Zealand (Unconfirmed)"],
    website: "https://four-corners.com.au/za-migrate-to-australia/",
    email: "info@four-corners.co.za",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Four Corners Emigration (also operating as Four Corners Migration) is one of South Africa's best-established Australia and New Zealand immigration specialists, founded in 1996 and claiming 61,000+ individuals, small businesses, and multinationals assisted.",
  },
  {
    name: "Gesundheit Personal Netz",
    categories: ["Migration consultants"],
    type: "Healthcare recruiter",
    destinations: ["Germany"],
    website: "https://global.gesundheit-pn.de/southernafrica/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Gesundheit Personal Netz (Health Personnel Network) is a Berlin-based healthcare recruitment organisation that specifically recruits nurses from South Africa and Namibia for placement in German hospitals and care facilities.",
  },
  {
    name: "Global Nurse Force",
    categories: ["Healthcare", "Migration consultants"],
    type: "Nursing recruiter",
    destinations: ["United Kingdom", "United States", "Ireland", "Germany", "UAE", "Saudi Arabia", "Qatar", "Australia"],
    website: "https://www.globalnurseforce.com/contact-us",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "US-based international nursing recruiter (20+ yrs, 20,000+ placements) — zero-cost to nurses; places SA nurses in UK, USA, Ireland, Germany, GCC, Australia; no confirmed SA office",
  },
  {
    name: "Impact Teachers",
    categories: ["Teaching"],
    type: "Teaching recruiter",
    destinations: ["United Kingdom"],
    website: "https://impactteachers.com/apply-register-with-us/southafrica/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "London-based UK teacher recruiter with dedicated SA portal; employer-pays model; small sample of positive Indeed reviews; no TrustPilot listing found",
  },
  {
    name: "Intergate Emigration",
    categories: ["Migration consultants"],
    type: "Immigration consultant",
    destinations: ["Australia", "New Zealand", "South Africa (Inbound)"],
    website: "https://www.intergate-emigration.com/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Intergate Emigration GmbH is a boutique immigration consultancy specialising in Australia, New Zealand, and South Africa immigration and visa services. Established as a formal entity in 2015 and headquartered in Hamburg, Germany, the firm operates from four offices — Hamburg, Zürich (Switzerland), Cork (Ireland), and Cape Town (South Africa) — reflecting its primary client base…",
  },
  {
    name: "Medipath Healthcare Recruitment",
    categories: ["Healthcare"],
    type: "Nursing recruiter",
    destinations: ["South Africa", "Australia", "New Zealand"],
    website: "https://www.medipath.co.za/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "SA-based healthcare recruiter since 2012 — places nurses in Australia and New Zealand; LinkedIn-verified; fee structure not disclosed; CIPC reg not found on site",
  },
  {
    name: "MMA Healthcare Recruitment",
    categories: ["Healthcare", "Migration consultants"],
    type: "Nursing recruiter",
    destinations: ["United Kingdom", "Ireland", "Germany", "United States", "Australia", "Canada", "New Zealand"],
    website: "https://mmarecruitment.com/applicants/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Established UK/Ireland nursing recruiter since 1998 (Melinda Moolman) — SA office confirmed; 2,000+ placements; NHS Employers Code + WHO Code compliant; employer pays; check red-list status for SA",
  },
  {
    name: "OfferZen",
    categories: ["IT/Tech"],
    type: "Developer marketplace",
    destinations: ["Ireland", "United Kingdom", "Germany", "Netherlands"],
    website: "https://www.offerzen.com/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "SA-founded developer marketplace (CIPC-registered Pty Ltd) connecting SA ICT workers with European and African tech employers. Over 100,000 developers on the platform; 2,000+ active companies including employers in Ireland, UK, Germany, and Netherlands. Employer-pays model — FREE for developers. Useful for bypassing the cold-application problem of finding a licensed sponsor from scratch.",
  },
  {
    name: "Move Up",
    categories: ["Engineering", "Migration consultants"],
    type: "Engineering recruiter",
    destinations: ["United Kingdom"],
    website: "https://ukjobs.moveup.co.za/",
    email: "info@moveup.co.za",
    phone: "021 761 4608",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Move Up is a South African recruitment firm that specialises in connecting South African professionals — primarily engineers — with UK employers who hold or can obtain Skilled Worker visa sponsorship licences. The company explicitly positions itself for South Africans without UK ancestry or marriage ties, navigating the UK Skilled Worker visa route as the primary pathway.",
  },
  {
    name: "Network Migration Services",
    categories: ["Migration consultants"],
    type: "Immigration consultant",
    destinations: ["Australia", "New Zealand"],
    website: "https://www.networkmigration.com/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Network Migration Services is a Johannesburg-based migration consultancy with 30+ years of operation and 10,000+ families successfully assisted to migrate to Australia and New Zealand. The firm is one of the most experienced SA-domiciled Australia/New Zealand immigration specialists, with its principal director Andrew Kerr holding MARA (Australia) and IAA (New Zealand) registra…",
  },
  {
    name: "NHS England International Recruitment Programme",
    categories: ["Healthcare"],
    type: "Nursing recruiter",
    destinations: ["United Kingdom"],
    website: "https://www.healthcareers.nhs.uk/we-are-the-nhs/nursing-careers/international-recruitment/application-process",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "NHS England programme that funds trust-level international nurse recruitment — not a direct nurse-facing agency; nurses apply via healthcareers.nhs.uk",
  },
  {
    name: "NOCN Job Cards (CPCS / CISRS)",
    categories: ["Trades"],
    type: "Competence card issuer",
    destinations: ["United Kingdom"],
    website: "https://www.nocnjobcards.org/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "NOCN Group is a UK charity and awarding organisation that owns the Construction Plant Competence Scheme (CPCS) and is responsible for providing scheme administration services to the Construction Industry Scaffolders Record Scheme (CISRS).",
  },
  {
    name: "SA-Recruitment",
    categories: ["Teaching"],
    type: "Teaching recruiter",
    destinations: ["Middle East", "Australia"],
    website: "https://www.sa-recruitment.com",
    email: "",
    phone: "",
    evidence: "alleged" as Recruiter['evidence'],
    notes: "SA-based recruiter placing teachers in international schools in Middle East and Australia; 20+ years claimed; CIPC status unverified; no TrustPilot/HelloPeter found",
  },
  {
    name: "Sable International",
    categories: ["Trades", "IT/Tech", "Migration consultants"],
    type: "Migration consultancy",
    destinations: ["United Kingdom", "Australia"],
    website: "https://www.sableinternational.com/immigration/contact",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Sable International is a Cape Town–based (and UK/Australia–based) financial and immigration services firm that provides cross-border financial advice, immigration consulting, and related services to South Africans and other global citizens. It is a vetted SA-facing migration consultancy with confirmed OISC registration for UK immigration advice (OISC Number: F2001-00004).",
  },
  {
    name: "Teaching Vacancies",
    categories: ["Teaching"],
    type: "Support organisation",
    destinations: ["United Kingdom"],
    website: "https://teaching-vacancies.service.gov.uk/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Free DfE government job board for UK school teaching jobs; SA teachers can apply directly to schools without using a paid recruitment agency",
  },
  {
    name: "TES (Times Educational Supplement)",
    categories: ["Teaching"],
    type: "Support organisation",
    destinations: ["United Kingdom", "International"],
    website: "https://www.tes.com/jobs/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Major UK and international teacher job board; free for candidates; widely used by SA teachers seeking UK and international school roles",
  },
  {
    name: "Tradewind Recruitment",
    categories: ["Teaching"],
    type: "Teaching recruiter",
    destinations: ["United Kingdom"],
    website: "https://www.twrecruitment.com/teachers-from-south-africa",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "UK teacher agency with 13 offices and dedicated SA support; employer-pays; 82 TrustPilot reviews (positive); noted for KCSIE training and CPD access",
  },
  {
    name: "Auxiliares de Conversación",
    categories: ["TEFL"],
    type: "Government TEFL programme",
    destinations: ["Spain"],
    website: "https://aee.educacionfpydeportes.gob.es/oportunidades/todas/auxiliares-conversacion/extranjeros.html",
    email: "auxiliares.conv@educacion.gob.es",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Spain's Ministry of Education language-assistant programme (Acción Educativa Exterior). NOT currently open to South African passport holders — SA does not appear on the bilateral eligibility list for the 2025–2026 call. Listed for transparency only; SA candidates must use private placement (CIEE, SPEAK) for Spain.",
  },
  {
    name: "EPIK (English Program in Korea)",
    categories: ["TEFL"],
    type: "Government TEFL programme",
    destinations: ["South Korea"],
    website: "http://www.epik.go.kr/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Korean Ministry of Education programme placing English teachers in public schools across all 17 provinces. SA explicitly eligible (one of seven E-2 visa nationalities). Free to apply directly via epik.go.kr or via official recruiting partners. Pays ₩2.1M–3.0M/month + free housing + flight allowance + severance. Spring (March) and Fall (September) intakes; apply ~6 months ahead.",
  },
  {
    name: "GEPIK (Gyeonggi English Program)",
    categories: ["TEFL"],
    type: "Government TEFL programme (regional)",
    destinations: ["South Korea"],
    website: "https://www.goe.go.kr/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Gyeonggi Province (greater Seoul) public-school placement; absorbed into EPIK in 2016 — apply via EPIK and indicate Gyeonggi as preference. Possible rural allowances. No separate application channel.",
  },
  {
    name: "JET Programme (Japan)",
    categories: ["TEFL"],
    type: "Government TEFL programme",
    destinations: ["Japan"],
    website: "https://jetprogramme.org/",
    email: "",
    phone: "+27 12 452 1500",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Bilateral programme of MIC, MOFA, MEXT, CLAIR. SA citizens apply exclusively through Embassy of Japan in SA (259 Baines Street, Groenkloof, Pretoria). Free application, formal interview at embassy. Annual cycle: opens ~August, deadline mid-October. ¥3,360,000/year (Year 1) ≈ ¥280,000/month + return flights + health insurance.",
  },
  {
    name: "Korvia Consulting",
    categories: ["TEFL"],
    type: "TEFL placement (official EPIK partner)",
    destinations: ["South Korea"],
    website: "https://www.korvia.com/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "EPIK's exclusive official recruiting partner since 2008. Korea-based; FREE to candidates (revenue from EPIK partnership, not application fees). End-to-end EPIK support: document review, interview prep, school matching, visa coordination. Treat any SA-based agent claiming 'EPIK partnership' that charges a fee as fraudulent — verify against EPIK's published recruiter list at epik.go.kr.",
  },
  {
    name: "SMOE (Seoul Metropolitan Office of Education)",
    categories: ["TEFL"],
    type: "Government TEFL programme (regional)",
    destinations: ["South Korea"],
    website: "https://smoe.sen.go.kr/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Seoul placements for EPIK; absorbed into EPIK system — apply via EPIK and indicate Seoul preference. Separate Seoul-specific salary scale may apply. No standalone SMOE application channel.",
  },
  {
    name: "Teach Away",
    categories: ["TEFL"],
    type: "TEFL placement agency",
    destinations: ["UAE", "Saudi Arabia", "China", "South Korea", "Japan", "Vietnam", "International schools (global)"],
    website: "https://www.teachaway.com/",
    email: "info@teachaway.com",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Toronto-based global teacher recruiter (TEFL + qualified-teacher routes). Strong UAE / Saudi Arabia / China presence; partners with school groups including ADEK (Abu Dhabi) and major international school chains. Free to teachers (employer-pays). Operates a public salary-and-benefits database useful for benchmarking offers.",
  },
  {
    name: "The TEFL Org",
    categories: ["TEFL"],
    type: "TEFL training + jobs board",
    destinations: ["Global", "Saudi Arabia", "UAE", "South Korea", "Vietnam"],
    website: "https://www.tefl.org/",
    email: "info@tefl.org",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "UK-based TEFL training provider (Ofqual-regulated Level 5 Diploma + 120-hr courses) with a jobs board and country-specific destination guides. Strong on regulatory accuracy. Not a placement agency in the classic sense — sells courses + signposts jobs — but a relevant outreach target because SA candidates frequently use TEFL Org as their first port of call.",
  },
  {
    name: "CIEE",
    categories: ["TEFL"],
    type: "TEFL programme provider",
    destinations: ["Spain", "China", "South Korea", "Thailand", "Vietnam"],
    website: "https://www.ciee.org/go-abroad/work/teach-english-abroad",
    email: "contact@ciee.org",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Council on International Educational Exchange — US-based non-profit running structured Teach Abroad programmes. Materially important for SA candidates targeting Spain (since Auxiliares de Conversación is closed to SA) — CIEE's private Spain teaching programme is the practical alternative. Charges a programme fee; provides placement, training, and in-country support.",
  },
  {
    name: "Footprints Recruiting",
    categories: ["TEFL"],
    type: "TEFL placement agency",
    destinations: ["South Korea", "China", "Vietnam", "Japan"],
    website: "https://www.footprintsrecruiting.com/",
    email: "",
    phone: "+1 604 200 8815",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Vancouver-based TEFL recruiter (since 2003). Strong Korea EPIK channel and China placements. Publishes an SA-specific E-2 visa guide (footprintsrecruiting.com/e2-visa-guide/south-africa). Free to teachers (employer-pays). Contact via form only (no public email surfaced May 2026).",
  },
  {
    name: "International TEFL Academy",
    categories: ["TEFL"],
    type: "TEFL training + placement support",
    destinations: ["Global", "Spain", "China", "South Korea"],
    website: "https://www.internationalteflacademy.com/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Chicago-based TEFL training provider with structured post-graduation placement support across 80+ countries. Mentioned in the TEFL corpus as a legitimate counterpoint to course-provider-upsell scams. Contact via form only (no public email surfaced May 2026).",
  },
  {
    name: "i-to-i TEFL",
    categories: ["TEFL"],
    type: "TEFL training + jobs board",
    destinations: ["Global"],
    website: "https://www.i-to-i.com/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "UK-based TEFL training provider (Ofqual-regulated Level 5 Diploma + online TEFL courses). Operates a jobs board for graduates. Like The TEFL Org, sells courses rather than running placements directly. Contact via form only.",
  },
  {
    name: "Reach to Teach Recruiting",
    categories: ["TEFL"],
    type: "TEFL placement agency",
    destinations: ["Taiwan", "China", "South Korea"],
    website: "https://www.reachtoteachrecruiting.com/",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Specialist Taiwan placement agency (since 2003) — relevant for SA candidates eyeing Taiwan's structured TFETP-adjacent private-school market. Free to teachers (employer-pays). Contact via form only.",
  },
  {
    name: "Cultural Care Au Pair",
    categories: ["Au Pair"],
    type: "USA J-1 designated sponsor",
    destinations: ["USA"],
    website: "https://www.culturalcare.com",
    email: "capetown@culturalcare.com",
    phone: "021 422 0807",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "Largest US au-pair sponsor by volume. US State Department designated J-1 sponsor. Direct SA office at 50 Kloof Street, Gardens, Cape Town. FREE to au pair (host families pay all programme fees). Includes outbound + return flights, medical insurance, 24h emergency line, $500 education allowance. Year-round intakes. Verify designation at j1visa.state.gov/participants/how-to-apply/sponsor-search/.",
  },
  {
    name: "AIFS Au Pair in America",
    categories: ["Au Pair"],
    type: "USA J-1 designated sponsor",
    destinations: ["USA"],
    website: "https://www.aupairinamerica.com",
    email: "info@aupairinamerica.co.za",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "First-designated US J-1 au-pair sponsor (since 1986). SA recruitment via African Ambassadors (Pty) Ltd — Cape Town head office, regional offices nationwide. FREE to au pair. Includes flights, insurance, 24h emergency line, end-of-programme certificate, education allowance.",
  },
  {
    name: "African Ambassadors",
    categories: ["Au Pair"],
    type: "SA-side AIFS partner",
    destinations: ["USA"],
    website: "https://www.aupairinamerica.co.za/",
    email: "info@aupairinamerica.co.za",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "South African private company (Pty Ltd, CIPC-registered) acting as recruitment partner for AIFS Au Pair in America. NOT the legal J-1 sponsor — that role is AIFS. African Ambassadors handles SA-side candidate screening, interview prep, and document support. Cape Town head office; regional offices throughout SA. Revenue from AIFS, not au pair.",
  },
  {
    name: "OVC South Africa",
    categories: ["Au Pair"],
    type: "SA placement partner (USA + NL)",
    destinations: ["USA", "Netherlands"],
    website: "https://www.ovc.co.za/pages/aupair.asp",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "SA's longest-running au-pair placement partner (since 1986). Multi-office presence across SA. Places candidates into USA (via Go Au Pair partnership) and Netherlands. CHARGES SA AU PAIRS A FEE: ~R5,450 admin + R8,500 programme fee — different model from US-sponsor-direct route which is free to au pair. Verify fee structure before signing.",
  },
  {
    name: "AuPairCare",
    categories: ["Au Pair"],
    type: "USA J-1 designated sponsor",
    destinations: ["USA"],
    website: "https://www.aupaircare.com",
    email: "customercare@aupaircare.com",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "US State Department designated J-1 au-pair sponsor. No dedicated SA office — SA candidates apply directly via aupaircare.com. FREE to au pair (competitive host-family pricing). Includes flights, insurance, 24h emergency line, programme academy, education allowance.",
  },
  {
    name: "Go Au Pair",
    categories: ["Au Pair"],
    type: "USA J-1 designated sponsor",
    destinations: ["USA"],
    website: "https://goaupair.com",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "US State Department designated J-1 au-pair sponsor. No dedicated SA office. FREE to au pair (host family pays). Includes flights, health insurance, programme academy, 24h support. SA candidates often reach Go Au Pair via OVC partnership rather than direct application — check whether free direct application is available before paying any SA-side intermediary fee. Form-only contact.",
  },
  {
    name: "EurAuPair Intercultural Child Care Programs",
    categories: ["Au Pair"],
    type: "USA J-1 designated sponsor",
    destinations: ["USA"],
    website: "https://www.euraupair.com",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "US State Department designated J-1 au-pair sponsor. No dedicated SA office. FREE to au pair. Includes outbound + return flights, medical insurance, programme academy, 24h emergency line, education allowance. Form-only contact (no public email surfaced May 2026).",
  },
  {
    name: "GreatAuPair",
    categories: ["Au Pair"],
    type: "USA J-1 designated sponsor + matching platform",
    destinations: ["USA"],
    website: "https://www.greataupair.com",
    email: "",
    phone: "",
    evidence: "confirmed" as Recruiter['evidence'],
    notes: "US State Department designated J-1 au-pair sponsor; also runs an au-pair / host-family matching platform that operates in non-USA destinations. Affordable host-family pricing. FREE to au pair on the J-1 USA programme. WARNING — the matching platform (vs the J-1 programme) carries catfish-host-family risk; SA candidates should verify host families and never send money/passport copies to unverified profiles. Form-only contact.",
  },
];

export const scamPatterns: ScamPattern[] = [
  {
    name: "Canada SAWP Confusion Scam",
    category: "Farming",
    vault: "Closed scheme pitch, Upfront recruitment fee",
    destinations: [],
    channels: ["facebook", "whatsapp", "email", "indeed"],
    typicalFeeZar: "3000–15000",
    reportSa: "SAPS (saps.gov.za); SA Department of Employment and Labour",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Canada SAWP is for Mexico and Caribbean countries only; SA workers are not eligible — but the legitimate Canadian Agricultural Stream via LMIA is open to all nationalities.",
  },
  {
    name: "Fake Australia PALM Placement Scam",
    category: "Farming",
    vault: "Closed scheme pitch",
    destinations: [],
    channels: ["facebook", "whatsapp", "telegram", "indeed", "email", "instagram"],
    typicalFeeZar: "3000–15000",
    reportSa: "SAPS (saps.gov.za); SA Department of Employment and Labour",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Fraudulent recruiters pitch PALM scheme placements to SA workers; PALM is restricted to 9 Pacific nations + Timor-Leste — SA is ineligible by design.",
  },
  {
    name: "Fake NZ RSE Placement Scam",
    category: "Farming",
    vault: "Closed scheme pitch",
    destinations: [],
    channels: ["facebook", "whatsapp", "telegram", "email", "indeed"],
    typicalFeeZar: "3000–12000",
    reportSa: "SAPS (saps.gov.za); SA Department of Employment and Labour",
    reportDestination: "",
    evidence: "confirmed",
    summary: "NZ RSE scheme is Pacific-only; South Africa is ineligible — any RSE placement pitch to a SA worker is fraudulent by design.",
  },
  {
    name: "Fake UK Seasonal Worker Agency Scam",
    category: "Farming",
    vault: "Fake scheme operator, Upfront recruitment fee",
    destinations: [],
    channels: ["facebook", "whatsapp", "indeed", "email", "linkedin"],
    typicalFeeZar: "5000–25000",
    reportSa: "SAPS (saps.gov.za); SA Department of Employment and Labour",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Fraudulent agencies claim to be UK Seasonal Worker scheme operators; only 5 Defra-endorsed operators can issue Certificates of Sponsorship for this route.",
  },
  {
    name: "Guaranteed PR Via Farm Work Pitch",
    category: "Farming",
    vault: "Guaranteed pr claim",
    destinations: [],
    channels: ["facebook", "whatsapp", "telegram", "tiktok", "instagram", "email"],
    typicalFeeZar: "10000–50000",
    reportSa: "SAPS (saps.gov.za); SA Department of Employment and Labour",
    reportDestination: "",
    evidence: "confirmed",
    summary: "UK Seasonal Worker, H-2A, and Canadian SAWP/Agricultural Stream do not provide permanent residency; any PR guarantee via these routes is a misrepresentation used to extract fees.",
  },
  {
    name: "H-2A Worker Recruitment Fee Scam",
    category: "Farming",
    vault: "Upfront recruitment fee",
    destinations: [],
    channels: ["facebook", "whatsapp", "indeed", "email", "telegram"],
    typicalFeeZar: "3000–20000",
    reportSa: "SAPS (saps.gov.za); US Embassy Pretoria (za.usembassy.gov)",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Charging H-2A workers recruitment/placement fees is illegal under 20 CFR §655.135(j)–(k); any recruiter asking SA workers for H-2A placement money is breaking US federal law.",
  },
  {
    name: "Maritime Offshore Fishing Vessel Scam",
    category: "Farming",
    vault: "Fake employer, Upfront recruitment fee",
    destinations: [],
    channels: ["email", "facebook", "whatsapp", "indeed"],
    typicalFeeZar: "5000–30000",
    reportSa: "SAPS (saps.gov.za)",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Fraudulent emails offer employment on Australian cruise ships or fishing vessels to South Africans; victims pay for fake visas or 'foreign worker certificates' and receive nothing.",
  },
  {
    name: "Bogus Canadian Hotel Agency Demanding LMIA Fee from Worker",
    category: "Hospitality",
    vault: "Hospitality",
    destinations: [],
    channels: [],
    typicalFeeZar: "",
    reportSa: "",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Fake Canadian hotel agencies sell LMIA-approved jobs for $25k–$50k — illegal; employer must pay all LMIA costs",
  },
  {
    name: "Cruise Ship / Yacht Hospitality Scam with Maritime Visa and Uniform Deposit",
    category: "Hospitality",
    vault: "Hospitality",
    destinations: [],
    channels: [],
    typicalFeeZar: "",
    reportSa: "",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Fake cruise recruiter demands upfront 'maritime visa' and uniform deposit — MLC 2006 prohibits all advance seafarer fees",
  },
  {
    name: "Fake UAE Hotel Job with Upfront Registration Fee",
    category: "Hospitality",
    vault: "Hospitality",
    destinations: [],
    channels: [],
    typicalFeeZar: "",
    reportSa: "",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Fake UAE hospitality job ads demand R3k–R10k upfront for visa/registration — illegal under MOHRE Resolution 47/2022",
  },
  {
    name: "Fake UK Certificate of Sponsorship for Sale",
    category: "Hospitality",
    vault: "Hospitality",
    destinations: [],
    channels: [],
    typicalFeeZar: "",
    reportSa: "",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Fraudulent UK CoS sold for £3k–£8k on WhatsApp/Telegram; criminal offence since Feb 2026 to advertise",
  },
  {
    name: "Fake UK Chef Placement After 22 July 2025",
    category: "Hospitality",
    vault: "Hospitality",
    destinations: [],
    channels: [],
    typicalFeeZar: "",
    reportSa: "",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Post-July 2025 UK chef/waiter Skilled Worker visa no longer exists; ads for it are fake or fraudulent",
  },
  {
    name: "Romance and Dating-App Dubai Hotel Job Scam",
    category: "Hospitality",
    vault: "Hospitality",
    destinations: [],
    channels: [],
    typicalFeeZar: "",
    reportSa: "",
    reportDestination: "",
    evidence: "alleged",
    summary: "Romance scam combined with Dubai hotel job offer; 'fiancé in Dubai' pattern combines emotional manipulation + visa fraud",
  },
  {
    name: "Tourist Visa and Find a Job in Dubai Pitch",
    category: "Hospitality",
    vault: "Hospitality",
    destinations: [],
    channels: [],
    typicalFeeZar: "",
    reportSa: "",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Recruiters tell SA hospitality workers to fly Dubai on tourist visa and job-hunt — illegal; deportation + AED 200/day fine",
  },
  {
    name: "Bogus SA Nursing College",
    category: "Healthcare",
    vault: "Fake programme",
    destinations: ["UK", "Australia", "Ireland"],
    channels: ["facebook", "whatsapp", "in_person"],
    typicalFeeZar: "10000–50000 (\\\"tuition\\\" for a non-existent programme)",
    reportSa: "SAPS (10111); Presidential Hotline (17737); Department of Health provincial offices; SANC (sanc.co.za)",
    reportDestination: "Action Fraud UK (0300 123 2040) if abroad-bound; NMC (020 7637 7181)",
    evidence: "confirmed",
    summary: "SA-based fake nursing colleges charge tuition and issue worthless 'diplomas' — victims left without valid SANC credentials and unplaceable abroad.",
  },
  {
    name: "Contract Trap and Bonded Labour",
    category: "Healthcare",
    vault: "Fake agency",
    destinations: ["UK", "Australia"],
    channels: ["whatsapp", "linkedin", "email", "in_person"],
    typicalFeeZar: "0 upfront — trap is enforced after arrival via contract clawback (R100000–R500000)",
    reportSa: "SA Fraud Prevention Service (0800 222 999); Department of Employment and Labour (0800 220 818)",
    reportDestination: "Gangmaster and Labour Abuse Authority UK (gla.gov.uk / 0800 432 0804); Fair Work Ombudsman AUS (fairwork.gov.au)",
    evidence: "confirmed",
    summary: "Agencies insert disproportionate repayment clauses trapping nurses in UK/AUS care homes; leaving triggers R200k+ clawback demands.",
  },
  {
    name: "Fake HSE Employer Ireland",
    category: "Healthcare",
    vault: "Fake employer",
    destinations: ["Ireland"],
    channels: ["whatsapp", "facebook", "linkedin", "zoom_teams", "email"],
    typicalFeeZar: "45000–165000 (€2300–€11000 range documented)",
    reportSa: "SAPS (10111); nearest Irish embassy (Pretoria)",
    reportDestination: "An Garda Síochána (garda.ie); NMBI (nmbi.ie); Migrant Nurses Ireland (MNI)",
    evidence: "confirmed",
    summary: "Operators clone HSE letterheads to sell fake Ireland nursing jobs — nurses pay €4k–€11k, receive genuine permits, arrive jobless.",
  },
  {
    name: "Fake NHS Trust Recruitment",
    category: "Healthcare",
    vault: "Fake employer",
    destinations: ["UK"],
    channels: ["facebook", "whatsapp", "linkedin", "indeed", "email"],
    typicalFeeZar: "5000–50000 (visa/relocation advance fees)",
    reportSa: "SAPS (10111 or saps.gov.za); South African Fraud Prevention Service (0800 222 999)",
    reportDestination: "Action Fraud (actionfraud.police.uk / 0300 123 2040); NHS Counter Fraud Authority (cfa.nhs.uk)",
    evidence: "confirmed",
    summary: "Scammers clone NHS trust branding to recruit SA nurses with fake job offers, extracting visa and relocation fees.",
  },
  {
    name: "Fake NMC Registration Agent",
    category: "Healthcare",
    vault: "Fake registration agent",
    destinations: ["UK"],
    channels: ["whatsapp", "email", "facebook", "phone"],
    typicalFeeZar: "3000–20000 (\\\"processing\\\" or \\\"fast-track\\\" fees)",
    reportSa: "SAPS (10111); South African Fraud Prevention Service (0800 222 999)",
    reportDestination: "NMC directly: 020 7637 7181; Action Fraud: 0300 123 2040",
    evidence: "confirmed",
    summary: "Fraudsters pose as NMC agents charging fees to 'fast-track' registration — NMC never charges via phone or third parties.",
  },
  {
    name: "Nursing Qualification Fraud",
    category: "Healthcare",
    vault: "Qualification fraud",
    destinations: ["UK", "Australia", "Ireland", "USA"],
    channels: ["whatsapp", "facebook", "email", "in_person"],
    typicalFeeZar: "5000–50000 (per fraudulent document set)",
    reportSa: "SAPS (10111); SAQA fraud hotline; SANC (sanc.co.za); SA Fraud Prevention Service (0800 222 999)",
    reportDestination: "Action Fraud UK (0300 123 2040); AHPRA Australia (ahpra.gov.au/Complaints); NMC UK (020 7637 7181)",
    evidence: "confirmed",
    summary: "Fraudsters sell fake SA nursing transcripts, SANC certificates, or university diplomas to nurses and would-be nurses seeking work abroad.",
  },
  {
    name: "Unregistered Nursing Agency",
    category: "Healthcare",
    vault: "Fake agency",
    destinations: ["UK", "Australia", "Ireland"],
    channels: ["facebook", "whatsapp", "linkedin", "indeed", "email"],
    typicalFeeZar: "5000–30000 (registration, placement, or admin fees)",
    reportSa: "SAPS (10111); Department of Employment and Labour (0800 220 818 / labour.gov.za)",
    reportDestination: "Action Fraud UK: 0300 123 2040; AHPRA Australia: ahpra.gov.au/Complaints",
    evidence: "confirmed",
    summary: "SA-based unregistered agencies collect fees from nurses for UK/AUS/IRE placement with no legitimate employer relationships.",
  },
  {
    name: "Upfront OSCE CBT Guarantee Fee Scam",
    category: "Healthcare",
    vault: "Upfront exam fee",
    destinations: ["UK"],
    channels: ["facebook", "whatsapp", "email", "linkedin"],
    typicalFeeZar: "5000–30000 (\\\"guarantee\\\" or \\\"preparation\\\" fees)",
    reportSa: "SAPS (10111); SA Fraud Prevention Service (0800 222 999)",
    reportDestination: "Action Fraud (0300 123 2040 / actionfraud.police.uk); NMC: 020 7637 7181",
    evidence: "confirmed",
    summary: "Fraudsters charge SA nurses upfront fees to 'guarantee' OSCE/CBT pass — no entity can legally guarantee exam outcomes.",
  },
  {
    name: "Canada IEC Fake Recognized Organisation Scam",
    category: "Seasonal",
    vault: "Fake sponsor agency, Upfront fee, Guaranteed placement",
    destinations: [],
    channels: ["facebook", "whatsapp", "linkedin", "email"],
    typicalFeeZar: "R28000–R37000 (equiv. CAD 2000 / USD 1500 — typical reported IEC employment scam loss)",
    reportSa: "SAPS (saps.gov.za); SA Dept of Employment and Labour",
    reportDestination: "",
    evidence: "alleged",
    summary: "Scammers pose as mandatory IEC Recognized Organisations to charge SA-eligible youth upfront fees — ROs are in fact optional intermediaries.",
  },
  {
    name: "Fake J1 Placement Agency Scam",
    category: "Seasonal",
    vault: "Fake sponsor agency, Upfront fee, Guaranteed placement",
    destinations: [],
    channels: ["facebook", "whatsapp", "linkedin", "indeed", "email", "instagram"],
    typicalFeeZar: "R2000–R15000 (varies; sometimes USD 200–500 framed as 'admin' or 'processing' fee)",
    reportSa: "SAPS (saps.gov.za); SA Dept of Employment and Labour",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Fraudulent agencies charge SA students upfront fees to 'secure' J1 Summer Work Travel placements, falsely claiming to issue DS-2019 forms.",
  },
  {
    name: "Fake UK Seasonal Recruiter Scam",
    category: "Seasonal",
    vault: "Fake sponsor agency, Fake visa service, Upfront fee",
    destinations: [],
    channels: ["facebook", "whatsapp", "linkedin", "instagram", "email"],
    typicalFeeZar: "R3000–R12000 (framed as 'YMS application assistance', 'visa fast-track', or 'slot reservation')",
    reportSa: "SAPS (saps.gov.za); SA Dept of Employment and Labour",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Fraudulent services charge SA applicants for 'assisted' UK Youth Mobility Scheme applications — a process that requires no intermediary and cannot be fast-tracked.",
  },
  {
    name: "Guaranteed Disney Resort Job Scam",
    category: "Seasonal",
    vault: "Fake employer, Upfront fee, Guaranteed placement",
    destinations: [],
    channels: ["facebook", "whatsapp", "instagram", "indeed", "email"],
    typicalFeeZar: "R1500–R10000 (framed as 'processing' or 'placement guarantee' fee)",
    reportSa: "SAPS (saps.gov.za); SA Dept of Employment and Labour",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Scammers impersonate Disney hiring to offer 'guaranteed' USA seasonal jobs, collecting fees and personal data from SA students.",
  },
  {
    name: "Advance Fee Fraud",
    category: "General",
    vault: "Advance fee",
    destinations: [],
    channels: ["email", "whatsapp", "facebook", "linkedin", "in_person"],
    typicalFeeZar: "R500–R10000+ (escalating through multiple invented obstacles)",
    reportSa: "SAPS Commercial Crime Branch: hq.commercial@saps.org.za; SAPS Cybercrime Division",
    reportDestination: "Action Fraud UK (actionfraud.police.uk); FTC USA (ReportFraud.ftc.gov); US Secret Service (419.fcd@usss.treas.gov)",
    evidence: "confirmed",
    summary: "Repeated fee extraction through invented obstacles before a promised job, visa, or payment that never materialises.",
  },
  {
    name: "Fake Job Offer Scam",
    category: "General",
    vault: "Job offer",
    destinations: [],
    channels: ["whatsapp", "facebook", "email", "in_person", "indeed", "gumtree"],
    typicalFeeZar: "R150–R2000 (registration, background check, uniform, admin)",
    reportSa: "SAPS Cybercrime Division; Department of Employment and Labour (086 6002 2194); SAFPS",
    reportDestination: "Action Fraud UK; ACCC Australia; US FTC (ReportFraud.ftc.gov)",
    evidence: "confirmed",
    summary: "Fee-based fake job offer exploiting SA's 31.9% unemployment rate via WhatsApp, Facebook, and cloned websites.",
  },
  {
    name: "Fake Recruitment Agency",
    category: "General",
    vault: "Job offer",
    destinations: [],
    channels: ["email", "facebook", "indeed", "in_person", "fax", "whatsapp"],
    typicalFeeZar: "R200–R3000 (placement, criminal clearance, insurance enrollment, fax premium rate)",
    reportSa: "SAPS; Department of Employment and Labour (086 6002 2194); CIPC",
    reportDestination: "Action Fraud UK; ACCC Australia",
    evidence: "confirmed",
    summary: "Illegally operating recruiters collect fees from SA job seekers for placements that don't materialise.",
  },
  {
    name: "Identity Document Fraud",
    category: "General",
    vault: "Identity",
    destinations: [],
    channels: ["email", "whatsapp", "in_person", "zoom_teams", "linkedin"],
    typicalFeeZar: "Not applicable — value extracted is the identity itself, worth thousands in downstream fraud",
    reportSa: "SAPS Cybercrime; SAFPS (011 867 2234 / protection@safps.org.za); credit bureaux (TransUnion, Experian)",
    reportDestination: "Action Fraud UK; FTC USA (IdentityTheft.gov); ACCC Australia (scamwatch.gov.au)",
    evidence: "confirmed",
    summary: "Scammers harvest SA victims' ID, passport, or bank details during fake job or visa processes — enabling downstream financial crime.",
  },
  {
    name: "LinkedIn Recruiter Impersonation",
    category: "General",
    vault: "Impersonation",
    destinations: [],
    channels: ["linkedin", "email", "indeed", "zoom_teams"],
    typicalFeeZar: "R1500–R25000 (equipment invoice or identity theft value)",
    reportSa: "SAPS Cybercrime Division; SAFPS",
    reportDestination: "Action Fraud UK (actionfraud.police.uk); FTC USA (ReportFraud.ftc.gov); LinkedIn Safety (linkedin.com/help)",
    evidence: "confirmed",
    summary: "Scammers clone real LinkedIn recruiter profiles to deliver fake job offers and harvest money or identity data.",
  },
  {
    name: "Phantom Interview Scam",
    category: "General",
    vault: "Phantom interview",
    destinations: [],
    channels: ["zoom_teams", "linkedin", "indeed", "email", "whatsapp"],
    typicalFeeZar: "R1000–R20000 (fake equipment deposit or fake check reimbursement)",
    reportSa: "SAPS Cybercrime Division; SAFPS",
    reportDestination: "Action Fraud UK (actionfraud.police.uk); FTC USA (ReportFraud.ftc.gov); ACCC Australia (scamwatch.gov.au)",
    evidence: "confirmed",
    summary: "Scammer conducts a fake job interview via Zoom or Teams chat (no video), then extracts money or identity data.",
  },
  {
    name: "Scam Compound Operator",
    category: "General",
    vault: "General",
    destinations: [],
    channels: [],
    typicalFeeZar: "",
    reportSa: "",
    reportDestination: "",
    evidence: "confirmed",
    summary: "Transnational criminal syndicates trafficking South Africans into forced online fraud operations in Myanmar, Cambodia, and Laos.",
  },
  {
    name: "Upfront Visa Fee Fraud",
    category: "General",
    vault: "Visa fee",
    destinations: [],
    channels: ["email", "whatsapp", "facebook", "linkedin", "in_person"],
    typicalFeeZar: "R500–R15000 (visa processing, work permit, medical, flight deposit)",
    reportSa: "SAPS Cybercrime Division; DIRCO; Department of Employment and Labour (086 6002 2194)",
    reportDestination: "Australian High Commission Pretoria (+27 12 423 6000); UK Home Office (gov.uk/report-immigration-fraud); Action Fraud UK (actionfraud.police.uk)",
    evidence: "confirmed",
    summary: "Scammers charge SA job seekers upfront for fraudulent visa or work permit processing — fees rarely below R1000.",
  },
  {
    name: "WhatsApp Global Group Placement Scam",
    category: "General",
    vault: "Job offer",
    destinations: [],
    channels: ["whatsapp", "linkedin", "facebook"],
    typicalFeeZar: "R300–R5000 (committal/activation fee to secure placement)",
    reportSa: "SAPS Cybercrime Division; report group to WhatsApp (Settings → Report)",
    reportDestination: "Action Fraud UK (actionfraud.police.uk); FTC USA (ReportFraud.ftc.gov)",
    evidence: "confirmed",
    summary: "Invitation-only WhatsApp group claiming to place members in overseas jobs; admin-only permissions trap victims and prevent warnings.",
  },
  {
    name: "Australian Teacher Registration Scam",
    category: "Teaching",
    vault: "Fake agency, Upfront placement fee, Qualification misrepresentation",
    destinations: ["Australia"],
    channels: ["facebook", "whatsapp", "linkedin", "email"],
    typicalFeeZar: "45000",
    reportSa: "SAPS (saps.gov.za); National Consumer Commission (ncc.gov.za)",
    reportDestination: "Australian Competition and Consumer Commission/Scamwatch (scamwatch.gov.au); Fair Work Ombudsman (fairwork.gov.au)",
    evidence: "alleged",
    summary: "Fraudulent agents charge SA teachers for 'bundled' AITSL + state registration + visa packages; all three are applied to separately and directly — no agent is needed.",
  },
  {
    name: "Fake DBS Check Fee Scam",
    category: "Teaching",
    vault: "Upfront placement fee, Fake employer",
    destinations: ["UK"],
    channels: ["email", "whatsapp", "linkedin", "indeed"],
    typicalFeeZar: "5000",
    reportSa: "SAPS (saps.gov.za)",
    reportDestination: "Action Fraud (actionfraud.police.uk); DBS directly (gov.uk/find-dbs-umbrella-body)",
    evidence: "confirmed",
    summary: "Fraudsters charge teachers upfront for fake 'Enhanced DBS checks' during recruitment; real DBS checks cost £49.50 max and are not demanded before a genuine job offer.",
  },
  {
    name: "Fake Guaranteed UK Placement Agency",
    category: "Teaching",
    vault: "Fake agency, Upfront placement fee",
    destinations: ["UK", "Australia"],
    channels: ["facebook", "whatsapp", "linkedin", "indeed", "email", "zoom_teams"],
    typicalFeeZar: "35000",
    reportSa: "SAPS (saps.gov.za); National Consumer Commission (ncc.gov.za); labour.gov.za",
    reportDestination: "Action Fraud (actionfraud.police.uk); Recruitment and Employment Confederation (rec.uk.com) for UK; Fair Work Ombudsman (fairwork.gov.au) for Australia",
    evidence: "confirmed",
    summary: "Fraudulent agencies charge SA teachers upfront 'placement', 'visa processing', or 'shortlisting' fees; legitimate UK teacher recruiters charge only the hiring school.",
  },
  {
    name: "Fraudulent Certificate of Sponsorship Seller",
    category: "Teaching",
    vault: "Fake cos seller",
    destinations: ["UK"],
    channels: ["facebook", "whatsapp", "linkedin", "email", "zoom_teams"],
    typicalFeeZar: "200000",
    reportSa: "SAPS (saps.gov.za); labour.gov.za",
    reportDestination: "Action Fraud (actionfraud.police.uk); Home Office immigration crime (gov.uk/report-immigration-crime)",
    evidence: "confirmed",
    summary: "Scam selling fake or invalid UK Certificates of Sponsorship to teachers/workers for fees up to £42,000; CoS is always free to candidates.",
  },
  {
    name: "QTS Misrepresentation Scam",
    category: "Teaching",
    vault: "Qualification misrepresentation",
    destinations: ["UK"],
    channels: ["facebook", "whatsapp", "linkedin", "email"],
    typicalFeeZar: "15000",
    reportSa: "SAPS (saps.gov.za); consumer complaints to National Consumer Commission (ncc.gov.za)",
    reportDestination: "Action Fraud (actionfraud.police.uk); DfE Teaching Regulation Agency (gov.uk/guidance/teacher-misconduct-regulating-the-teaching-profession)",
    evidence: "confirmed",
    summary: "Agents falsely claim all SA teachers get free automatic QTS regardless of subject, then charge for 'processing' a qualification that may not be obtainable.",
  },
  {
    name: "SACE Document Harvesting Scam",
    category: "Teaching",
    vault: "Document harvesting",
    destinations: ["UK", "Australia", "UAE", "General"],
    channels: ["whatsapp", "facebook", "email", "in_person"],
    typicalFeeZar: "2800",
    reportSa: "SAPS (saps.gov.za); SACE directly (sace.org.za); WCED/provincial education departments",
    reportDestination: "Action Fraud (actionfraud.police.uk) for UK-directed variants",
    evidence: "confirmed",
    summary: "Scammers impersonate SACE officials or overseas recruiters to harvest original SACE certificates, police clearances, and passports before any legitimate employment exists.",
  },
  {
    name: "School Impersonation Scam",
    category: "Teaching",
    vault: "Fake employer",
    destinations: ["UK", "Australia", "General"],
    channels: ["email", "linkedin", "indeed", "facebook", "whatsapp"],
    typicalFeeZar: "25000",
    reportSa: "SAPS (saps.gov.za)",
    reportDestination: "Action Fraud (actionfraud.police.uk); reporting to the real school whose name was impersonated",
    evidence: "confirmed",
    summary: "Scammers use near-identical names or stolen branding of real UK schools to issue fake job offers and collect fees or documents from SA teachers.",
  },
  {
    name: "Australian FIFO Mining Placement Scam",
    category: "Trades",
    vault: "Guaranteed placement, Upfront fee, Maritime oil rig, Fifo mining, Fake employer",
    destinations: ["australia"],
    channels: ["facebook", "whatsapp", "telegram", "instagram", "indeed", "email", "recruitment_agency"],
    typicalFeeZar: "50000",
    reportSa: "SAPS (saps.gov.za); Australian High Commission Pretoria (southafrica.embassy.gov.au)",
    reportDestination: "Department of Home Affairs — visa fraud reporting (homeaffairs.gov.au); Border Watch Line",
    evidence: "confirmed",
    summary: "Fake recruiters offer SA tradespeople FIFO/mining/oil rig placements in Australia, bypassing TRA assessment and SBS requirements.",
  },
  {
    name: "Fake Canadian Trades Visa Pipeline",
    category: "Trades",
    vault: "Fake pnp nomination, Upfront fee, Guaranteed placement, Fake immigration adviser",
    destinations: ["canada"],
    channels: ["facebook", "whatsapp", "telegram", "tiktok", "youtube", "instagram"],
    typicalFeeZar: "40000",
    reportSa: "SAPS (saps.gov.za); Canadian High Commission Pretoria",
    reportDestination: "Canadian Anti-Fraud Centre (CAFC) — antifraudcentre-centreantifraude.ca; IRCC fraud reporting",
    evidence: "confirmed",
    summary: "Operators on Facebook/TikTok/Telegram sell fake 'guaranteed PNP nominations' to SA tradespeople; PNPs are issued by provinces, not agents.",
  },
  {
    name: "Fake New Zealand Trades Placement",
    category: "Trades",
    vault: "Fake employer, Upfront fee, Guaranteed placement, Identity theft",
    destinations: ["new_zealand"],
    channels: ["facebook", "whatsapp", "email", "indeed", "recruitment_agency"],
    typicalFeeZar: "30000",
    reportSa: "SAPS (saps.gov.za); NZ High Commission Pretoria",
    reportDestination: "Immigration NZ fraud reporting (immigration.govt.nz); New Zealand Police",
    evidence: "confirmed",
    summary: "Fake NZ employer offers targeting SA tradespeople exploit AEWV system; company absent from Accredited Employer list = definitive fraud indicator.",
  },
  {
    name: "Fake UAE Trades Placement",
    category: "Trades",
    vault: "Fake employer, Upfront fee, Guaranteed placement, Identity theft",
    destinations: ["uae"],
    channels: ["facebook", "whatsapp", "telegram", "instagram", "indeed", "email"],
    typicalFeeZar: "25000",
    reportSa: "SAPS (saps.gov.za); UAE Embassy Pretoria",
    reportDestination: "MOHRE — ask@mohre.gov.ae / +971 6802 7666; Dubai GDRFA; ICP eChannels",
    evidence: "confirmed",
    summary: "Fake UAE construction/trades offers target SA workers with upfront fee demands; MOHRE warns all genuine offers must be issued through the ministry system.",
  },
  {
    name: "Fake UK Certificate of Sponsorship Scam",
    category: "Trades",
    vault: "Fake cos, Upfront fee, Guaranteed placement",
    destinations: ["uk"],
    channels: ["facebook", "whatsapp", "telegram", "tiktok", "instagram", "email", "website", "recruitment_agency"],
    typicalFeeZar: "230000",
    reportSa: "SAPS (saps.gov.za); SA Department of Employment and Labour",
    reportDestination: "Action Fraud (actionfraud.police.uk); Home Office immigration enforcement",
    evidence: "confirmed",
    summary: "Agents sell fake or invalid UK CoS documents to SA tradespeople for £10k–£35k; only Licensed Sponsors can issue CoS.",
  },
  {
    name: "Fake UK Competence Card Services",
    category: "Trades",
    vault: "Fake competence card, Upfront fee",
    destinations: ["uk"],
    channels: ["facebook", "instagram", "tiktok", "twitter", "whatsapp", "telegram"],
    typicalFeeZar: "3000",
    reportSa: "SAPS (saps.gov.za)",
    reportDestination: "CSCS — intel@cscs.co.uk; JIB — feedback@ecscard.org.uk; Police",
    evidence: "confirmed",
    summary: "Operators sell fake pre-arrival CSCS/ECS/JIB competence cards on social media; real cards require UK-assessed qualifications.",
  },
  {
    name: "Fake EPIK / SMOE / JET Recruiter Scam",
    category: "TEFL",
    vault: "Fake programme impersonator, Fake recruiter",
    destinations: ["korea", "japan"],
    channels: ["facebook", "whatsapp", "linkedin", "email", "instagram"],
    typicalFeeZar: "5000–20000",
    reportSa: "SAPS (saps.gov.za); Department of Employment and Labour (Employment Services Act); EPIK directly at epik.go.kr",
    reportDestination: "EPIK Office in Korea; Embassy of Japan in SA for JET; Korean Embassy in SA for E-2 visa fraud",
    evidence: "confirmed",
    summary: "SA-based agents impersonate EPIK / SMOE / JET partnership and charge R5k–20k for placements that are free via official channels. EPIK's real recruiter list is published at epik.go.kr (Korvia is the only confirmed official partner). JET applications go directly to the Embassy of Japan in Pretoria — no third-party recruiter has any role.",
  },
  {
    name: "Guaranteed Placement Package Scam (TEFL)",
    category: "TEFL",
    vault: "Guaranteed placement, Fake recruiter",
    destinations: ["korea", "japan", "china", "vietnam", "uae", "saudi", "spain"],
    channels: ["facebook", "whatsapp", "linkedin", "indeed", "email", "tefl_course_provider_upsell"],
    typicalFeeZar: "5000–30000",
    reportSa: "SAPS; Dept of Employment and Labour (Employment Services Act); SAFPS (safps.org.za); CIPC (cipc.co.za)",
    reportDestination: "Destination embassy in SA; EPIK directly if Korea-related",
    evidence: "confirmed",
    summary: "SA placement agents sell R5k–30k 'guaranteed teaching position abroad' packages. For EPIK, JET, and most mainstream TEFL routes, direct application is free; SA agents not on official recruiter lists are selling CV-forwarding only. Course-provider variant bundles unaccredited online TEFL with 'placement guarantee' — both worthless.",
  },
  {
    name: "Mid-Contract Chinese Private School Closure",
    category: "TEFL",
    vault: "Mid-contract closure",
    destinations: ["china"],
    channels: ["linkedin", "indeed", "email", "in_person"],
    typicalFeeZar: "0",
    reportSa: "DIRCO (dirco.gov.za); SA Embassy in Beijing/Shanghai/Guangzhou",
    reportDestination: "China MOST Foreigner Work Permit portal (fuwu.most.gov.cn); local labour bureau",
    evidence: "confirmed",
    summary: "China's Double Reduction Policy (July 2021) collapsed the private K–12 English tutoring sector; foreign teachers are still being recruited to non-viable academies that close mid-contract with unpaid salary and no visa-change support. Vet any China private-sector role against fuwu.most.gov.cn and gsxt.gov.cn before signing. Public schools and licensed international schools are materially safer.",
  },
  {
    name: "Passport Holding on Arrival",
    category: "TEFL",
    vault: "Passport confiscation, Trafficking-risk",
    destinations: ["china", "vietnam", "cambodia", "thailand", "uae", "saudi"],
    channels: ["linkedin", "indeed", "email", "in_person"],
    typicalFeeZar: "0",
    reportSa: "DIRCO (dirco.gov.za) — consular support; SAPS for document theft; SA Embassy/Consulate in destination",
    reportDestination: "Local police; destination labour authority (MOHRE UAE / HRSD Saudi / MoLISA Vietnam); SA Embassy",
    evidence: "confirmed",
    summary: "Lower-tier private academies in China, Vietnam, Cambodia, Thailand and parts of the Gulf demand passports on arrival 'for work permit processing' and refuse to return them. Legitimate work permit lodgement returns the passport within days with a receipt. Indefinite holding is a trafficking-precursor red flag — get help from the SA Embassy immediately.",
  },
  {
    name: "Unaccredited TEFL Certificate Scam",
    category: "TEFL",
    vault: "Unaccredited certificate, Qualification fraud",
    destinations: ["vietnam", "china", "uae", "saudi", "korea", "global"],
    channels: ["facebook", "linkedin", "email", "tefl_course_provider_upsell", "indeed"],
    typicalFeeZar: "3000–15000",
    reportSa: "National Consumer Commission (misleading marketing); SAFPS (safps.org.za)",
    reportDestination: "Cambridge Assessment English (false CELTA claims); Trinity College London (false CertTESOL); Ofqual (false regulatory claims)",
    evidence: "confirmed",
    summary: "SA candidates pay R3k–15k for online TEFL courses with vague 'Ofqual-regulated' or 'internationally recognised' claims, then have certificates rejected at visa stage in Vietnam (Decree 219/2025/ND-CP), the UAE, Saudi Arabia, and Korean hagwons. Verify any TEFL cert against the awarding body's live register: Cambridge for CELTA, Trinity for CertTESOL, Ofqual for Level 5 diplomas (with the awarding-body name + qualification number, not just 'Ofqual-regulated').",
  },
  {
    name: "Upfront Visa Processing Fee Scam",
    category: "TEFL",
    vault: "Upfront visa fee, Fake recruiter",
    destinations: ["uae", "saudi", "vietnam", "china"],
    channels: ["email", "indeed", "linkedin", "facebook"],
    typicalFeeZar: "3600–14000",
    reportSa: "SAPS (saps.gov.za); SAFPS (safps.org.za)",
    reportDestination: "UAE: MOHRE (mohre.gov.ae) + AMER centres; Saudi: HRSD (hrsd.gov.sa) + Qiwa (qiwa.sa); Vietnam Ministry of Labour",
    evidence: "confirmed",
    summary: "Fantasy Gulf job offer (e.g. $4,800/month tax-free, free 3-bed apartment, free family flights), accepted after a superficial Q&A, then payment of $200–$750 'visa processing fee' via Western Union to a 'travel agency'. Active continuously since 2018; documented variant: iEnglish Language Institute Dubai (alias names: Rashid, Wison, Wilson, Rubaj). Real Gulf TEFL salaries top out around R60k–R90k/month — anything wildly above that is a scam.",
  },
  {
    name: "Fake Guaranteed Placement SA Recruiter (Au Pair)",
    category: "Au Pair",
    vault: "Fake recruiter, Guaranteed placement, Upfront fee",
    destinations: ["usa", "germany", "netherlands", "uk", "australia"],
    channels: ["whatsapp", "facebook", "instagram", "tiktok", "sa_recruiter_office"],
    typicalFeeZar: "5000–30000",
    reportSa: "SAPS; Dept of Employment and Labour (fraud@labour.gov.za, 08600 22 194); SAFPS (safps.org.za); CIPC company verification (cipc.co.za)",
    reportDestination: "US State Dept Office of Designation (jvisas@state.gov) if USA-bound; IND if NL-bound",
    evidence: "confirmed",
    summary: "SA-based WhatsApp/Facebook recruiter charges R5k–R30k 'guaranteed placement' fee. Real US J-1 sponsors (Cultural Care, AIFS, AuPairCare, EurAuPair, Go Au Pair, GreatAuPair) charge au pairs nothing — host families cover all programme costs. Any SA-side fee above ~R8,500 (OVC programme model) for USA placement is suspect.",
  },
  {
    name: "Sponsor Impersonation Scam (Au Pair)",
    category: "Au Pair",
    vault: "Sponsor impersonation, Brand fraud",
    destinations: ["usa", "germany", "netherlands", "uk", "australia"],
    channels: ["whatsapp", "email", "instagram", "facebook", "tiktok"],
    typicalFeeZar: "5000–25000",
    reportSa: "SAPS Cybercrime Unit; za.usembassy.gov (for USA sponsor impersonation); SAFPS",
    reportDestination: "Contact the real sponsor directly: Cultural Care, AIFS / Au Pair in America, AuPairCare, EurAuPair, Go Au Pair",
    evidence: "confirmed",
    summary: "Fraudster impersonates a legitimate sponsor brand (Cultural Care, AIFS, AuPairCare etc) via lookalike domains, WhatsApp/Instagram profiles, or unofficial emails. Always cross-check the contact against the official US State Dept sponsor register (j1visa.state.gov/participants/how-to-apply/sponsor-search/) and the sponsor's verified URL before sending any documents or paying any fee.",
  },
  {
    name: "Direct Host-Family Placement Scam (J-1 Bypass)",
    category: "Au Pair",
    vault: "Visa fraud, Direct host-family bypass",
    destinations: ["usa"],
    channels: ["whatsapp", "facebook", "instagram", "aupairworld", "greataupair", "email"],
    typicalFeeZar: "0",
    reportSa: "SAPS Human Trafficking Unit; za.usembassy.gov visa-fraud reporting",
    reportDestination: "US State Dept Office of Designation (jvisas@state.gov); sponsor 24h emergency line; local police",
    evidence: "confirmed",
    summary: "US host family contacts SA candidate directly and offers to skip the J-1 sponsor — promising to bring you in on a B-2 tourist visa and arrange the au-pair work informally. Working as an au pair on a B-2 is illegal visa fraud, deportable, and leaves you with no sponsor protections. Au-pair work in the USA can ONLY be done via one of the State-Department-designated J-1 sponsor agencies.",
  },
  {
    name: "Netherlands Private Au Pair Arrangement (IND Bypass)",
    category: "Au Pair",
    vault: "Unsponsored arrangement, IND bypass",
    destinations: ["netherlands"],
    channels: ["aupairworld", "greataupair", "facebook", "instagram", "whatsapp", "email"],
    typicalFeeZar: "0",
    reportSa: "SA Embassy Netherlands; SAPS",
    reportDestination: "IND (ind.nl/en/contact); Nederlandse Arbeidsinspectie (nlarbeidsinspectie.nl); local police",
    evidence: "confirmed",
    summary: "Host family or agency NOT on IND's public register of recognised au-pair sponsors offers a 'private arrangement'. The residence permit cannot be obtained legally — au pair work in the Netherlands requires an IND-recognised sponsor. Always verify the sponsor at ind.nl/en/public-register-recognised-sponsors before signing or paying anything.",
  },
  {
    name: "Catfish Host Family Profile",
    category: "Au Pair",
    vault: "Identity fraud, Phishing",
    destinations: ["usa", "netherlands", "germany", "uk", "australia"],
    channels: ["aupairworld", "greataupair", "facebook", "instagram", "email"],
    typicalFeeZar: "2000–20000",
    reportSa: "SAPS Cybercrime Unit; SAFPS",
    reportDestination: "AuPairWorld / GreatAuPair fraud reporting; local cybercrime unit",
    evidence: "confirmed",
    summary: "Fake host-family profile on AuPairWorld or GreatAuPair harvests passport copies and personal data, or requests 'flight booking' money via Western Union or e-wallet. Never send passport scans or money to a host family before contracts are countersigned and you have verified them through the sponsor's matching system, not just the platform DM.",
  },
  {
    name: "Au Pair Training Fee Scam",
    category: "Au Pair",
    vault: "Upfront fee, Fake recruiter",
    destinations: ["usa", "germany", "netherlands", "uk", "australia"],
    channels: ["whatsapp", "facebook", "instagram", "sa_recruiter_office"],
    typicalFeeZar: "5000–15000",
    reportSa: "SAPS; Dept of Employment and Labour (fraud@labour.gov.za, 08600 22 194)",
    reportDestination: "N/A — pre-departure scam",
    evidence: "confirmed",
    summary: "SA-based recruiter charges R5k–R15k for an 'au pair training certificate' before placement. Unnecessary — every J-1 sponsor includes a mandatory pre-departure training programme as part of the host-family-paid programme fee. The sponsor's training is required by 22 CFR 62.31; any prior SA-side training is upsell, not a real requirement.",
  },
  {
    name: "Gulf State Au Pair Domestic Worker Scam",
    category: "Au Pair",
    vault: "Trafficking risk, Kafala mislabelling",
    destinations: ["uae", "saudi", "qatar", "kuwait", "bahrain", "oman"],
    channels: ["whatsapp", "facebook", "instagram", "tiktok", "email", "in_person"],
    typicalFeeZar: "0–15000",
    reportSa: "SAPS Human Trafficking Unit; IOM South Africa; DIRCO",
    reportDestination: "IOM emergency line; SA Embassy in Gulf country; local police (limited effectiveness)",
    evidence: "confirmed",
    summary: "Job offers using the 'au pair' label for the Gulf (UAE, Saudi Arabia, Qatar, Kuwait, Bahrain, Oman) are NOT cultural-exchange au-pair roles — there is no au-pair visa category in any Gulf state. These offers are domestic worker positions under the Kafala system, with materially higher trafficking risk: passport confiscation, restricted movement, and limited legal recourse. No legitimate au-pair programme operates in the Gulf.",
  },
  {
    name: "Passport Holding on Arrival (Au Pair)",
    category: "Au Pair",
    vault: "Trafficking indicator, Document servitude",
    destinations: ["usa", "netherlands", "germany", "france", "uk"],
    channels: ["in_person"],
    typicalFeeZar: "0",
    reportSa: "SAPS Human Trafficking Unit; IOM South Africa; SA Embassy in destination",
    reportDestination: "Sponsor 24h emergency line; US State Dept (1-866-283-9090 / jvisas@state.gov); Polaris Project (1-888-373-7888); IND; local police",
    evidence: "confirmed",
    summary: "Host family keeps your passport on arrival 'for safekeeping'. This is illegal in USA/NL/DE/FR and is a primary IOM trafficking indicator. Refuse, report immediately to the sponsor's 24h emergency line, and contact the SA Embassy if not resolved. You are entitled to keep your own passport at all times.",
  },
  {
    name: "Early Departure Forfeiture Clause Exploitation",
    category: "Au Pair",
    vault: "Contract abuse, Rematch denial",
    destinations: ["usa", "netherlands", "germany"],
    channels: ["in_person", "email"],
    typicalFeeZar: "0",
    reportSa: "SA Embassy in destination country",
    reportDestination: "US State Dept Office of Designation (jvisas@state.gov); IND; local labour authority",
    evidence: "confirmed",
    summary: "Host family or unscrupulous operator uses legitimate early-departure forfeiture clauses (you forfeit return flight if you leave early) to threaten au pairs who report abuse or want to rematch. Au pairs are entitled to rematch into a different host family within the same sponsor's programme — the threat of forfeiture should never block this. Report through the sponsor's emergency line first, embassy second.",
  },
  {
    name: "Inflated CDR Writing Service",
    category: "Engineering",
    vault: "Inflated assessment fee, Unnecessary CDR",
    destinations: ["australia"],
    channels: ["facebook", "linkedin", "whatsapp", "email", "website"],
    typicalFeeZar: "5000–25000 (writing fee) + AUD$462 unnecessary EA fee premium",
    reportSa: "SA Department of Employment and Labour (under Employment Services Act); SAPS if fraud",
    reportDestination: "Engineers Australia complaints (engineersaustralia.org.au/about-us/complaints); MARA (portal.mara.gov.au) if a migration agent is involved",
    evidence: "confirmed",
    summary: "Most SA engineers with a 4-year ECSA-accredited BEng qualify for the Engineers Australia Accord pathway (AUD$539) — no Competency Demonstration Report needed. Services that sell CDR writing without first checking your IEA Accord eligibility extract avoidable fees (R5k–R25k+ writing fee PLUS AUD$462 unnecessary fee premium). Check your specific programme on the IEA Qualification Checker (internationalengineeringalliance.org/for-engineers/qualification-checker) before paying anyone.",
  },
  {
    name: "Fake Engineers Australia Fast-Track Intermediary",
    category: "Engineering",
    vault: "Fake intermediary, Guaranteed outcome claim",
    destinations: ["australia"],
    channels: ["facebook", "linkedin", "whatsapp", "email", "website"],
    typicalFeeZar: "2000–15000",
    reportSa: "SAPS; SA Department of Employment and Labour",
    reportDestination: "Engineers Australia complaints (engineersaustralia.org.au/about-us/complaints); MARA (portal.mara.gov.au)",
    evidence: "confirmed",
    summary: "Engineers Australia's legitimate Fast Track add-on (AUD$385) is purchased directly via the EA portal and only accelerates assessor assignment — it does not guarantee a positive outcome. Any third party claiming 'connections' with EA assessors, 'priority processing' outside the EA portal, or a guaranteed approval is misrepresenting the process. Verify any Australian migration agent at portal.mara.gov.au before paying.",
  },
  {
    name: "Maritime / Offshore Engineering Job Offer",
    category: "Engineering",
    vault: "Fake employer, Maritime visa scam",
    destinations: ["australia"],
    channels: ["email", "linkedin", "whatsapp", "facebook"],
    typicalFeeZar: "10000–50000+",
    reportSa: "SAPS; Australian High Commission Pretoria (pret.visas@dfat.gov.au)",
    reportDestination: "AMSA (amsa.gov.au); Scamwatch (scamwatch.gov.au)",
    evidence: "confirmed",
    summary: "Highest-severity engineering scam — formal warnings issued by the Australian High Commission Pretoria and AMSA. Unsolicited 'vessel engineer' job offers request payment for MSIC cards, work permits, or visas; some victims have been physically harmed. AMSA never asks workers to pay money to a third party. Known fake identities include 'Captain Mrs. Mirabelle Mass', 'Mr. Gordon Lawton Llewellyn', 'Mrs Cheryl-Anne Moy', 'Mrs Anne Connell'. Legitimate MSIC applications go only through AusCheck-licensed issuing bodies — never via a job advertiser.",
  },
  {
    name: "Fake Engineering Recruiter Upfront Fee",
    category: "Engineering",
    vault: "Upfront recruitment fee, Impersonation",
    destinations: ["australia", "united kingdom", "canada", "ireland", "new zealand"],
    channels: ["linkedin", "indeed", "facebook", "whatsapp", "email"],
    typicalFeeZar: "2000–30000",
    reportSa: "SAPS; SA Department of Employment and Labour (under Employment Services Act, charging worker fees is prohibited)",
    reportDestination: "UK Licensed Sponsor Register (gov.uk); MARA (Australia); CICC (Canada); IAA (New Zealand)",
    evidence: "confirmed",
    summary: "Scammers impersonate real SA mining and engineering employers (Anglo American/Kumba Iron Ore, Foskor, and Gold Fields South Deep have all issued formal warnings) and request upfront 'visa processing', 'sponsorship registration', or 'background check' fees. No legitimate employer or licensed recruiter charges a worker fees for visa sponsorship. For UK roles, verify the employer on gov.uk's Register of Licensed Sponsors. For AU, confirm an Engineers Australia skills assessment is part of the process. Never pay before a formal signed offer directly from the named employer.",
  },
  {
    name: "Fake Big Tech Recruiter Scam",
    category: "IT/Tech",
    vault: "Recruiter impersonation, Upfront fee, Coding-assessment malware",
    destinations: ["united kingdom", "ireland", "germany", "canada", "australia", "remote"],
    channels: ["linkedin", "whatsapp", "telegram", "email"],
    typicalFeeZar: "5000–50000",
    reportSa: "SAPS; SA Department of Employment and Labour",
    reportDestination: "FTC (US, ftc.gov); LinkedIn report-a-profile; destination employer's official careers team",
    evidence: "confirmed",
    summary: "Scammers create convincing LinkedIn profiles impersonating Google, Microsoft, Amazon or SA-destination tech recruiters. They target developers with 'Open to Work' active, offer remote-then-relocate roles above market rate, then extract upfront fees ('visa processing deposit', 'equipment advance') OR deliver malware via a fake coding assessment. LinkedIn removed 80.6M fake accounts H2 2024. FTC tracked USD$501M in job-scam losses 2024 — 'job offer' is now the highest-volume scam category. Verify any recruiter against the company's official careers page; never click a coding-assessment link sent via DM.",
  },
  {
    name: "Contagious Interview Malware",
    category: "IT/Tech",
    vault: "Coding-assessment malware, Credential theft",
    destinations: ["remote", "global"],
    channels: ["linkedin", "github", "email", "whatsapp"],
    typicalFeeZar: "0 (loss is via stolen credentials)",
    reportSa: "SAPS Cybercrime; CSIR Cybersecurity",
    reportDestination: "Microsoft Security Response Centre; GitHub abuse; LinkedIn",
    evidence: "confirmed",
    summary: "DPRK-linked campaign (Microsoft, March 2026) delivering BeaverTail / OtterCookie malware through fake developer job interviews. Targets are asked to clone a repo or run an 'environment setup' script as part of a coding test. Compromise extends beyond personal data — cloud infrastructure access (AWS/Azure/GCP), CI/CD pipeline keys, source code, and employer systems. NEVER clone a stranger's repo or run their setup script on your work machine. Use an isolated VM for any unsolicited assessment, or refuse and ask for a HackerRank/Codility-style hosted test.",
  },
  {
    name: "Scam Compound Recruitment (IT Job — Trafficking)",
    category: "IT/Tech",
    vault: "Trafficking, Life-safety, Fake IT job",
    destinations: ["cambodia", "myanmar", "laos", "thailand"],
    channels: ["linkedin", "facebook", "whatsapp", "telegram"],
    typicalFeeZar: "0 upfront — losses via passport confiscation + forced labour",
    reportSa: "SAPS Human Trafficking Unit (08600 10111); IOM South Africa; SA Embassy in destination",
    reportDestination: "INTERPOL Operation Storm Makers; destination embassy",
    evidence: "confirmed",
    summary: "Fake 'tech support' or 'customer service' IT job offers in Cambodia, Myanmar, Laos, or Thailand. INTERPOL, Reuters, and UN have documented organised criminal compounds where workers are trafficked, passports confiscated, and forced to run online scams under threat of violence. NEVER accept a tech job in SE Asia without independent verification of the employer's physical office, registered business number, and government registration. If a job pitch involves flying to Cambodia/Myanmar/Laos for an interview, refuse — there is no legitimate IT employer who needs you on a plane that fast.",
  },
  {
    name: "Germany Opportunity Card Agent Fraud",
    category: "IT/Tech",
    vault: "Upfront fee, Visa outcome unaffected",
    destinations: ["germany"],
    channels: ["facebook", "instagram", "whatsapp", "tiktok"],
    typicalFeeZar: "3000–30000",
    reportSa: "SAPS; SA Department of Employment and Labour",
    reportDestination: "German Embassy Pretoria (southafrica.diplo.de); BAMF",
    evidence: "alleged",
    summary: "SA-based 'consultants' charge R3k–R30k for Germany Opportunity Card (Chancenkarte) application 'guarantees'. The Opportunity Card application is a self-service process via the German Embassy — no agent has special access. Agents add no value beyond document templates available free at make-it-in-germany.com. Pay only for: SAPS PCC, DIRCO apostille, blocked account setup (Expatrio/Fintiba), and the embassy visa fee. Anything else is a scam.",
  },
  {
    name: "Dubai Crypto IT Job Scam",
    category: "IT/Tech",
    vault: "Trafficking, Fake employer, Crypto scam",
    destinations: ["uae"],
    channels: ["linkedin", "instagram", "whatsapp", "tinder"],
    typicalFeeZar: "0 upfront — losses via salary withholding + forced participation in pig-butchering scams",
    reportSa: "SAPS Human Trafficking Unit; SA Embassy UAE",
    reportDestination: "Dubai Police (901); FBI IC3 (ic3.gov)",
    evidence: "confirmed",
    summary: "Confirmed by FBI (2026) and Dubai Police. SA IT workers (especially crypto/Web3 developers) lured to Dubai with high-salary offers from 'crypto exchanges' or 'blockchain startups'. On arrival, passport confiscated, victim forced to run pig-butchering scams against Western targets, salary withheld. Often combined with romance scam on Tinder/Instagram beforehand. NEVER accept a UAE crypto/blockchain role without: a verifiable VARA licence (Dubai's Virtual Assets Regulatory Authority), a UAE trade licence number, and a video walk-through of the actual office before flying.",
  },
  {
    name: "Malicious Document Delivery via Fake Agents",
    category: "IT/Tech",
    vault: "Malware, Identity theft, Fake immigration agent",
    destinations: ["united kingdom", "ireland", "germany", "canada", "australia"],
    channels: ["whatsapp", "telegram", "email"],
    typicalFeeZar: "0 (loss via stolen identity / malware)",
    reportSa: "SAPS Cybercrime; SA Department of Employment and Labour",
    reportDestination: "IAA (UK); CICC (Canada); MARA (Australia); destination embassy",
    evidence: "alleged",
    summary: "Fake immigration agents send 'visa templates', 'CoS samples', or 'employer offer letters' as PDF/DOCX files containing macros or embedded payloads. Opening the file installs credential-stealing malware. SA developers are higher-value targets because of cloud admin credentials. NEVER open immigration document attachments from unverified senders. Verify every adviser at the official register: IAA (UK), CICC (Canada), MARA (Australia) — confirm name + reg number match before opening anything.",
  },
];
